// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.objects;

import nl.tno.oorti.test.mim4.datatypes.HLAfederateState;
import nl.tno.oorti.test.mim4.datatypes.HLAswitch;
import nl.tno.oorti.test.mim4.datatypes.HLAtimeState;

/**
 * This object class shall contain RTI state variables relating to a joined federate. The RTI shall
 * publish it and shall register one object instance for each joined federate in a federation.
 * Dynamic attributes that shall be contained in an object instance shall be updated periodically,
 * where the period should be determined by an interaction of the class
 * HLAmanager.HLAfederate.HLAadjust.HLAsetTiming. If this value is never set or is set to zero, no
 * periodic update shall be performed by the RTI.
 *
 * <p>The RTI shall respond to the invocation, by any federate, of the Request Attribute Value
 * Update service for this object class or for any instance attribute of an object instance of this
 * class by supplying values via the normal instance attribute update mechanism, regardless of
 * whether the attribute has a data type of static, periodic, or conditional. In addition to its
 * responsibility to update attributes of object instances of this class when those updates are
 * explicitly requested, the RTI shall automatically update instance attributes of object instances
 * of this class according to the update policy of the attribute, which is determined by the update
 * type of the class attribute in Table 6. For those attributes that have an update type of
 * Periodic, the update wall-clock time interval shall be determined by the HLAreportPeriod
 * parameter in an interaction of classHLAmanager.HLAfederate. HLAadjust.HLAsetTiming. If this value
 * is never set or is set to zero, no periodic updates shall be performed by the RTI. Those
 * attributes that have an update type of Conditional shall have update conditions as defined in the
 * Table 6.
 */
public class HLAfederate extends HLAmanager {

  /** Handle of the joined federate returned by a Join Federation Execution service invocation */
  byte[] HLAfederateHandle;

  /**
   * Name of the joined federate supplied to a successful Join Federation Execution service
   * invocation
   */
  String HLAfederateName;

  /** Type of the joined federate specified by the joined federate when it joined the federation */
  String HLAfederateType;

  /** Host name of the computer on which the joined federate is executing */
  String HLAfederateHost;

  /** Version of the RTI software being used */
  String HLARTIversion;

  /**
   * FOM Module designators as specified by the federate when the Join Federation Execution service
   * was invoked. If several identical FOM modules are provided only the designator of the first of
   * these FOM modules shall be added to the list.
   */
  String[] HLAFOMmoduleDesignatorList;

  /**
   * Whether the time advancement of the joined federate is constrained by other joined federates
   */
  Boolean HLAtimeConstrained;

  /** Whether the joined federate influences the time advancement of other joined federates */
  Boolean HLAtimeRegulating;

  /**
   * Whether the RTI shall deliver RO messages to the joined federate while the joined federate's
   * time manager state is not "Time Advancing" (only matters if the joined federate is
   * time-constrained).
   */
  Boolean HLAasynchronousDelivery;

  /**
   * State of the joined federate. The MOM may, but is not required to, update any HLAfederateState
   * instance attribute values during the interval after the last federate in the federation
   * execution invokes the Federate Restore Complete service but before the last Federation Restored
   * † callback is invoked at some federate for a given federation restoration.
   */
  HLAfederateState HLAfederateState;

  /** State of the joined federate's time manager */
  HLAtimeState HLAtimeManagerState;

  /**
   * Joined federate's logical time. Initial value of this information is initial value of
   * federation time of the Time Representation Abstract Data Type (TRADT).
   */
  byte[] HLAlogicalTime;

  /**
   * Minimum duration into the future that a TSO message will be scheduled. The value shall not be
   * defined if the joined federate is not time-regulating)
   */
  byte[] HLAlookahead;

  /**
   * Joined federate's Greatest Available Logical Time (GALT). The value shall not be defined if
   * GALT is not defined for the joined federate.
   */
  byte[] HLAGALT;

  /**
   * Joined federate's Least Incoming Time Stamp (LITS). The value shall not be defined if LITS is
   * not defined for the joined federate.
   */
  byte[] HLALITS;

  /** Number of RO messages queued for delivery to the joined federate. */
  Integer HLAROlength;

  /** Number of TSO messages queued for delivery to the joined federate */
  Integer HLATSOlength;

  /**
   * Total number of times the Reflect Attribute Values † service has been invoked at the joined
   * federate (as opposed to the number of instance attribute value reflections that have been
   * received at the joined federate).
   */
  Integer HLAreflectionsReceived;

  /**
   * Total number of updates sent by the joined federate" in XML and "Total number of times the
   * Update Attribute Values † service has successfully been invoked by the joined federate (as
   * opposed to the number of instance attribute values that have been updated by the joined
   * federate).
   */
  Integer HLAupdatesSent;

  /** Total number of interactions received by the joined federate. */
  Integer HLAinteractionsReceived;

  /**
   * Total number of interactions sent by the joined federate. This information shall reflect
   * related DDM usage.
   */
  Integer HLAinteractionsSent;

  /**
   * Total number of object instances whose HLAprivilegeToDeleteObject attribute is owned by the
   * joined federate
   */
  Integer HLAobjectInstancesThatCanBeDeleted;

  /**
   * Total number of object instances for which the joined federate has invoked the Update Attribute
   * Values service.
   */
  Integer HLAobjectInstancesUpdated;

  /**
   * Total number of object instances for which the joined federate has had a Reflect Attribute
   * Values service invocation.
   */
  Integer HLAobjectInstancesReflected;

  /**
   * Total number of times the Delete Object Instance service was invoked by the joined federate
   * since the federate joined the federation
   */
  Integer HLAobjectInstancesDeleted;

  /**
   * Total number of times the Remove Object Instance service was invoked for the joined federate
   * since the federate joined the federation.
   */
  Integer HLAobjectInstancesRemoved;

  /**
   * Total number of times the Register Object Instance or Register Object Instance with Region
   * service were invoked by the joined federate since the federate joined the federation.
   */
  Integer HLAobjectInstancesRegistered;

  /**
   * Total number of times the Discover Object Instance † service was invoked for the joined
   * federate since the federate joined the federation.The value of the HLAobjectInstancesDiscovered
   * attribute shall include multiple invocations of the Discover Object Instance † service for a
   * given object instance that may occur as a result of invocation of the Local Delete Object
   * Instance service at a federate.
   */
  Integer HLAobjectInstancesDiscovered;

  /**
   * Wall clock time duration that the federate has spent in the Time Granted state since the last
   * update of this attribute. When the HLAtimeGrantedTime and the HLAtimeAdvancingTime attributes
   * are initially updated, their values shall be the wall-clock time duration that the federate has
   * spent in the state since the federate has been joined to the federation execution.
   */
  Integer HLAtimeGrantedTime;

  /**
   * Wall clock time duration that the federate has spent in the Time Advancing state since the last
   * update of this attribute. When the HLAtimeGrantedTime and the HLAtimeAdvancingTime attributes
   * are initially updated, their values shall be the wall-clock time duration that the federate has
   * spent in the state since the federate has been joined to the federation execution.
   */
  Integer HLAtimeAdvancingTime;

  /**
   * Value of joined federate's Convey Region Designator Sets Switch. Updated when value of switch
   * changes
   */
  HLAswitch HLAconveyRegionDesignatorSets;

  /**
   * Value of joined federate's Convey Producing Federate Switch. Updated when value of switch
   * changes
   */
  HLAswitch HLAconveyProducingFederate;

  public byte[] getHLAfederateHandle() {
    return this.HLAfederateHandle;
  }

  public void setHLAfederateHandle(byte[] HLAfederateHandle) {
    this.HLAfederateHandle = HLAfederateHandle;
  }

  public String getHLAfederateName() {
    return this.HLAfederateName;
  }

  public void setHLAfederateName(String HLAfederateName) {
    this.HLAfederateName = HLAfederateName;
  }

  public String getHLAfederateType() {
    return this.HLAfederateType;
  }

  public void setHLAfederateType(String HLAfederateType) {
    this.HLAfederateType = HLAfederateType;
  }

  public String getHLAfederateHost() {
    return this.HLAfederateHost;
  }

  public void setHLAfederateHost(String HLAfederateHost) {
    this.HLAfederateHost = HLAfederateHost;
  }

  public String getHLARTIversion() {
    return this.HLARTIversion;
  }

  public void setHLARTIversion(String HLARTIversion) {
    this.HLARTIversion = HLARTIversion;
  }

  public String[] getHLAFOMmoduleDesignatorList() {
    return this.HLAFOMmoduleDesignatorList;
  }

  public void setHLAFOMmoduleDesignatorList(String[] HLAFOMmoduleDesignatorList) {
    this.HLAFOMmoduleDesignatorList = HLAFOMmoduleDesignatorList;
  }

  public Boolean getHLAtimeConstrained() {
    return this.HLAtimeConstrained;
  }

  public void setHLAtimeConstrained(Boolean HLAtimeConstrained) {
    this.HLAtimeConstrained = HLAtimeConstrained;
  }

  public Boolean getHLAtimeRegulating() {
    return this.HLAtimeRegulating;
  }

  public void setHLAtimeRegulating(Boolean HLAtimeRegulating) {
    this.HLAtimeRegulating = HLAtimeRegulating;
  }

  public Boolean getHLAasynchronousDelivery() {
    return this.HLAasynchronousDelivery;
  }

  public void setHLAasynchronousDelivery(Boolean HLAasynchronousDelivery) {
    this.HLAasynchronousDelivery = HLAasynchronousDelivery;
  }

  public HLAfederateState getHLAfederateState() {
    return this.HLAfederateState;
  }

  public void setHLAfederateState(HLAfederateState HLAfederateState) {
    this.HLAfederateState = HLAfederateState;
  }

  public HLAtimeState getHLAtimeManagerState() {
    return this.HLAtimeManagerState;
  }

  public void setHLAtimeManagerState(HLAtimeState HLAtimeManagerState) {
    this.HLAtimeManagerState = HLAtimeManagerState;
  }

  public byte[] getHLAlogicalTime() {
    return this.HLAlogicalTime;
  }

  public void setHLAlogicalTime(byte[] HLAlogicalTime) {
    this.HLAlogicalTime = HLAlogicalTime;
  }

  public byte[] getHLAlookahead() {
    return this.HLAlookahead;
  }

  public void setHLAlookahead(byte[] HLAlookahead) {
    this.HLAlookahead = HLAlookahead;
  }

  public byte[] getHLAGALT() {
    return this.HLAGALT;
  }

  public void setHLAGALT(byte[] HLAGALT) {
    this.HLAGALT = HLAGALT;
  }

  public byte[] getHLALITS() {
    return this.HLALITS;
  }

  public void setHLALITS(byte[] HLALITS) {
    this.HLALITS = HLALITS;
  }

  public Integer getHLAROlength() {
    return this.HLAROlength;
  }

  public void setHLAROlength(Integer HLAROlength) {
    this.HLAROlength = HLAROlength;
  }

  public Integer getHLATSOlength() {
    return this.HLATSOlength;
  }

  public void setHLATSOlength(Integer HLATSOlength) {
    this.HLATSOlength = HLATSOlength;
  }

  public Integer getHLAreflectionsReceived() {
    return this.HLAreflectionsReceived;
  }

  public void setHLAreflectionsReceived(Integer HLAreflectionsReceived) {
    this.HLAreflectionsReceived = HLAreflectionsReceived;
  }

  public Integer getHLAupdatesSent() {
    return this.HLAupdatesSent;
  }

  public void setHLAupdatesSent(Integer HLAupdatesSent) {
    this.HLAupdatesSent = HLAupdatesSent;
  }

  public Integer getHLAinteractionsReceived() {
    return this.HLAinteractionsReceived;
  }

  public void setHLAinteractionsReceived(Integer HLAinteractionsReceived) {
    this.HLAinteractionsReceived = HLAinteractionsReceived;
  }

  public Integer getHLAinteractionsSent() {
    return this.HLAinteractionsSent;
  }

  public void setHLAinteractionsSent(Integer HLAinteractionsSent) {
    this.HLAinteractionsSent = HLAinteractionsSent;
  }

  public Integer getHLAobjectInstancesThatCanBeDeleted() {
    return this.HLAobjectInstancesThatCanBeDeleted;
  }

  public void setHLAobjectInstancesThatCanBeDeleted(Integer HLAobjectInstancesThatCanBeDeleted) {
    this.HLAobjectInstancesThatCanBeDeleted = HLAobjectInstancesThatCanBeDeleted;
  }

  public Integer getHLAobjectInstancesUpdated() {
    return this.HLAobjectInstancesUpdated;
  }

  public void setHLAobjectInstancesUpdated(Integer HLAobjectInstancesUpdated) {
    this.HLAobjectInstancesUpdated = HLAobjectInstancesUpdated;
  }

  public Integer getHLAobjectInstancesReflected() {
    return this.HLAobjectInstancesReflected;
  }

  public void setHLAobjectInstancesReflected(Integer HLAobjectInstancesReflected) {
    this.HLAobjectInstancesReflected = HLAobjectInstancesReflected;
  }

  public Integer getHLAobjectInstancesDeleted() {
    return this.HLAobjectInstancesDeleted;
  }

  public void setHLAobjectInstancesDeleted(Integer HLAobjectInstancesDeleted) {
    this.HLAobjectInstancesDeleted = HLAobjectInstancesDeleted;
  }

  public Integer getHLAobjectInstancesRemoved() {
    return this.HLAobjectInstancesRemoved;
  }

  public void setHLAobjectInstancesRemoved(Integer HLAobjectInstancesRemoved) {
    this.HLAobjectInstancesRemoved = HLAobjectInstancesRemoved;
  }

  public Integer getHLAobjectInstancesRegistered() {
    return this.HLAobjectInstancesRegistered;
  }

  public void setHLAobjectInstancesRegistered(Integer HLAobjectInstancesRegistered) {
    this.HLAobjectInstancesRegistered = HLAobjectInstancesRegistered;
  }

  public Integer getHLAobjectInstancesDiscovered() {
    return this.HLAobjectInstancesDiscovered;
  }

  public void setHLAobjectInstancesDiscovered(Integer HLAobjectInstancesDiscovered) {
    this.HLAobjectInstancesDiscovered = HLAobjectInstancesDiscovered;
  }

  public Integer getHLAtimeGrantedTime() {
    return this.HLAtimeGrantedTime;
  }

  public void setHLAtimeGrantedTime(Integer HLAtimeGrantedTime) {
    this.HLAtimeGrantedTime = HLAtimeGrantedTime;
  }

  public Integer getHLAtimeAdvancingTime() {
    return this.HLAtimeAdvancingTime;
  }

  public void setHLAtimeAdvancingTime(Integer HLAtimeAdvancingTime) {
    this.HLAtimeAdvancingTime = HLAtimeAdvancingTime;
  }

  public HLAswitch getHLAconveyRegionDesignatorSets() {
    return this.HLAconveyRegionDesignatorSets;
  }

  public void setHLAconveyRegionDesignatorSets(HLAswitch HLAconveyRegionDesignatorSets) {
    this.HLAconveyRegionDesignatorSets = HLAconveyRegionDesignatorSets;
  }

  public HLAswitch getHLAconveyProducingFederate() {
    return this.HLAconveyProducingFederate;
  }

  public void setHLAconveyProducingFederate(HLAswitch HLAconveyProducingFederate) {
    this.HLAconveyProducingFederate = HLAconveyProducingFederate;
  }
}
