// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;
import nl.tno.oorti.test.netn4.datatypes.RelativePositionStruct;

/**
 * Specifies the occurrence of a transient acoustic event such as torpedo tube floodings, hatch
 * slams, and wrench drops.
 */
public class AcousticTransient extends HLAinteractionRoot {

  /** Index into a data base of transient acoustic events */
  Short ActivityCode;

  /** The current state of the activity specified by the activity code */
  Short ActivityParameter;

  /** The Object Instance ID of the object emitting the sound */
  String HostObjectIdentifier;

  /** The location of the sound relative to the hosts coordinate system */
  RelativePositionStruct RelativePosition;

  public Short getActivityCode() {
    return this.ActivityCode;
  }

  public void setActivityCode(Short ActivityCode) {
    this.ActivityCode = ActivityCode;
  }

  public Short getActivityParameter() {
    return this.ActivityParameter;
  }

  public void setActivityParameter(Short ActivityParameter) {
    this.ActivityParameter = ActivityParameter;
  }

  public String getHostObjectIdentifier() {
    return this.HostObjectIdentifier;
  }

  public void setHostObjectIdentifier(String HostObjectIdentifier) {
    this.HostObjectIdentifier = HostObjectIdentifier;
  }

  public RelativePositionStruct getRelativePosition() {
    return this.RelativePosition;
  }

  public void setRelativePosition(RelativePositionStruct RelativePosition) {
    this.RelativePosition = RelativePosition;
  }
}
