// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;

/**
 * Trigger the specified federate to initiate a transfer of modelling responsibility for the
 * specified entity.
 */
public class AcquireModellingResponsibility extends SMC_FederateControl {

  /** Required: Reference to the object which is to be transferred. */
  UUID Entity;

  public UUID getEntity() {
    return this.Entity;
  }

  public void setEntity(UUID Entity) {
    this.Entity = Entity;
  }
}
