// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.AcknowledgementProtocolEnum8;

/**
 * A Simulation Management (SIMAN) interaction sent from a Simulation Manager federate to one or
 * more federates to request that they perform a specified action. The Simulation Manager federate
 * specifies the acknowledgement protocol to be used.
 */
public class ActionRequestR extends ActionRequest {

  /** The acknowledgement protocol to be used for a transaction */
  AcknowledgementProtocolEnum8 AcknowledgementProtocol;

  public AcknowledgementProtocolEnum8 getAcknowledgementProtocol() {
    return this.AcknowledgementProtocol;
  }

  public void setAcknowledgementProtocol(AcknowledgementProtocolEnum8 AcknowledgementProtocol) {
    this.AcknowledgementProtocol = AcknowledgementProtocol;
  }
}
