// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * This is the root interaction class for all AIS messages. The interaction class contains a
 * reference to the embedded system that represents the AIS transmitter. The embedded system should
 * be modelled as a RadioTransmitter, an RPR-FOM object class that is subclassed from Embedded
 * System.
 */
public class AIS_RadioSignal extends RadioSignal {

  /**
   * Optional (Default: not available). The HostRadioIndex is a unique string that identifies the
   * name of the RadioTransmitter object.
   */
  String HostRadioIndex;

  public String getHostRadioIndex() {
    return this.HostRadioIndex;
  }

  public void setHostRadioIndex(String HostRadioIndex) {
    this.HostRadioIndex = HostRadioIndex;
  }
}
