// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Binary Payload for Message Types 6 and 8. The interpretation of the binary payload is controlled
 * by: - The Designated Area Code (DAC), is a jurisdiction code: 366 for the United States. It uses
 * the same encoding as the area designator in MMMSIs; see [ITU-MID]. 1 designates international
 * (ITU) messages. - The FID is the Functional ID for a message subtype. In some sources, this is
 * abbreviated FI.
 */
public class AisBinaryMessageData extends AisMessage {

  /** Required. Designated area code (DAC). */
  Integer DesignatedAreaCode;

  /** Required. Functional ID (FID). */
  Integer FunctionId;

  /** Required. Binary data up to 920 bits. */
  boolean[] Data;

  public Integer getDesignatedAreaCode() {
    return this.DesignatedAreaCode;
  }

  public void setDesignatedAreaCode(Integer DesignatedAreaCode) {
    this.DesignatedAreaCode = DesignatedAreaCode;
  }

  public Integer getFunctionId() {
    return this.FunctionId;
  }

  public void setFunctionId(Integer FunctionId) {
    this.FunctionId = FunctionId;
  }

  public boolean[] getData() {
    return this.Data;
  }

  public void setData(boolean[] Data) {
    this.Data = Data;
  }
}
