// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeodeticLocation;

/**
 * Common reporting structure for Message Types 4 and 11 for reporting UTC time and date and, at the
 * same time, position. It is also used by AIS stations for determining if the station is within 120
 * NM for response to Messages Types 20 and 23.
 */
public class AisBaseStationReportAndUTCDateResponseData extends AisMessage {

  /** Optional (Default: not available). Time of report. */
  Integer UTCtime;

  /** Optional (Default: not available). AIS (Lat,Lon) position. */
  GeodeticLocation Position;

  public Integer getUTCtime() {
    return this.UTCtime;
  }

  public void setUTCtime(Integer UTCtime) {
    this.UTCtime = UTCtime;
  }

  public GeodeticLocation getPosition() {
    return this.Position;
  }

  public void setPosition(GeodeticLocation Position) {
    this.Position = Position;
  }
}
