// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Message Type 5: Static and Voyage-Related Data.
 *
 * <p>This message type is transmitted every 6 minutes and should only be used by Class A shipborne
 * and SAR aircraft AIS stations when reporting static or voyage-related data.
 */
public class AisMessage5 extends AisStaticAndVoyageData {

  /** Optional (Default: zero). The IMO ship ID number. Not applicable to SAR aircraft. */
  Integer IMO;

  /**
   * Optional (Default: not available). Estimated time of arrival. Not applicable to SAR aircraft.
   * If a zero value is provided then this shall be interpreted as not available.
   */
  Integer ETAtime;

  /** Optional (Default: not available). Maximum present static draught. */
  Float Draught;

  /**
   * Optional (Default: not available, 20 six-bit "@" value). 20 six-bit characters for the
   * destination. For SAR aircraft, the use of this field may be decided by the responsible
   * administration.
   */
  String Destination;

  public Integer getIMO() {
    return this.IMO;
  }

  public void setIMO(Integer IMO) {
    this.IMO = IMO;
  }

  public Integer getETAtime() {
    return this.ETAtime;
  }

  public void setETAtime(Integer ETAtime) {
    this.ETAtime = ETAtime;
  }

  public Float getDraught() {
    return this.Draught;
  }

  public void setDraught(Float Draught) {
    this.Draught = Draught;
  }

  public String getDestination() {
    return this.Destination;
  }

  public void setDestination(String Destination) {
    this.Destination = Destination;
  }
}
