// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.MsgIdEnum8;

/** Super class for all AIS message types. */
public class AisMessage extends AIS_RadioSignal {

  /** Required. Message type identifier. */
  MsgIdEnum8 MessageId;

  /** Required. The message is from the vessel identified by this MMSI. */
  Integer UserId;

  public MsgIdEnum8 getMessageId() {
    return this.MessageId;
  }

  public void setMessageId(MsgIdEnum8 MessageId) {
    this.MessageId = MessageId;
  }

  public Integer getUserId() {
    return this.UserId;
  }

  public void setUserId(Integer UserId) {
    this.UserId = UserId;
  }
}
