// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Message Type 10: UTC/Date Inquiry.
 *
 * <p>Request for UTC/Date information from an AIS base station.
 */
public class AisMessage10 extends AisMessage {

  /** Required. Destination MMSI. */
  Integer Destination;

  public Integer getDestination() {
    return this.Destination;
  }

  public void setDestination(Integer Destination) {
    this.Destination = Destination;
  }
}
