// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Type 14: Safety-Related Broadcast Message.
 *
 * <p>This is a broadcast text message. The payload is interpreted as six-bit text.
 */
public class AisMessage14 extends AisMessage {

  /** Required. 1-161 chars of six-bit text. */
  String Message;

  public String getMessage() {
    return this.Message;
  }

  public void setMessage(String Message) {
    this.Message = Message;
  }
}
