// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeodeticLocation;

/**
 * Message type 9: Standard SAR Aircraft Position Report.
 *
 * <p>Tracking information for search-and-rescue aircraft.
 */
public class AisMessage9 extends AisMessage {

  /** Optional (Default: not available). Altitude. */
  Double Altitude;

  /** Optional (Default: not available). Speed over the ground. */
  Float SpeedOverGround;

  /** Optional (Default: not available). AIS (Lat,Lon) position. */
  GeodeticLocation Position;

  /** Optional (Default: not available). Course over the ground. */
  Float CourseOverGround;

  /** Optional (Default: not available). Time of the report. */
  Integer UTCtime;

  public Double getAltitude() {
    return this.Altitude;
  }

  public void setAltitude(Double Altitude) {
    this.Altitude = Altitude;
  }

  public Float getSpeedOverGround() {
    return this.SpeedOverGround;
  }

  public void setSpeedOverGround(Float SpeedOverGround) {
    this.SpeedOverGround = SpeedOverGround;
  }

  public GeodeticLocation getPosition() {
    return this.Position;
  }

  public void setPosition(GeodeticLocation Position) {
    this.Position = Position;
  }

  public Float getCourseOverGround() {
    return this.CourseOverGround;
  }

  public void setCourseOverGround(Float CourseOverGround) {
    this.CourseOverGround = CourseOverGround;
  }

  public Integer getUTCtime() {
    return this.UTCtime;
  }

  public void setUTCtime(Integer UTCtime) {
    this.UTCtime = UTCtime;
  }
}
