// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

/**
 * Message Type 8: Binary Broadcast Message.
 *
 * <p>This message type is a broadcast message with a binary payload.
 */
public class AisMessage8 extends AisBinaryMessageData {}
