// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeodeticLocation;

/**
 * Message Type 18: Standard Class B CS Position Report.
 *
 * <p>A less detailed report than message types 1-3 for vessels using Class B transmitters. Omits
 * navigational status and rate of turn.
 */
public class AisMessage18 extends AisMessage {

  /** Optional (Default: not available). Speed over the ground. */
  Float SpeedOverGround;

  /** Optional (Default: not available). AIS (Lat,Lon) position. */
  GeodeticLocation Position;

  /** Optional (Default: not available). Course over the ground. */
  Float CourseOverGround;

  /** Optional (Default: not available). True heading. */
  Float TrueHeading;

  /** Optional (Default: not available). Time of the report. */
  Integer UTCtime;

  public Float getSpeedOverGround() {
    return this.SpeedOverGround;
  }

  public void setSpeedOverGround(Float SpeedOverGround) {
    this.SpeedOverGround = SpeedOverGround;
  }

  public GeodeticLocation getPosition() {
    return this.Position;
  }

  public void setPosition(GeodeticLocation Position) {
    this.Position = Position;
  }

  public Float getCourseOverGround() {
    return this.CourseOverGround;
  }

  public void setCourseOverGround(Float CourseOverGround) {
    this.CourseOverGround = CourseOverGround;
  }

  public Float getTrueHeading() {
    return this.TrueHeading;
  }

  public void setTrueHeading(Float TrueHeading) {
    this.TrueHeading = TrueHeading;
  }

  public Integer getUTCtime() {
    return this.UTCtime;
  }

  public void setUTCtime(Integer UTCtime) {
    this.UTCtime = UTCtime;
  }
}
