// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Type 12: Addressed Safety-Related Message.
 *
 * <p>This is a point-to-point text message. The payload is interpreted as six-bit text.
 */
public class AisMessage12 extends AisMessage {

  /** Required. Destination MMSI. */
  Integer Destination;

  /** Required. 1-156 chars of six-bit text. */
  String Message;

  public Integer getDestination() {
    return this.Destination;
  }

  public void setDestination(Integer Destination) {
    this.Destination = Destination;
  }

  public String getMessage() {
    return this.Message;
  }

  public void setMessage(String Message) {
    this.Message = Message;
  }
}
