// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeodeticLocation;

/**
 * Message Type 17: DGNSS Broadcast Binary Message.
 *
 * <p>This message type is used to broadcast differential corrections for GPS.
 */
public class AisMessage17 extends AisMessage {

  /** Optional (Default: not available). Position data. */
  GeodeticLocation Position;

  public GeodeticLocation getPosition() {
    return this.Position;
  }

  public void setPosition(GeodeticLocation Position) {
    this.Position = Position;
  }
}
