// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

/**
 * Message Type 11: UTC/Date Response.
 *
 * <p>Identical to Message Type 4, with the semantics of a response to inquiry. This message type is
 * only transmitted from a mobile station as a result of a UTC request message (Message Type 10).
 */
public class AisMessage11 extends AisBaseStationReportAndUTCDateResponseData {}
