// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * Message Type 4: Base Station Report.
 *
 * <p>This message is to be used by fixed-location base stations to periodically report a position
 * and time reference.
 */
public class AisMessage4 extends AisBaseStationReportAndUTCDateResponseData {}
