// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeodeticLocation;
import nl.tno.oorti.test.netn4.datatypes.ManeuverIndicatorEnum8;
import nl.tno.oorti.test.netn4.datatypes.NavigationStatusEnum8;

/**
 * Message Types 1, 2 and 3 share a common reporting structure for navigational data, captured in
 * this class.
 */
public class AisNavigationData extends AisMessage {

  /** Optional (Default: not defined). Navigational status. */
  NavigationStatusEnum8 NavigationalStatus;

  /** Optional (Default: not available). Rate of turn. */
  Float RateOfTurn;

  /** Optional (Default: not available). Speed over the ground. */
  Float SpeedOverGround;

  /** Optional (Default: not available). AIS (Lat,Lon) position. */
  GeodeticLocation Position;

  /** Optional (Default: not available). Course over the ground. */
  Float CourseOverGround;

  /** Optional (Default: not available). True heading. */
  Float TrueHeading;

  /** Optional (Default: not available). Time of the report. */
  Integer UTCtime;

  /** Optional (Default: not available). Maneuver indication. */
  ManeuverIndicatorEnum8 SpecialManeuverIndicator;

  public NavigationStatusEnum8 getNavigationalStatus() {
    return this.NavigationalStatus;
  }

  public void setNavigationalStatus(NavigationStatusEnum8 NavigationalStatus) {
    this.NavigationalStatus = NavigationalStatus;
  }

  public Float getRateOfTurn() {
    return this.RateOfTurn;
  }

  public void setRateOfTurn(Float RateOfTurn) {
    this.RateOfTurn = RateOfTurn;
  }

  public Float getSpeedOverGround() {
    return this.SpeedOverGround;
  }

  public void setSpeedOverGround(Float SpeedOverGround) {
    this.SpeedOverGround = SpeedOverGround;
  }

  public GeodeticLocation getPosition() {
    return this.Position;
  }

  public void setPosition(GeodeticLocation Position) {
    this.Position = Position;
  }

  public Float getCourseOverGround() {
    return this.CourseOverGround;
  }

  public void setCourseOverGround(Float CourseOverGround) {
    this.CourseOverGround = CourseOverGround;
  }

  public Float getTrueHeading() {
    return this.TrueHeading;
  }

  public void setTrueHeading(Float TrueHeading) {
    this.TrueHeading = TrueHeading;
  }

  public Integer getUTCtime() {
    return this.UTCtime;
  }

  public void setUTCtime(Integer UTCtime) {
    this.UTCtime = UTCtime;
  }

  public ManeuverIndicatorEnum8 getSpecialManeuverIndicator() {
    return this.SpecialManeuverIndicator;
  }

  public void setSpecialManeuverIndicator(ManeuverIndicatorEnum8 SpecialManeuverIndicator) {
    this.SpecialManeuverIndicator = SpecialManeuverIndicator;
  }
}
