// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;
import nl.tno.oorti.test.netn4.datatypes.AttributeValuePairStruct;

/**
 * A Simulation Management (SIMAN) interaction, sent from a Simulation Manager federate to ask that
 * a specified attribute be set to a specified value.
 */
public class AttributeChangeRequest extends HLAinteractionRoot {

  /** The list of objects that are the intended recipients of this interaction. */
  String[] ObjectIdentifiers;

  /** The set of attributes and their values, that the recipients are asked to update. */
  AttributeValuePairStruct[] AttributeValueSet;

  public String[] getObjectIdentifiers() {
    return this.ObjectIdentifiers;
  }

  public void setObjectIdentifiers(String[] ObjectIdentifiers) {
    this.ObjectIdentifiers = ObjectIdentifiers;
  }

  public AttributeValuePairStruct[] getAttributeValueSet() {
    return this.AttributeValueSet;
  }

  public void setAttributeValueSet(AttributeValuePairStruct[] AttributeValueSet) {
    this.AttributeValueSet = AttributeValueSet;
  }
}
