// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.BreachStruct;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the BreachObject class.
 */
public class BreachObjectTransaction extends LinearObjectTransaction {

  /** Specifies a breach linear object */
  BreachStruct[] SegmentRecords;

  public BreachStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(BreachStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
