// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;

/** Request to cancel all one or more tasks. */
public class CancelTasks extends SMC_EntityControl {

  /**
   * Required. Tasks to cancel. If no specific tasks are indicated, the default is to cancel all
   * scheduled and ongoing tasks for the simulation entity.
   */
  UUID[] Tasks;

  public UUID[] getTasks() {
    return this.Tasks;
  }

  public void setTasks(UUID[] Tasks) {
    this.Tasks = Tasks;
  }
}
