// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.AgentTypeEnum16;

/** Sends information about the current state of a previously registered CBRN sensor. */
public class CBRN_SensorUpdate extends ETR_SensorEvent {

  /** Required: Type of the agent. */
  AgentTypeEnum16 Agent;

  /** Required: Mean Concentration in kg m-3. */
  Float Concentration;

  public AgentTypeEnum16 getAgent() {
    return this.Agent;
  }

  public void setAgent(AgentTypeEnum16 Agent) {
    this.Agent = Agent;
  }

  public Float getConcentration() {
    return this.Concentration;
  }

  public void setConcentration(Float Concentration) {
    this.Concentration = Concentration;
  }
}
