// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;

/**
 * Request a change in the organizational structure. The federate with the primary responsibility of
 * the referenced entity (OrganizationElement) should if possible update the `SuperiorUnit`
 * relationship.
 */
public class ChangeSuperiorUnit extends SMC_EntityControl {

  /**
   * Required: Reference to a Unit for which the referenced entity (OrganizationElement) is
   * requested to relate to as a subunit/equipment.
   */
  UUID SuperiorUnit;

  public UUID getSuperiorUnit() {
    return this.SuperiorUnit;
  }

  public void setSuperiorUnit(UUID SuperiorUnit) {
    this.SuperiorUnit = SuperiorUnit;
  }
}
