// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.ChangeRulesOfEngagementTaskStruct;

/** Instructs the simulation entity to change its rules of engagement immediately. */
public class ChangeRulesOfEngagement extends Task {

  /** Required: Task parameters. */
  ChangeRulesOfEngagementTaskStruct TaskParameters;

  public ChangeRulesOfEngagementTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(ChangeRulesOfEngagementTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
