// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.ChangeSpeedTaskStruct;

/** Tasking of an entity to change speed. */
public class ChangeSpeed extends Task {

  /** Required: Task parameters. */
  ChangeSpeedTaskStruct TaskParameters;

  public ChangeSpeedTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(ChangeSpeedTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
