// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.ChangeAltitudeTaskStruct;

/** Tasking of an entity to set move to a specified altitude. */
public class ChangeAltitude extends Task {

  /** Required: Task parameters. */
  ChangeAltitudeTaskStruct TaskParameters;

  public ChangeAltitudeTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(ChangeAltitudeTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
