// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the CraterObject class.
 */
public class CraterObjectTransaction extends PointObjectTransaction {

  /**
   * Specifies the diameter of the crater, where the center of the crater is at the point object
   * location
   */
  Integer CraterSize;

  public Integer getCraterSize() {
    return this.CraterSize;
  }

  public void setCraterSize(Integer CraterSize) {
    this.CraterSize = CraterSize;
  }
}
