// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.CreateBreachTaskStruct;

/** Requests a simulated entity to create a breach or passage on a breachable engineering object. */
public class CreateBreach extends Task {

  /** Required: Task parameters. */
  CreateBreachTaskStruct TaskParameters;

  public CreateBreachTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(CreateBreachTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
