// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.CreateFireBreakTaskStruct;

/** Use the `CreateFireBreak` task to request an entity to build a firebreak. */
public class CreateFireBreak extends Task {

  /** Required: Task parameters. */
  CreateFireBreakTaskStruct TaskParameters;

  public CreateFireBreakTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(CreateFireBreakTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
