// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a
 * CreateObjectRequest from a Simulation Manager federate and to inform the Simulation Manager
 * federate whether the object creation was successful or not. The Simulation Manager federate
 * specifies the acknowledgement protocol to be used.
 */
public class CreateObjectResultR extends CreateObjectResult {}
