// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.TacticalDataLinkTypeEnum16;

/**
 * A radio signal that represents transmission of a pre-determined message by using a pre-defined
 * database index.
 */
public class DatabaseIndexRadioSignal extends RadioSignal {

  /** The object instance ID of the radio transmitting this signal. */
  String HostRadioIndex;

  /** The index into the federation specific database of stored signals. */
  Integer DatabaseIndex;

  /** The duration of the stored signal to be replayed. */
  Integer Duration;

  /** The offset, from the start of the stored signal, that the signal is replayed from. */
  Integer StartOffset;

  /** The type of tactical data link used to transmitted this signal (if any). */
  TacticalDataLinkTypeEnum16 TacticalDataLinkType;

  /** The number of tactical data link messages contained in this signal. */
  Short TDLMessageCount;

  public String getHostRadioIndex() {
    return this.HostRadioIndex;
  }

  public void setHostRadioIndex(String HostRadioIndex) {
    this.HostRadioIndex = HostRadioIndex;
  }

  public Integer getDatabaseIndex() {
    return this.DatabaseIndex;
  }

  public void setDatabaseIndex(Integer DatabaseIndex) {
    this.DatabaseIndex = DatabaseIndex;
  }

  public Integer getDuration() {
    return this.Duration;
  }

  public void setDuration(Integer Duration) {
    this.Duration = Duration;
  }

  public Integer getStartOffset() {
    return this.StartOffset;
  }

  public void setStartOffset(Integer StartOffset) {
    this.StartOffset = StartOffset;
  }

  public TacticalDataLinkTypeEnum16 getTacticalDataLinkType() {
    return this.TacticalDataLinkType;
  }

  public void setTacticalDataLinkType(TacticalDataLinkTypeEnum16 TacticalDataLinkType) {
    this.TacticalDataLinkType = TacticalDataLinkType;
  }

  public Short getTDLMessageCount() {
    return this.TDLMessageCount;
  }

  public void setTDLMessageCount(Short TDLMessageCount) {
    this.TDLMessageCount = TDLMessageCount;
  }
}
