// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.FormationStruct;

/** Instructs a federate application to disaggregate the indicated `AggregateEntity`. */
public class Disaggregate extends SMC_EntityControl {

  /** The formation of the disaggregated units. */
  FormationStruct Formation;

  public FormationStruct getFormation() {
    return this.Formation;
  }

  public void setFormation(FormationStruct Formation) {
    this.Formation = Formation;
  }
}
