// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.EstablishCheckpointTaskStruct;

/** Requests a simulated entity to establish a checkpoint. */
public class EstablishCheckpoint extends Task {

  /** Required: Task parameters. */
  EstablishCheckpointTaskStruct TaskParameters;

  public EstablishCheckpointTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(EstablishCheckpointTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
