// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;
import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;
import nl.tno.oorti.test.netn4.datatypes.TaskStatusEnum32;

/**
 * A management task report regarding the status of a specific task assigned to an entity. The
 * inherited parameter `Time is required.`
 */
public class ETR_TaskStatus extends HLAinteractionRoot {

  /** Required. Reference to the task associated with the report. */
  UUID Task;

  /** Required. The status of the task. */
  TaskStatusEnum32 TaskStatus;

  public UUID getTask() {
    return this.Task;
  }

  public void setTask(UUID Task) {
    this.Task = Task;
  }

  public TaskStatusEnum32 getTaskStatus() {
    return this.TaskStatus;
  }

  public void setTaskStatus(TaskStatusEnum32 TaskStatus) {
    this.TaskStatus = TaskStatus;
  }
}
