// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;
import nl.tno.oorti.test.netn4.datatypes.EntityIdentifierStruct;
import nl.tno.oorti.test.netn4.datatypes.EventTypeEnum32;
import nl.tno.oorti.test.netn4.datatypes.FixedDatumStruct;
import nl.tno.oorti.test.netn4.datatypes.VariableDatumStruct;

/**
 * A Simulation Management (SIMAN) interaction designed to allow a federate to alert a Simulation
 * Manager federate that a particular event has occurred.
 */
public class EventReport extends HLAinteractionRoot {

  /** The DIS entity ID of the entity or application sending the interaction. */
  EntityIdentifierStruct OriginatingEntity;

  /**
   * The DIS entity ID of the entity or application which is the intended recipient(s) of the
   * interaction.
   */
  EntityIdentifierStruct ReceivingEntity;

  /** The type of event being reported. */
  EventTypeEnum32 EventType;

  /** The set of fixed size data items (types and values) associated with this event. */
  FixedDatumStruct[] FixedDatums;

  /** The set of variable size data items (types and values) associated with this event. */
  VariableDatumStruct[] VariableDatumSet;

  public EntityIdentifierStruct getOriginatingEntity() {
    return this.OriginatingEntity;
  }

  public void setOriginatingEntity(EntityIdentifierStruct OriginatingEntity) {
    this.OriginatingEntity = OriginatingEntity;
  }

  public EntityIdentifierStruct getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(EntityIdentifierStruct ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public EventTypeEnum32 getEventType() {
    return this.EventType;
  }

  public void setEventType(EventTypeEnum32 EventType) {
    this.EventType = EventType;
  }

  public FixedDatumStruct[] getFixedDatums() {
    return this.FixedDatums;
  }

  public void setFixedDatums(FixedDatumStruct[] FixedDatums) {
    this.FixedDatums = FixedDatums;
  }

  public VariableDatumStruct[] getVariableDatumSet() {
    return this.VariableDatumSet;
  }

  public void setVariableDatumSet(VariableDatumStruct[] VariableDatumSet) {
    this.VariableDatumSet = VariableDatumSet;
  }
}
