// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.FollowEntityTaskStruct;

/**
 * Tasking of an entity to follow another entity at a specified distance. If attached, the entity is
 * detached immediately just before the move task starts.
 */
public class FollowEntity extends Task {

  /** Required: Task parameters. */
  FollowEntityTaskStruct TaskParameters;

  public FollowEntityTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(FollowEntityTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
