// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.IndirectFireTaskStruct;

/** Tasking an entity to fire directed at an area. */
public class IndirectFire extends Task {

  /** Required: Task parameters */
  IndirectFireTaskStruct TaskParameters;

  public IndirectFireTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(IndirectFireTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
