// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.LayMinefieldTaskStruct;

/** Requests a simulated entity to lay a minefield within a specified area and amount of mines. */
public class LayMinefield extends Task {

  /** Required: Task parameters. */
  LayMinefieldTaskStruct TaskParameters;

  public LayMinefieldTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(LayMinefieldTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
