// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.MagicMoveTaskStruct;

/**
 * Instructs the simulation entity to immediately change location to the specified position and
 * heading. If attached, the entity is detached immediately just before the move task starts.
 */
public class MagicMove extends Task {

  /** Required: Task parameters. */
  MagicMoveTaskStruct TaskParameters;

  public MagicMoveTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(MagicMoveTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
