// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.GeoReferenceVariant;

/**
 * A request to a specified METOC Service to provide METOC data for a specific geographical
 * reference. The request can result in either a response interaction including the requested data
 * or registration of an EnvironmentCondition object for continuous updates.
 */
public class METOC_Request extends SMC_FederateControl {

  /**
   * Optional. Geographical reference. If not provided, the request is for a global environmental
   * condition.
   */
  GeoReferenceVariant GeoReference;

  /**
   * Optional. Indicates if the service is requested to represent the environmental condition as an
   * EnvironmentCondition object instance. The default is False.
   */
  Boolean UpdateAsObject;

  public GeoReferenceVariant getGeoReference() {
    return this.GeoReference;
  }

  public void setGeoReference(GeoReferenceVariant GeoReference) {
    this.GeoReference = GeoReference;
  }

  public Boolean getUpdateAsObject() {
    return this.UpdateAsObject;
  }

  public void setUpdateAsObject(Boolean UpdateAsObject) {
    this.UpdateAsObject = UpdateAsObject;
  }
}
