// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;
import nl.tno.oorti.test.netn4.datatypes.GeoReferenceVariant;

/** A response to a request for METOC data. */
public class METOC_Response extends SMC_Response {

  /** GeoReferenceVariant|Optional. Geographical reference. The default is global. */
  GeoReferenceVariant GeoReference;

  /**
   * Optional. Reference to an existing environment condition if the corresponding request includes
   * UpdateAsObject set to true.
   */
  UUID EnvironmentObject;

  public GeoReferenceVariant getGeoReference() {
    return this.GeoReference;
  }

  public void setGeoReference(GeoReferenceVariant GeoReference) {
    this.GeoReference = GeoReference;
  }

  public UUID getEnvironmentObject() {
    return this.EnvironmentObject;
  }

  public void setEnvironmentObject(UUID EnvironmentObject) {
    this.EnvironmentObject = EnvironmentObject;
  }
}
