// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;
import nl.tno.oorti.test.netn4.datatypes.EntityTypeStruct;
import nl.tno.oorti.test.netn4.datatypes.MinefieldSensorTypeEnum32;
import nl.tno.oorti.test.netn4.datatypes.PerimeterPointStruct;
import nl.tno.oorti.test.netn4.datatypes.RPRboolean;

/**
 * Provides the means by which a federate shall query a minefield simulation for information on the
 * individual mines within the minefield operating in QRP mode.
 */
public class MinefieldQuery extends HLAinteractionRoot {

  /** Identifies the minefield to which this query is addressed */
  String MinefieldIdentifier;

  /**
   * Specifies the location of each perimeter point in the requested area relative to the minefield
   * location
   */
  PerimeterPointStruct[] PerimeterPoints;

  /** Specifies whether or not fusing is requested */
  RPRboolean QueryFusing;

  /** Specifies whether or not orientation is requested */
  RPRboolean QueryMineOrientation;

  /** Specifies whether or not ground burial depth offset is requested */
  RPRboolean QueryGroundBurialDepthOffset;

  /** Specifies whether or not emplacement age is requested */
  RPRboolean QueryMineEmplacementAge;

  /** Specifies whether or not paint scheme is requested */
  RPRboolean QueryPaintScheme;

  /** Specifies whether or not reflectance is requested */
  RPRboolean QueryReflectance;

  /** Specifies whether or not scalar detection coefficient is requested */
  RPRboolean QueryScalarDetectionCoefficient;

  /** Specifies whether or not snow burial depth offset is requested */
  RPRboolean QuerySnowBurialDepthOffset;

  /** Specifies whether or not thermal contrast is requested */
  RPRboolean QueryThermalContrast;

  /** Specifies whether or not trip detonation wire is requested */
  RPRboolean QueryTripDetonationWire;

  /** Specifies whether or not water burial depth offset is requested */
  RPRboolean QueryWaterBurialDepthOffset;

  /** Identifies the entity that requests the information from the minefield simulation */
  String RequestingEntityIdentifier;

  /** Identifies the minefield query request */
  Byte RequestIdentifier;

  /** Identifies the type of mine being queried by the requesting federate */
  EntityTypeStruct RequestedMineType;

  /** Specifies the types of sensors requesting the data */
  MinefieldSensorTypeEnum32[] SensorTypes;

  public String getMinefieldIdentifier() {
    return this.MinefieldIdentifier;
  }

  public void setMinefieldIdentifier(String MinefieldIdentifier) {
    this.MinefieldIdentifier = MinefieldIdentifier;
  }

  public PerimeterPointStruct[] getPerimeterPoints() {
    return this.PerimeterPoints;
  }

  public void setPerimeterPoints(PerimeterPointStruct[] PerimeterPoints) {
    this.PerimeterPoints = PerimeterPoints;
  }

  public RPRboolean getQueryFusing() {
    return this.QueryFusing;
  }

  public void setQueryFusing(RPRboolean QueryFusing) {
    this.QueryFusing = QueryFusing;
  }

  public RPRboolean getQueryMineOrientation() {
    return this.QueryMineOrientation;
  }

  public void setQueryMineOrientation(RPRboolean QueryMineOrientation) {
    this.QueryMineOrientation = QueryMineOrientation;
  }

  public RPRboolean getQueryGroundBurialDepthOffset() {
    return this.QueryGroundBurialDepthOffset;
  }

  public void setQueryGroundBurialDepthOffset(RPRboolean QueryGroundBurialDepthOffset) {
    this.QueryGroundBurialDepthOffset = QueryGroundBurialDepthOffset;
  }

  public RPRboolean getQueryMineEmplacementAge() {
    return this.QueryMineEmplacementAge;
  }

  public void setQueryMineEmplacementAge(RPRboolean QueryMineEmplacementAge) {
    this.QueryMineEmplacementAge = QueryMineEmplacementAge;
  }

  public RPRboolean getQueryPaintScheme() {
    return this.QueryPaintScheme;
  }

  public void setQueryPaintScheme(RPRboolean QueryPaintScheme) {
    this.QueryPaintScheme = QueryPaintScheme;
  }

  public RPRboolean getQueryReflectance() {
    return this.QueryReflectance;
  }

  public void setQueryReflectance(RPRboolean QueryReflectance) {
    this.QueryReflectance = QueryReflectance;
  }

  public RPRboolean getQueryScalarDetectionCoefficient() {
    return this.QueryScalarDetectionCoefficient;
  }

  public void setQueryScalarDetectionCoefficient(RPRboolean QueryScalarDetectionCoefficient) {
    this.QueryScalarDetectionCoefficient = QueryScalarDetectionCoefficient;
  }

  public RPRboolean getQuerySnowBurialDepthOffset() {
    return this.QuerySnowBurialDepthOffset;
  }

  public void setQuerySnowBurialDepthOffset(RPRboolean QuerySnowBurialDepthOffset) {
    this.QuerySnowBurialDepthOffset = QuerySnowBurialDepthOffset;
  }

  public RPRboolean getQueryThermalContrast() {
    return this.QueryThermalContrast;
  }

  public void setQueryThermalContrast(RPRboolean QueryThermalContrast) {
    this.QueryThermalContrast = QueryThermalContrast;
  }

  public RPRboolean getQueryTripDetonationWire() {
    return this.QueryTripDetonationWire;
  }

  public void setQueryTripDetonationWire(RPRboolean QueryTripDetonationWire) {
    this.QueryTripDetonationWire = QueryTripDetonationWire;
  }

  public RPRboolean getQueryWaterBurialDepthOffset() {
    return this.QueryWaterBurialDepthOffset;
  }

  public void setQueryWaterBurialDepthOffset(RPRboolean QueryWaterBurialDepthOffset) {
    this.QueryWaterBurialDepthOffset = QueryWaterBurialDepthOffset;
  }

  public String getRequestingEntityIdentifier() {
    return this.RequestingEntityIdentifier;
  }

  public void setRequestingEntityIdentifier(String RequestingEntityIdentifier) {
    this.RequestingEntityIdentifier = RequestingEntityIdentifier;
  }

  public Byte getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(Byte RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public EntityTypeStruct getRequestedMineType() {
    return this.RequestedMineType;
  }

  public void setRequestedMineType(EntityTypeStruct RequestedMineType) {
    this.RequestedMineType = RequestedMineType;
  }

  public MinefieldSensorTypeEnum32[] getSensorTypes() {
    return this.SensorTypes;
  }

  public void setSensorTypes(MinefieldSensorTypeEnum32[] SensorTypes) {
    this.SensorTypes = SensorTypes;
  }
}
