// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;

/** A response to a MinefieldQuery providing information on individual mines within a minefield. */
public class MinefieldResponseNACK extends HLAinteractionRoot {

  /** Identifies the minefield to which this query is addressed */
  String MinefieldIdentifier;

  /** Specifies the record numbers that were not received in a sequence of minefield records */
  byte[] MissingRecordNumbers;

  /** Identifies the minefield query request */
  Byte RequestIdentifier;

  /** Identifies the entity that requested the information from the minefield simulation */
  String RequestingEntityIdentifier;

  public String getMinefieldIdentifier() {
    return this.MinefieldIdentifier;
  }

  public void setMinefieldIdentifier(String MinefieldIdentifier) {
    this.MinefieldIdentifier = MinefieldIdentifier;
  }

  public byte[] getMissingRecordNumbers() {
    return this.MissingRecordNumbers;
  }

  public void setMissingRecordNumbers(byte[] MissingRecordNumbers) {
    this.MissingRecordNumbers = MissingRecordNumbers;
  }

  public Byte getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(Byte RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public String getRequestingEntityIdentifier() {
    return this.RequestingEntityIdentifier;
  }

  public void setRequestingEntityIdentifier(String RequestingEntityIdentifier) {
    this.RequestingEntityIdentifier = RequestingEntityIdentifier;
  }
}
