// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.MoveIntoFormationTaskStruct;

/**
 * Tasking a simulated entity to move into the given formation on the given location with the given
 * heading. If attached, the entity is detached immediately just before the move task starts.
 */
public class MoveIntoFormation extends Task {

  /** Required: Task parameters. */
  MoveIntoFormationTaskStruct TaskParameters;

  public MoveIntoFormationTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(MoveIntoFormationTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
