// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.OperateCheckpointTaskStruct;

/**
 * Request an entity to operate a checkpoint. The tasked entity should be within the radius of the
 * checkpoint object. If not, a separate move task should be issued first. The tasked entity
 * activates an inactive checkpoint and operates the checkpoint for the specified duration.
 */
public class OperateCheckpoint extends Task {

  /** Required: Task parameters */
  OperateCheckpointTaskStruct TaskParameters;

  public OperateCheckpointTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(OperateCheckpointTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
