// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.PatrolTaskStruct;

/**
 * Requesting a simulated entity to perform a patrol task. The tasked entity moves from its current
 * position to the start of the patrol route and then moves according to the patrol route from its
 * start point in the path through all waypoints. If attached, the entity is detached immediately
 * just before the move task starts.
 */
public class Patrol extends Task {

  /** Required: Task parameters */
  PatrolTaskStruct TaskParameters;

  public PatrolTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(PatrolTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
