// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/** Request for land surface condition data. */
public class RequestLandSurfaceCondition extends METOC_Request {}
