// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.LayerStruct;

/** Request for tropospheric environment condition data. */
public class RequestTroposphereLayerCondition extends METOC_Request {

  /**
   * Optional. A description of a layer for the request of layered conditions troposphere
   * environment condition. Default is the entire volume of air in the identified layer.
   */
  LayerStruct Layer;

  public LayerStruct getLayer() {
    return this.Layer;
  }

  public void setLayer(LayerStruct Layer) {
    this.Layer = Layer;
  }
}
