// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;

/**
 * Requests the federate application modelling the tasked entity to send a `TaskStatusUpdate`
 * interaction for the specified tasks.
 */
public class RequestTaskStatus extends SMC_EntityControl {

  /**
   * Optional. Tasks for which status reports are requested. The default, if not provided or if the
   * list of tasks is empty, the request refers to all tasks for the tasked entity.
   */
  UUID[] Tasks;

  public UUID[] getTasks() {
    return this.Tasks;
  }

  public void setTasks(UUID[] Tasks) {
    this.Tasks = Tasks;
  }
}
