// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.SupplyStatusStruct;

/** Report on a unit's remaining amount of resources. */
public class ResourceStatusReport extends ETR_Report {

  /** Required. The type of resource and remaining quantity. */
  SupplyStatusStruct Resource;

  public SupplyStatusStruct getResource() {
    return this.Resource;
  }

  public void setResource(SupplyStatusStruct Resource) {
    this.Resource = Resource;
  }
}
