// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the RibbonBridgeObject class.
 */
public class RibbonBridgeObjectTransaction extends PointObjectTransaction {

  /** Specifies the number of segments composing the ribbon bridge */
  Integer NumberOfSegments;

  public Integer getNumberOfSegments() {
    return this.NumberOfSegments;
  }

  public void setNumberOfSegments(Integer NumberOfSegments) {
    this.NumberOfSegments = NumberOfSegments;
  }
}
