// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.ResourceStatusStruct;

/**
 * Instruct federate with the primary responsibility of the specified simulated entity to update the
 * model concerning its Equipment. Only applicable to AggregateEntity.
 */
public class SetEquipmentStatus extends SMC_EntityControl {

  /** Required: Status of a specific type of equipment. */
  ResourceStatusStruct EquipmentStatus;

  public ResourceStatusStruct getEquipmentStatus() {
    return this.EquipmentStatus;
  }

  public void setEquipmentStatus(ResourceStatusStruct EquipmentStatus) {
    this.EquipmentStatus = EquipmentStatus;
  }
}
