// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.SetTransmitterStatusTaskStruct;

/** Tasking of an entity to switch on/off all of its transmitters. */
public class SetTransmitterStatus extends Task {

  /** Required: Task parameters. */
  SetTransmitterStatusTaskStruct TaskParameters;

  public SetTransmitterStatusTaskStruct getTaskParameters() {
    return this.TaskParameters;
  }

  public void setTaskParameters(SetTransmitterStatusTaskStruct TaskParameters) {
    this.TaskParameters = TaskParameters;
  }
}
