// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import java.util.UUID;
import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;

/**
 * Control action intended for a federate with primary modelling responsibility for the referenced
 * entity. The inherited NETN-BASE `UniqueId` parameter matches this interaction with a
 * corresponding `SMC_Response`. Before sending this interaction, use the NETN-SMC `BaseEntity`
 * object attribute `SupportedActions` to determine if the referenced entity supports the action.
 */
public class SMC_EntityControl extends HLAinteractionRoot {

  /** Required: Reference to a simulation entity for which the control action is intended. */
  UUID Entity;

  public UUID getEntity() {
    return this.Entity;
  }

  public void setEntity(UUID Entity) {
    this.Entity = Entity;
  }
}
