// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.mim4.interactions.HLAinteractionRoot;

/**
 * Base class for all control actions applicable to all federates in the federation. The inherited
 * NETN-BASE `UniqueId` parameter is used to match this interaction with a corresponding
 * `SMC_Response`.
 */
public class SMC_FederationControl extends HLAinteractionRoot {}
