// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.CurrentStruct;
import nl.tno.oorti.test.netn4.datatypes.SedimentTypeEnum32;

/** Response specifying the subsurface body of water condition data. */
public class SubsurfaceLayerCondition extends METOC_Response {

  /** Optional. The average temperature in the body of water. */
  Float Temperature;

  /** Optional. The average current direction and speed in the body of water. */
  CurrentStruct Current;

  /** Optional. The average salinity in the body of water. */
  Float Salinity;

  /** Optional. The type of sediment on the sea floor. The default is 0 (NoSediment). */
  SedimentTypeEnum32 BottomType;

  public Float getTemperature() {
    return this.Temperature;
  }

  public void setTemperature(Float Temperature) {
    this.Temperature = Temperature;
  }

  public CurrentStruct getCurrent() {
    return this.Current;
  }

  public void setCurrent(CurrentStruct Current) {
    this.Current = Current;
  }

  public Float getSalinity() {
    return this.Salinity;
  }

  public void setSalinity(Float Salinity) {
    this.Salinity = Salinity;
  }

  public SedimentTypeEnum32 getBottomType() {
    return this.BottomType;
  }

  public void setBottomType(SedimentTypeEnum32 BottomType) {
    this.BottomType = BottomType;
  }
}
