// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.CloudStruct;

/** Response specifying the environmental condition in a volume of air. */
public class TroposphereLayerCondition extends WeatherCondition {

  /** Optional. Cloud cover. */
  CloudStruct Cloud;

  public CloudStruct getCloud() {
    return this.Cloud;
  }

  public void setCloud(CloudStruct Cloud) {
    this.Cloud = Cloud;
  }
}
