// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.AttackTypeEnum32;

/** Report from a unit that it is under attack. */
public class UnderAttackStatusReport extends ETR_Report {

  /** Required. The direction to the attacking entity [0,360). Default = 0. True North. */
  Float FromDirection;

  /** Required. Severeness of the attack upon the reporting entity. */
  AttackTypeEnum32 Severeness;

  public Float getFromDirection() {
    return this.FromDirection;
  }

  public void setFromDirection(Float FromDirection) {
    this.FromDirection = FromDirection;
  }

  public AttackTypeEnum32 getSevereness() {
    return this.Severeness;
  }

  public void setSevereness(AttackTypeEnum32 Severeness) {
    this.Severeness = Severeness;
  }
}
