// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.interactions;

import nl.tno.oorti.test.netn4.datatypes.HazeStruct;
import nl.tno.oorti.test.netn4.datatypes.PrecipitationStruct;
import nl.tno.oorti.test.netn4.datatypes.WindStruct;

/** Response with the general weather condition data. */
public class WeatherCondition extends METOC_Response {

  /** Optional. The average temperature in the region/location. */
  Float Temperature;

  /** Optional. The average wind speed and direction in the region/location. */
  WindStruct Wind;

  /** Optional. The average precipitation intensity in the region/location. */
  PrecipitationStruct Precipitation;

  /** Optional. The average haze density in the region/location, */
  HazeStruct Haze;

  /** Optional. The average humidity in the region/location. */
  Float Humidity;

  /**
   * Optional. The average barometric pressure in millibar or hectopascal (1 mbar = 1hPa) in the
   * region/location.
   */
  Float BarometricPressure;

  /**
   * Optional. The average distance at which the human eye in the region/location discerns an object
   * or light.
   */
  Float VisibilityRange;

  public Float getTemperature() {
    return this.Temperature;
  }

  public void setTemperature(Float Temperature) {
    this.Temperature = Temperature;
  }

  public WindStruct getWind() {
    return this.Wind;
  }

  public void setWind(WindStruct Wind) {
    this.Wind = Wind;
  }

  public PrecipitationStruct getPrecipitation() {
    return this.Precipitation;
  }

  public void setPrecipitation(PrecipitationStruct Precipitation) {
    this.Precipitation = Precipitation;
  }

  public HazeStruct getHaze() {
    return this.Haze;
  }

  public void setHaze(HazeStruct Haze) {
    this.Haze = Haze;
  }

  public Float getHumidity() {
    return this.Humidity;
  }

  public void setHumidity(Float Humidity) {
    this.Humidity = Humidity;
  }

  public Float getBarometricPressure() {
    return this.BarometricPressure;
  }

  public void setBarometricPressure(Float BarometricPressure) {
    this.BarometricPressure = BarometricPressure;
  }

  public Float getVisibilityRange() {
    return this.VisibilityRange;
  }

  public void setVisibilityRange(Float VisibilityRange) {
    this.VisibilityRange = VisibilityRange;
  }
}
