// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.datatypes;

/** Count of interactions of a class */
public class HLAinteractionCount {

  /** Encoded interaction class handle */
  byte[] HLAinteractionClass;

  /** Number of interactions */
  int HLAinteractionCount;

  public byte[] getHLAinteractionClass() {
    return this.HLAinteractionClass;
  }

  public void setHLAinteractionClass(byte[] HLAinteractionClass) {
    this.HLAinteractionClass = HLAinteractionClass;
  }

  public int getHLAinteractionCount() {
    return this.HLAinteractionCount;
  }

  public void setHLAinteractionCount(int HLAinteractionCount) {
    this.HLAinteractionCount = HLAinteractionCount;
  }
}
