// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.datatypes;

/** Order type to be used for sending attributes or interactions */
public enum HLAorderType {
  HLAunknown(0),
  Receive(0),
  TimeStamp(1);

  private final int value;

  private final int[] values;

  private HLAorderType(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
