// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.datatypes;

/** NA */
public enum HLAownership {
  HLAunknown(0),
  Unowned(0),
  Owned(1);

  private final int value;

  private final int[] values;

  private HLAownership(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
