// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.datatypes;

/** Joined federate synchronization point status */
public enum HLAsynchPointStatus {
  HLAunknown(0),
  NoActivity(0),
  AttemptingToRegisterSynchPoint(1),
  MovingToSynchPoint(2),
  WaitingForRestOfFederation(3);

  private final int value;

  private final int[] values;

  private HLAsynchPointStatus(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
