// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

import nl.tno.oorti.impl.mim.datatypes.HLAorderType;

/** Change the order type used by the joined federate when sending a class of interaction */
public class HLAchangeInteractionOrderType extends HLAservice {

  /** Interaction class whose order type is changed by this service invocation */
  byte[] HLAinteractionClass;

  /** Order type to be used for sending the interaction class */
  HLAorderType HLAsendOrder;

  public byte[] getHLAinteractionClass() {
    return this.HLAinteractionClass;
  }

  public void setHLAinteractionClass(byte[] HLAinteractionClass) {
    this.HLAinteractionClass = HLAinteractionClass;
  }

  public HLAorderType getHLAsendOrder() {
    return this.HLAsendOrder;
  }

  public void setHLAsendOrder(HLAorderType HLAsendOrder) {
    this.HLAsendOrder = HLAsendOrder;
  }
}
