// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * When the joined federate is time-constrained, cause the RTI to deliver RO messages to the joined
 * federate only when its time manager state is "Time Advancing".
 */
public class HLAdisableAsynchronousDelivery extends HLAservice {}
