// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/** Cause an object instance to be deleted from the federation. */
public class HLAdeleteObjectInstance extends HLAservice {

  /** Handle of the object instance that is to be deleted */
  byte[] HLAobjectInstance;

  /** Tag associated with the deletion */
  byte[] HLAtag;

  /** Time stamp of the deletion (optional) */
  byte[] HLAtimeStamp;

  public byte[] getHLAobjectInstance() {
    return this.HLAobjectInstance;
  }

  public void setHLAobjectInstance(byte[] HLAobjectInstance) {
    this.HLAobjectInstance = HLAobjectInstance;
  }

  public byte[] getHLAtag() {
    return this.HLAtag;
  }

  public void setHLAtag(byte[] HLAtag) {
    this.HLAtag = HLAtag;
  }

  public byte[] getHLAtimeStamp() {
    return this.HLAtimeStamp;
  }

  public void setHLAtimeStamp(byte[] HLAtimeStamp) {
    this.HLAtimeStamp = HLAtimeStamp;
  }
}
