// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Cause the logical time of the joined federate to cease being constrained by the logical times of
 * other joined federates
 */
public class HLAdisableTimeConstrained extends HLAservice {}
