// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/** Permit a federate to request RTI data about a specific federation execution */
public class HLAmanager_HLAfederation_HLArequest extends HLAfederation {}
