// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Report RTI data about a joined federate. The RTI shall send these interactions in response to
 * interactions of class HLAmanager.HLAfederate.HLArequest that correspond to services that are
 * normally invoked by federates.
 */
public class HLAreport extends HLAfederate {}
