// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Request that the RTI send a report interaction that contains the information that a joined
 * federate maintains on a single object instance. It shall result in one interaction of class
 * HLAmanager.HLAfederate.HLAreport.HLAreportObjectInstanceInformation
 */
public class HLArequestObjectInstanceInformation extends HLArequest {

  /** Handle of the object instance for which information is being requested */
  byte[] HLAobjectInstance;

  public byte[] getHLAobjectInstance() {
    return this.HLAobjectInstance;
  }

  public void setHLAobjectInstance(byte[] HLAobjectInstance) {
    this.HLAobjectInstance = HLAobjectInstance;
  }
}
