// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * This MOM interaction shall be sent when a federate has been lost from the federation due to a
 * fault.
 */
public class HLAreportFederateLost extends HLAreport {

  /** Name of the lost joined federate */
  String HLAfederateName;

  /** Last-known-good timestamp to which the lost joined federate was granted */
  byte[] HLAtimeStamp;

  /** Human-readable description of the fault */
  String HLAfaultDescription;

  public String getHLAfederateName() {
    return this.HLAfederateName;
  }

  public void setHLAfederateName(String HLAfederateName) {
    this.HLAfederateName = HLAfederateName;
  }

  public byte[] getHLAtimeStamp() {
    return this.HLAtimeStamp;
  }

  public void setHLAtimeStamp(byte[] HLAtimeStamp) {
    this.HLAtimeStamp = HLAtimeStamp;
  }

  public String getHLAfaultDescription() {
    return this.HLAfaultDescription;
  }

  public void setHLAfaultDescription(String HLAfaultDescription) {
    this.HLAfaultDescription = HLAfaultDescription;
  }
}
