// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Request that the RTI send a report interaction that contains the object instances that can be
 * deleted at a joined federate. It shall result in one interaction of class
 * HLAmanager.HLAfederate.HLAreport.HLAreportObjectInstancesThatCanBeDeleted.
 */
public class HLArequestObjectInstancesThatCanBeDeleted extends HLArequest {}
