// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * The interaction shall be sent by the RTI in response to an interaction of class
 * HLAmanager.HLAfederate.HLArequest.HLArequestSubscriptions. It shall report the attributes of one
 * object class subscribed to by the joined federate. One of these interactions shall be sent for
 * each object class that is subscribed by the joined federate. This information shall reflect
 * related DDM usage. If joined federate has no subscribed object classes, then a single interaction
 * shall be sent as a NULL response with the HLAnumberOfClasses parameter having a value of 0.
 */
public class HLAreportObjectClassSubscription extends HLAreport {

  /**
   * The number of object class and passive indicator combinations for which the joined federate
   * subscribes to attributes. This information shall reflect related DDM usage. This parameter
   * shall be 0 in a NULL response.
   */
  Integer HLAnumberOfClasses;

  /**
   * The object class whose subscription is being reported. This parameter shall be omitted in a
   * NULL response.
   */
  byte[] HLAobjectClass;

  /** Whether the subscription is active. This parameter shall be omitted in a NULL response. */
  Boolean HLAactive;

  /**
   * Name of the maximum subscribed update rate. This parameter shall be omitted in a NULL response.
   */
  String HLAmaxUpdateRate;

  /**
   * List of handles of class attributes to which the joined federate is subscribing. This parameter
   * shall be omitted in a NULL response.
   */
  byte[][] HLAattributeList;

  public Integer getHLAnumberOfClasses() {
    return this.HLAnumberOfClasses;
  }

  public void setHLAnumberOfClasses(Integer HLAnumberOfClasses) {
    this.HLAnumberOfClasses = HLAnumberOfClasses;
  }

  public byte[] getHLAobjectClass() {
    return this.HLAobjectClass;
  }

  public void setHLAobjectClass(byte[] HLAobjectClass) {
    this.HLAobjectClass = HLAobjectClass;
  }

  public Boolean getHLAactive() {
    return this.HLAactive;
  }

  public void setHLAactive(Boolean HLAactive) {
    this.HLAactive = HLAactive;
  }

  public String getHLAmaxUpdateRate() {
    return this.HLAmaxUpdateRate;
  }

  public void setHLAmaxUpdateRate(String HLAmaxUpdateRate) {
    this.HLAmaxUpdateRate = HLAmaxUpdateRate;
  }

  public byte[][] getHLAattributeList() {
    return this.HLAattributeList;
  }

  public void setHLAattributeList(byte[][] HLAattributeList) {
    this.HLAattributeList = HLAattributeList;
  }
}
