// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * This interaction shall be sent by the RTI whenever an HLA service is invoked, either by the
 * indicated joined federate or by the RTI at the indicated joined federate, and Service-Reporting
 * is Enabled for the indicated joined federate. This interaction shall always contain the arguments
 * supplied by the service invoker. If the service invocation was successful, the interaction also
 * shall contain the value returned to the invoker (if the service returns a value); otherwise, the
 * interaction also shall contain an indication of the exception that was raised to the invoker.
 */
public class HLAreportServiceInvocation extends HLAreport {

  /** Textual name of the service */
  String HLAservice;

  /**
   * Whether the service invocation was successful. Exception values are returned along with
   * HLAfalse value
   */
  Boolean HLAsuccessIndicator;

  /** Textual depiction of the arguments supplied in the service invocation */
  String[] HLAsuppliedArguments;

  /**
   * Textual depiction of the argument returned by the service invocation. The list is null if the
   * service does not normally return a value or if HLAsuccessIndicator is HLAfalse. Each returned
   * argument is an element on the list. The number of returned arguments depends upon the service
   * narrative and not any particular API and services may have more than one returned argument.
   */
  String[] HLAreturnedArguments;

  /**
   * Textual depiction of the exception raised by this service invocation (null if
   * HLAsuccessIndicator is HLAtrue)
   */
  String HLAexception;

  /**
   * This is a per-joined federate serial number that shall start at zero and shall increment by 1
   * for each HLAmanager.HLAfederate.HLAreport HLAreportServiceInvocation interaction that
   * represents service invocations to or from the respective joined federate.
   */
  Integer HLAserialNumber;

  public String getHLAservice() {
    return this.HLAservice;
  }

  public void setHLAservice(String HLAservice) {
    this.HLAservice = HLAservice;
  }

  public Boolean getHLAsuccessIndicator() {
    return this.HLAsuccessIndicator;
  }

  public void setHLAsuccessIndicator(Boolean HLAsuccessIndicator) {
    this.HLAsuccessIndicator = HLAsuccessIndicator;
  }

  public String[] getHLAsuppliedArguments() {
    return this.HLAsuppliedArguments;
  }

  public void setHLAsuppliedArguments(String[] HLAsuppliedArguments) {
    this.HLAsuppliedArguments = HLAsuppliedArguments;
  }

  public String[] getHLAreturnedArguments() {
    return this.HLAreturnedArguments;
  }

  public void setHLAreturnedArguments(String[] HLAreturnedArguments) {
    this.HLAreturnedArguments = HLAreturnedArguments;
  }

  public String getHLAexception() {
    return this.HLAexception;
  }

  public void setHLAexception(String HLAexception) {
    this.HLAexception = HLAexception;
  }

  public Integer getHLAserialNumber() {
    return this.HLAserialNumber;
  }

  public void setHLAserialNumber(Integer HLAserialNumber) {
    this.HLAserialNumber = HLAserialNumber;
  }
}
