// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

import nl.tno.oorti.impl.mim.datatypes.HLAresignAction;

/**
 * Cause the joined federate to resign from the federation execution. A joined federate shall be
 * able to send this interaction anytime.
 */
public class HLAresignFederationExecution extends HLAservice {

  /** Action that the RTI is to take in conjunction with the resignation */
  HLAresignAction HLAresignAction;

  public HLAresignAction getHLAresignAction() {
    return this.HLAresignAction;
  }

  public void setHLAresignAction(HLAresignAction HLAresignAction) {
    this.HLAresignAction = HLAresignAction;
  }
}
