// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Specify whether to report service invocations to or from the specified joined federate via
 * HLAmanager.HLAfederate.HLAreport.HLAreportServiceInvocation interactions (enable or disable
 * Service-Reporting). If the specified joined federate is subscribed to the
 * HLAmanager.HLAfederate.HLAreport.HLAreportServiceInvocation interaction, all attempts to enable
 * service reporting for that joined federate by sending an
 * HLAmanager.HLAfederate.HLAadjust.HLAsetServiceReporting interaction with an HLAreportingState
 * parameter value of HLAtrue shall fail and be reported via the normal MOM interaction failure
 * means.
 */
public class HLAsetServiceReporting extends HLAadjust {

  /** Whether the RTI should report service invocations (default = HLAfalse) */
  Boolean HLAreportingState;

  public Boolean getHLAreportingState() {
    return this.HLAreportingState;
  }

  public void setHLAreportingState(Boolean HLAreportingState) {
    this.HLAreportingState = HLAreportingState;
  }
}
