// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/** Mimic the federate's report of achieving a synchronization point. */
public class HLAsynchronizationPointAchieved extends HLAservice {

  /** Label associated with the synchronization point */
  String HLAlabel;

  public String getHLAlabel() {
    return this.HLAlabel;
  }

  public void setHLAlabel(String HLAlabel) {
    this.HLAlabel = HLAlabel;
  }
}
