// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/** Set the joined federate's subscription status to an interaction class. */
public class HLAsubscribeInteractionClass extends HLAservice {

  /** Interaction class to which the federate shall subscribe */
  byte[] HLAinteractionClass;

  /** Whether the subscription is active */
  Boolean HLAactive;

  public byte[] getHLAinteractionClass() {
    return this.HLAinteractionClass;
  }

  public void setHLAinteractionClass(byte[] HLAinteractionClass) {
    this.HLAinteractionClass = HLAinteractionClass;
  }

  public Boolean getHLAactive() {
    return this.HLAactive;
  }

  public void setHLAactive(Boolean HLAactive) {
    this.HLAactive = HLAactive;
  }
}
