// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Adjust the time period between updates of the HLAmanager.HLAfederate object instance for the
 * specified joined federate. If this interaction is never sent, the RTI shall not perform periodic
 * updates
 */
public class HLAsetTiming extends HLAadjust {

  /**
   * Number of seconds between updates of instance attribute values of the HLAfederate object
   * instance (A zero value causes periodic updates to cease). If no interaction of class
   * HLAmanager.HLAfederate.HLAadjust.HLAsetTiming has been sent, then no periodic updates of MOM
   * attribute values shall be generated.
   */
  Integer HLAreportPeriod;

  public Integer getHLAreportPeriod() {
    return this.HLAreportPeriod;
  }

  public void setHLAreportPeriod(Integer HLAreportPeriod) {
    this.HLAreportPeriod = HLAreportPeriod;
  }
}
