// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/**
 * Request an advance of the joined federate's logical time, on behalf of the joined federate, and
 * release zero or more messages for delivery to the joined federate
 */
public class HLAtimeAdvanceRequestAvailable extends HLAservice {

  /** Time stamp requested */
  byte[] HLAtimeStamp;

  public byte[] getHLAtimeStamp() {
    return this.HLAtimeStamp;
  }

  public void setHLAtimeStamp(byte[] HLAtimeStamp) {
    this.HLAtimeStamp = HLAtimeStamp;
  }
}
