// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:23:22

package nl.tno.oorti.impl.mim.interactions;

/** Cause the joined federate no longer to subscribe to an interaction class */
public class HLAunsubscribeInteractionClass extends HLAservice {

  /** Interaction class to which the joined federate will no longer be subscribed */
  byte[] HLAinteractionClass;

  public byte[] getHLAinteractionClass() {
    return this.HLAinteractionClass;
  }

  public void setHLAinteractionClass(byte[] HLAinteractionClass) {
    this.HLAinteractionClass = HLAinteractionClass;
  }
}
