// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.mim4.datatypes;

/** State of the federate */
public enum HLAfederateState {
  HLAunknown(0),
  ActiveFederate(1),
  FederateSaveInProgress(3),
  FederateRestoreInProgress(5);

  private final int value;

  private final int[] values;

  private HLAfederateState(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
