// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.datatypes;

/** A particular joined federate and its synchronization point status */
public class HLAsynchPointFederate {

  /** Encoded joined federate handle */
  byte[] HLAfederate;

  /** Synchronization status of the particular joined federate */
  HLAsynchPointStatus HLAfederateSynchStatus;

  public byte[] getHLAfederate() {
    return this.HLAfederate;
  }

  public void setHLAfederate(byte[] HLAfederate) {
    this.HLAfederate = HLAfederate;
  }

  public HLAsynchPointStatus getHLAfederateSynchStatus() {
    return this.HLAfederateSynchStatus;
  }

  public void setHLAfederateSynchStatus(HLAsynchPointStatus HLAfederateSynchStatus) {
    this.HLAfederateSynchStatus = HLAfederateSynchStatus;
  }
}
