// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.datatypes;

/** State of time advancement */
public enum HLAtimeState {
  HLAunknown(0),
  TimeGranted(0),
  TimeAdvancing(1);

  private final int value;

  private final int[] values;

  private HLAtimeState(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
