// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Acknowledgment flags */
public enum AcknowledgeFlagEnum16 {
  HLAunknown((short) 0),
  CreateEntity((short) 1),
  RemoveEntity((short) 2),
  StartResume((short) 3),
  StopFreeze((short) 4),
  TransferOwnership((short) 5);

  private final short value;

  private final short[] values;

  private AcknowledgeFlagEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
