// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Request status */
public enum ActionResultEnum32 {
  HLAunknown(0),
  Other(0),
  Pending(1),
  Executing(2),
  PartiallyComplete(3),
  Complete(4),
  RequestRejected(5),
  RetransmitRequestNow(6),
  RetransmitRequestLater(7),
  InvalidTimeParameters(8),
  SimulationTimeExceeded(9),
  RequestDone(10),
  TACCSF__LOS__Reply___Type1(100),
  TACCSF__LOS__Reply___Type2(101),
  JoinExerciseRequestRejected(201);

  private final int value;

  private final int[] values;

  private ActionResultEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
