// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Acoustic system name */
public enum ActiveSonarEnum16 {
  HLAunknown((short) 0),
  Other((short) 0),
  AN__BQQ___5((short) 1),
  AN__SSQ___62((short) 2),
  AN__SQS___23((short) 3),
  AN__SQS___26((short) 4),
  AN__SQS___53((short) 5),
  ALFS((short) 6),
  LFA((short) 7),
  AN__AQS___901((short) 8),
  AN__AQS___902((short) 9);

  private final short value;

  private final short[] values;

  private ActiveSonarEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
