// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * A state which indicates the status of an object concerning its participation in the simulation.
 * An object in an inactive state is not simulated and does not interact with other objects.
 */
public enum ActiveStatusEnum8 {
  HLAunknown((byte) 0),
  Other((byte) 0),
  Active((byte) 1),
  Inactive((byte) 2);

  private final byte value;

  private final byte[] values;

  private ActiveStatusEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
