// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Class of Agent for an ATP-45 Hazard Area. */
public enum AgentClassEnum8 {
  HLAunknown((byte) 0),
  Chemical((byte) 0),
  Biological((byte) 1),
  Radiological((byte) 2),
  Nuclear((byte) 3);

  private final byte value;

  private final byte[] values;

  private AgentClassEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
