// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Mass of contaminant inside a vehicle brought in by an embedded unit. */
public class AgentMassStruct {

  /** Mass in kg of contaminant. */
  float ContaminatedMass;

  /** Enumeration representation of the agent. */
  AgentTypeEnum16 Agent;

  public float getContaminatedMass() {
    return this.ContaminatedMass;
  }

  public void setContaminatedMass(float ContaminatedMass) {
    this.ContaminatedMass = ContaminatedMass;
  }

  public AgentTypeEnum16 getAgent() {
    return this.Agent;
  }

  public void setAgent(AgentTypeEnum16 Agent) {
    this.Agent = Agent;
  }
}
