// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Aggregate State-Formation [UID 205] */
public enum AggregateStateFormationEnum32 {
  HLAunknown(0),
  Other(0),
  Assembly(1),
  Vee(2),
  Wedge(3),
  Line(4),
  Column(5);

  private final int value;

  private final int[] values;

  private AggregateStateFormationEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
