// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Detailed modulation types for Amplitude Modulation */
public enum AmplitudeModulationTypeEnum16 {
  HLAunknown((short) 0),
  Other((short) 0),
  AudioFrequencyShiftKeying((short) 1),
  AmplitudeModulation((short) 2),
  ContinuousWaveModulation((short) 3),
  DoubleSideband((short) 4),
  IndependentSideband((short) 5),
  SSB__LowerSideband((short) 6),
  SSB__FullCarrier((short) 7),
  SSB__ReducedCarrier((short) 8),
  SSB__UpperSideband((short) 9),
  VestigialSideband((short) 10);

  private final short value;

  private final short[] values;

  private AmplitudeModulationTypeEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
