// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Specifies the radiation pattern from the antenna, its orientation in space, and the polarization
 * of the radiation.
 */
public class AntennaPatternVariantStruct {

  /** Discriminant */
  AntennaPatternTypeEnum32 AntennaPatternType;

  /**
   * Specifies the direction, pattern, and polarization of radiation from a radio transmitter's
   * antenna, represented with respect to a beam coordinate system.
   */
  BeamAntennaStruct BeamAntenna;

  /**
   * Specifies the direction and radiation pattern from a radio transmitter's antenna, represented
   * with respect to the world coordinate system or entity coordinate system.
   */
  SphericalHarmonicAntennaStruct SphericalHarmonicAntenna;

  public AntennaPatternTypeEnum32 getAntennaPatternType() {
    return this.AntennaPatternType;
  }

  public void setAntennaPatternType(AntennaPatternTypeEnum32 AntennaPatternType) {
    this.AntennaPatternType = AntennaPatternType;
  }

  public BeamAntennaStruct getBeamAntenna() {
    return this.BeamAntenna;
  }

  public void setBeamAntenna(BeamAntennaStruct BeamAntenna) {
    this.BeamAntenna = BeamAntenna;
  }

  public SphericalHarmonicAntennaStruct getSphericalHarmonicAntenna() {
    return this.SphericalHarmonicAntenna;
  }

  public void setSphericalHarmonicAntenna(SphericalHarmonicAntennaStruct SphericalHarmonicAntenna) {
    this.SphericalHarmonicAntenna = SphericalHarmonicAntenna;
  }
}
