// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The radiation pattern from an antenna. */
public enum AntennaPatternTypeEnum32 {
  HLAunknown(0),
  OmniDirectional(0),
  Beam(1),
  SphericalHarmonic(2);

  private final int value;

  private final int[] values;

  private AntennaPatternTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
