// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Articulated part type metric */
public enum ArticulatedTypeMetricEnum32 {
  HLAunknown(0),
  Position(1),
  PositionRate(2),
  Extension(3),
  ExtensionRate(4),
  X(5),
  XRate(6),
  Y(7),
  YRate(8),
  Z(9),
  ZRate(10),
  Azimuth(11),
  AzimuthRate(12),
  Elevation(13),
  ElevationRate(14),
  Rotation(15),
  RotationRate(16);

  private final int value;

  private final int[] values;

  private ArticulatedTypeMetricEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
