// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The kind of attack by the enemy. */
public enum AttackTypeEnum32 {
  HLAunknown(0),
  None(0),
  Artillery(1),
  HeavyArtillery(2),
  Other(3);

  private final int value;

  private final int[] values;

  private AttackTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
