// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Beam function */
public enum BeamFunctionCodeEnum8 {
  HLAunknown((byte) 0),
  Other((byte) 0),
  Search((byte) 1),
  HeightFinder((byte) 2),
  Acquisition((byte) 3),
  Tracking((byte) 4),
  AcquisitionAndTracking((byte) 5),
  CommandGuidance((byte) 6),
  Illumination((byte) 7),
  RangeOnlyRadar((byte) 8),
  MissileBeacon((byte) 9),
  MissileFuze((byte) 10),
  ActiveRadarMissileSeeker((byte) 11),
  Jammer((byte) 12),
  IFF((byte) 13),
  NavigationalOrWeather((byte) 14),
  Meteorological((byte) 15),
  DataTransmission((byte) 16),
  NavigationalDirectionalBeacon((byte) 17),
  Time___SharedSearch((byte) 20),
  Time___SharedAcquisition((byte) 21),
  Time___SharedTrack((byte) 22),
  Time___SharedCommandGuidance((byte) 23),
  Time___SharedIllumination((byte) 24),
  Time___SharedJamming((byte) 25);

  private final byte value;

  private final byte[] values;

  private BeamFunctionCodeEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
