// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Breached appearance */
public enum BreachedStatusEnum8 {
  HLAunknown((byte) 0),
  NoBreaching((byte) 0),
  SlightBreaching((byte) 1),
  ModerateBreaching((byte) 2),
  Cleared((byte) 3);

  private final byte value;

  private final byte[] values;

  private BreachedStatusEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
