// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Dosage exposure value associated with a specific agent. */
public class CBRNExposureStruct {

  /** Dosage value (in kg.s.m-3) which has caused this casualty. Defaults to 0.0. */
  float Exposure;

  /** Enumeration representation of the agent. */
  AgentTypeEnum16 Agent;

  public float getExposure() {
    return this.Exposure;
  }

  public void setExposure(float Exposure) {
    this.Exposure = Exposure;
  }

  public AgentTypeEnum16 getAgent() {
    return this.Agent;
  }

  public void setAgent(AgentTypeEnum16 Agent) {
    this.Agent = Agent;
  }
}
