// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for ChangeSpeedTask task. */
public class ChangeSpeedTaskStruct {

  /** Determines the ordered speed to set for an entity, in m/s. */
  float Speed;

  public float getSpeed() {
    return this.Speed;
  }

  public void setSpeed(float Speed) {
    this.Speed = Speed;
  }
}
