// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for ChangeRulesOfEngagement. */
public class ChangeRulesOfEngagementTaskStruct {

  /** The rules of engagement for an entity. */
  RulesOfEngagementEnum8 RulesOfEngagement;

  public RulesOfEngagementEnum8 getRulesOfEngagement() {
    return this.RulesOfEngagement;
  }

  public void setRulesOfEngagement(RulesOfEngagementEnum8 RulesOfEngagement) {
    this.RulesOfEngagement = RulesOfEngagement;
  }
}
