// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for ChangeAltitude */
public class ChangeAltitudeTaskStruct {

  /**
   * Defines the altitude as relative to mean sea level (MSL). Positive if above MSL and negative if
   * below.
   */
  double Altitude;

  public double getAltitude() {
    return this.Altitude;
  }

  public void setAltitude(double Altitude) {
    this.Altitude = Altitude;
  }
}
