// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The cloud layer type, coverage and density. */
public class CloudStruct {

  /** Type of cloud */
  CloudTypeEnum32 Type;

  /** Cloud coverage as percent. */
  float Coverage;

  /** Average density of clouds. */
  float Density;

  public CloudTypeEnum32 getType() {
    return this.Type;
  }

  public void setType(CloudTypeEnum32 Type) {
    this.Type = Type;
  }

  public float getCoverage() {
    return this.Coverage;
  }

  public void setCoverage(float Coverage) {
    this.Coverage = Coverage;
  }

  public float getDensity() {
    return this.Density;
  }

  public void setDensity(float Density) {
    this.Density = Density;
  }
}
