// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Classification of different types of clouds. */
public enum CloudTypeEnum32 {
  HLAunknown(0),
  NoCloud(1),
  Altocumulus(5),
  Altostratus(6),
  Cirrocumulus(3),
  Cirrostratus(4),
  Cirrus(2),
  Cumulonimbus(12),
  Cumulus(9),
  Nimbostratus(8),
  Stratocumulus(7),
  Stratus(10),
  Unknown(13),
  CumulusCongestus(11),
  InvalidCloudClassification(0);

  private final int value;

  private final int[] values;

  private CloudTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
