// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The type of communication network. */
public enum CommunicationNetworkTypeEnum {
  HLAunknown((byte) 0),
  OTHER((byte) 0),
  COMMAND__NET((byte) 1),
  OPERATIONS__INTELLIGENCE__NET((byte) 2),
  ADMIN__LOGISTICS__NET((byte) 3),
  FIRE__SUPPORT__NET((byte) 4);

  private final byte value;

  private final byte[] values;

  private CommunicationNetworkTypeEnum(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
