// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Life form compliance */
public enum ComplianceStateEnum32 {
  HLAunknown(0),
  Other(0),
  Detained(1),
  Surrender(2),
  UsingFists(3),
  VerbalAbuse1(4),
  VerbalAbuse2(5),
  VerbalAbuse3(6),
  PassiveResistance1(7),
  PassiveResistance2(8),
  PassiveResistance3(9),
  NonLethalWeapon1(10),
  NonLethalWeapon2(11),
  NonLethalWeapon3(12),
  NonLethalWeapon4(13),
  NonLethalWeapon5(14),
  NonLethalWeapon6(15);

  private final int value;

  private final int[] values;

  private ComplianceStateEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
