// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Station name */
public enum ConstituentPartStationNameEnum16 {
  HLAunknown((short) 0),
  Other((short) 0),
  AircraftWingstation((short) 1),
  ShipsForwardGunmountStarboard((short) 2),
  ShipsForwardGunmountPort((short) 3),
  ShipsForwardGunmountCenterline((short) 4),
  ShipsAftGunmountStarboard((short) 5),
  ShipsAftGunmountPort((short) 6),
  ShipsAftGunmountCenterline((short) 7),
  ForwardTorpedoTube((short) 8),
  AftTorpedoTube((short) 9),
  BombBay((short) 10),
  CargoBay((short) 11),
  TruckBed((short) 12),
  TrailerBed((short) 13),
  WellDeck((short) 14),
  OnStationRangeBearing((short) 15),
  OnStationXYZ((short) 16);

  private final short value;

  private final short[] values;

  private ConstituentPartStationNameEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
