// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * The relationship of the constituent part object to its host object. Based on the Relationship
 * record as specified in IEEE 1278.1a-1998 section 5.2.56.
 */
public class ConstituentPartRelationshipStruct {

  /** The nature or purpose for the joining of the constituent part object to the host object. */
  ConstituentPartNatureEnum16 Nature;

  /** The position of the constituent part object with respect to the host object. */
  ConstituentPartPositionEnum16 Position;

  public ConstituentPartNatureEnum16 getNature() {
    return this.Nature;
  }

  public void setNature(ConstituentPartNatureEnum16 Nature) {
    this.Nature = Nature;
  }

  public ConstituentPartPositionEnum16 getPosition() {
    return this.Position;
  }

  public void setPosition(ConstituentPartPositionEnum16 Position) {
    this.Position = Position;
  }
}
