// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Relationship position */
public enum ConstituentPartPositionEnum16 {
  HLAunknown((short) 0),
  Other((short) 0),
  OnTopOf((short) 1),
  Inside((short) 2);

  private final short value;

  private final short[] values;

  private ConstituentPartPositionEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
