// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Countour description. */
public class ContourStruct {

  /** Points of the contour. */
  GeodeticLocation[] Boundary;

  /** Percentage of entities within this contour being affected to the define exposure level. */
  float ProbabilityLevel;

  /** Concentration level of the contour. */
  float ConcentrationLevel;

  public GeodeticLocation[] getBoundary() {
    return this.Boundary;
  }

  public void setBoundary(GeodeticLocation[] Boundary) {
    this.Boundary = Boundary;
  }

  public float getProbabilityLevel() {
    return this.ProbabilityLevel;
  }

  public void setProbabilityLevel(float ProbabilityLevel) {
    this.ProbabilityLevel = ProbabilityLevel;
  }

  public float getConcentrationLevel() {
    return this.ConcentrationLevel;
  }

  public void setConcentrationLevel(float ConcentrationLevel) {
    this.ConcentrationLevel = ConcentrationLevel;
  }
}
