// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task parameters. */
public class CreateObstacleTaskStruct {

  /** Common engineering task parameters. */
  EngineeringTaskStruct EngineeringTask;

  /** Area of the obstacle. */
  LocationStruct[] Area;

  public EngineeringTaskStruct getEngineeringTask() {
    return this.EngineeringTask;
  }

  public void setEngineeringTask(EngineeringTaskStruct EngineeringTask) {
    this.EngineeringTask = EngineeringTask;
  }

  public LocationStruct[] getArea() {
    return this.Area;
  }

  public void setArea(LocationStruct[] Area) {
    this.Area = Area;
  }
}
