// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Identifies the type of cryptographic equipment */
public enum CryptographicSystemTypeEnum16 {
  HLAunknown((short) 0),
  Other((short) 0),
  KY__28((short) 1),
  KY__58((short) 2),
  NarrowSpectrumSecureVoice__NSVE((short) 3),
  WideSpectrumSecureVoice__WSVE((short) 4),
  SINCGARS__ICOM((short) 5),
  KY___75((short) 6),
  KY___100((short) 7),
  KY___57((short) 8),
  KYV___5((short) 9),
  Link11KG___40A___P__NTDS__((short) 10),
  Link11BKG___40A___S((short) 11),
  Link11KG___40AR((short) 12);

  private final short value;

  private final short[] values;

  private CryptographicSystemTypeEnum16(short... values) {
    this.value = values[0];
    this.values = values;
  }

  public short getValue() {
    return value;
  }

  public short[] getValues() {
    return values;
  }
}
