// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The damage status of an object. */
public enum DamageStatusEnhancedEnum32 {
  HLAunknown(0),
  NoDamage(0),
  SlightDamage(1),
  ModerateDamage(2),
  SignificantDamage(3),
  Destroyed(4);

  private final int value;

  private final int[] values;

  private DamageStatusEnhancedEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
