// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Detonation result */
public enum DetonationResultCodeEnum8 {
  HLAunknown((byte) 0),
  Other((byte) 0),
  EntityImpact((byte) 1),
  EntityProximateDetonation((byte) 2),
  GroundImpact((byte) 3),
  GroundProximateDetonation((byte) 4),
  Detonation((byte) 5),
  None((byte) 6),
  HE__hit__Small((byte) 7),
  HE__hit__Medium((byte) 8),
  HE__hit__Large((byte) 9),
  ArmorPiercingHit((byte) 10),
  DirtBlast__Small((byte) 11),
  DirtBlast__Medium((byte) 12),
  DirtBlast__Large((byte) 13),
  WaterBlast__Small((byte) 14),
  WaterBlast__Medium((byte) 15),
  WaterBlast__Large((byte) 16),
  AirHit((byte) 17),
  BuildingHit__Small((byte) 18),
  BuildingHit__Medium((byte) 19),
  BuildingHit__Large((byte) 20),
  MineClearingLineCharge((byte) 21),
  EnvironmentObjectImpact((byte) 22),
  EnvironmentObjectProximateDetonation((byte) 23),
  WaterImpact((byte) 24),
  AirBurst((byte) 25),
  Kill__with__fragment__type__1((byte) 26),
  Kill__with__fragment__type__2((byte) 27),
  Kill__with__fragment__type__3((byte) 28),
  Kill__with__fragment__type__1__after__fly___out__failure((byte) 29),
  Kill__with__fragment__type__2__after__fly___out__failure((byte) 30),
  Miss__due__to__fly___out__failure((byte) 31),
  Miss__due__to__end___game__failure((byte) 32),
  Miss__due__to__fly___out__and__end___game__failure((byte) 33);

  private final byte value;

  private final byte[] values;

  private DetonationResultCodeEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
