// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying length X, Y, Z rates */
public class DimensionRateStruct {

  /** Variation of X axis length */
  float XRate;

  /** Variation of Y axis length */
  float YRate;

  /** Variation of Z axis length */
  float ZRate;

  public float getXRate() {
    return this.XRate;
  }

  public void setXRate(float XRate) {
    this.XRate = XRate;
  }

  public float getYRate() {
    return this.YRate;
  }

  public void setYRate(float YRate) {
    this.YRate = YRate;
  }

  public float getZRate() {
    return this.ZRate;
  }

  public void setZRate(float ZRate) {
    this.ZRate = ZRate;
  }
}
