// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Task-specific data for direct fire. */
public class DirectFireTaskStruct {

  /** Target to fire at. */
  UUID Target;

  /** Duration of the fire (milliseconds). Can be 0 */
  long Duration;

  /** Details regarding the weapon, munition, rounds and rate of fire. */
  RoundStruct Round;

  public UUID getTarget() {
    return this.Target;
  }

  public void setTarget(UUID Target) {
    this.Target = Target;
  }

  public long getDuration() {
    return this.Duration;
  }

  public void setDuration(long Duration) {
    this.Duration = Duration;
  }

  public RoundStruct getRound() {
    return this.Round;
  }

  public void setRound(RoundStruct Round) {
    this.Round = Round;
  }
}
