// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Task specific data for DisruptCommuncation */
public class DisruptCommunicationTaskStruct {

  /** Reference to the affected network. If not provided all networks are affected. */
  UUID Network;

  /** Area affected by disruption. */
  LocationStruct[] Area;

  /** Disruption enabled or disabled. Default is True = Enabled. */
  boolean DisruptionEnabled;

  public UUID getNetwork() {
    return this.Network;
  }

  public void setNetwork(UUID Network) {
    this.Network = Network;
  }

  public LocationStruct[] getArea() {
    return this.Area;
  }

  public void setArea(LocationStruct[] Area) {
    this.Area = Area;
  }

  public boolean getDisruptionEnabled() {
    return this.DisruptionEnabled;
  }

  public void setDisruptionEnabled(boolean DisruptionEnabled) {
    this.DisruptionEnabled = DisruptionEnabled;
  }
}
