// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The echelon level of a unit. */
public enum EchelonEnum32 {
  HLAunknown(0),
  NONE(0),
  TEAM(1),
  CREW(2),
  SQUAD(3),
  SECTION(4),
  PLATOON(5),
  DETACHMENT(6),
  COMPANY(7),
  BATTERY(8),
  TROOP(9),
  BATTALION(10),
  SQUADRON(11),
  REGIMENT(12),
  GROUP(13),
  BRIGADE(14),
  DIVISION(15),
  CORPS(16),
  ARMY(17),
  ARMYGROUP(18),
  FRONT(19),
  REGION(20);

  private final int value;

  private final int[] values;

  private EchelonEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
