// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying Ellipsoid 1 geometry record */
public class Ellipsoid1GeomRecStruct {

  /** Centroid location X, Y, Z */
  WorldLocationStruct CentroidLocation;

  /** Sigma dimensions */
  DimensionStruct SigmaValue;

  /** Orientation, specified by Euler angles */
  OrientationStruct Orientation;

  public WorldLocationStruct getCentroidLocation() {
    return this.CentroidLocation;
  }

  public void setCentroidLocation(WorldLocationStruct CentroidLocation) {
    this.CentroidLocation = CentroidLocation;
  }

  public DimensionStruct getSigmaValue() {
    return this.SigmaValue;
  }

  public void setSigmaValue(DimensionStruct SigmaValue) {
    this.SigmaValue = SigmaValue;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }
}
