// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying Ellipsoid 2 geometry record */
public class Ellipsoid2GeomRecStruct {

  /** Centroid location X, Y, Z */
  WorldLocationStruct CentroidLocation;

  /** Sigma dimensions */
  DimensionStruct SigmaValue;

  /** Variation of sigma dimensions */
  VelocityVectorStruct SigmaRate;

  /** Orientation, specified by Euler angles */
  OrientationStruct Orientation;

  /** Velocity Vx, Vy, Vz */
  VelocityVectorStruct Velocity;

  /** Angular velocity Vx, Vy, Vz */
  AngularVelocityVectorStruct AngularVelocity;

  /** Padding field */
  byte[] Padding;

  public WorldLocationStruct getCentroidLocation() {
    return this.CentroidLocation;
  }

  public void setCentroidLocation(WorldLocationStruct CentroidLocation) {
    this.CentroidLocation = CentroidLocation;
  }

  public DimensionStruct getSigmaValue() {
    return this.SigmaValue;
  }

  public void setSigmaValue(DimensionStruct SigmaValue) {
    this.SigmaValue = SigmaValue;
  }

  public VelocityVectorStruct getSigmaRate() {
    return this.SigmaRate;
  }

  public void setSigmaRate(VelocityVectorStruct SigmaRate) {
    this.SigmaRate = SigmaRate;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }

  public VelocityVectorStruct getVelocity() {
    return this.Velocity;
  }

  public void setVelocity(VelocityVectorStruct Velocity) {
    this.Velocity = Velocity;
  }

  public AngularVelocityVectorStruct getAngularVelocity() {
    return this.AngularVelocity;
  }

  public void setAngularVelocity(AngularVelocityVectorStruct AngularVelocity) {
    this.AngularVelocity = AngularVelocity;
  }

  public byte[] getPadding() {
    return this.Padding;
  }

  public void setPadding(byte[] Padding) {
    this.Padding = Padding;
  }
}
