// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Unique, exercise-wide identification of the entity, or a symbolic group address referencing
 * multiple entities or a simulation application. Based on the Entity Identifier record as specified
 * in IEEE 1278.1-1995 section 5.2.14.
 */
public class EntityIdentifierStruct {

  /** Simulation application (federate) identifier. */
  FederateIdentifierStruct FederateIdentifier;

  /**
   * Each entity in a given simulation application shall be given an entity identifier number unique
   * to all other entities in that application. This identifier number is valid for the duration of
   * the exercise; however, entity identifier numbers may be reused when all possible numbers have
   * been exhausted. No entity shall have an entity identifier number of NO_ENTITY (0), ALL_ENTITIES
   * (0xFFFF), or RQST_ASSIGN_ID (0xFFFE). The entity identifier number need not be registered or
   * retained for future exercises. An entity identifier number equal to zero with valid site and
   * application identification shall address a simulation application. An entity identifier number
   * equal to ALL_ENTITIES shall mean all entities within the specified site and application. An
   * entity identifier number equal to RQST_ASSIGN_ID allows the receiver of the CreateEntity
   * interaction to define the entity identifier number of the new entity. The new entity will
   * specify its entity identifier number in the Acknowledge interaction.
   */
  short EntityNumber;

  public FederateIdentifierStruct getFederateIdentifier() {
    return this.FederateIdentifier;
  }

  public void setFederateIdentifier(FederateIdentifierStruct FederateIdentifier) {
    this.FederateIdentifier = FederateIdentifier;
  }

  public short getEntityNumber() {
    return this.EntityNumber;
  }

  public void setEntityNumber(short EntityNumber) {
    this.EntityNumber = EntityNumber;
  }
}
