// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Type of weather model used by a METOC service. */
public enum EnvironmentConditionModelTypeEnum32 {
  HLAunknown(0),
  None(0),
  Simulated(1),
  Real__Historical(2),
  Live(3),
  Standard__Model(4);

  private final int value;

  private final int[] values;

  private EnvironmentConditionModelTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
