// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Text amplifiers for Equipment symbols. */
public class EquipmentSymbolAmplificationStruct {

  /**
   * A text amplifier in an equipment symbol that identifies the number of items present. Max length
   * 9 characters.
   */
  String Quantity;

  /** A text amplifier for units, equipment and installations. Max length 20 characters. */
  String StaffComments;

  /** A text amplifier for units, equipment and installations. Max length 20 characters. */
  String AdditionalInformation;

  /**
   * A text amplifier for units, equipment and installations with a one-letter reliability rating
   * and a one-number credibility rating. Max length 2 characters.
   *
   * <p>Reliability Ratings: A-completely reliable B-usually reliable C-fairly reliable D-not
   * usually reliable E-unreliable F-reliability cannot be judged
   *
   * <p>Credibility Ratings: 1-confirmed by other sources 2-probably true 3-possibly true
   * 4-doubtfully true 5-improbable 6-truth cannot be judged.
   */
  String EvaluationRating;

  /**
   * A text amplifier for hostile equipment; “!” indicates detectable electronic signatures. Max
   * length 1 character.
   */
  String SignatureEquipment;

  /**
   * A text amplifier for equipment; letters "ENY" denote hostile symbols. Max length 3 characters.
   */
  String Hostile;

  /**
   * A text amplifier displaying IFF/SIF/AIS identification modes and codes. Max length 15
   * characters.
   */
  String IFF__SIF__AIS;

  /**
   * A text amplifier for units, equipment and installations that uniquely identifies a particular
   * symbol or track number. Identifies acquisitions number when used with SIGINT symbology. Max
   * length 21 characters.
   */
  String UniqueDesignation;

  /** A text amplifier for equipment that indicates types of equipment. Max length 24 characters. */
  String EquipmentType;

  /**
   * A text amplifier is placed immediately atop the symbol in the engagement bar. May denote 1)
   * local/remote status, 2) engagement status, and 3) weapon type. Max length 8 characters.
   */
  String EngagementBarText;

  public String getQuantity() {
    return this.Quantity;
  }

  public void setQuantity(String Quantity) {
    this.Quantity = Quantity;
  }

  public String getStaffComments() {
    return this.StaffComments;
  }

  public void setStaffComments(String StaffComments) {
    this.StaffComments = StaffComments;
  }

  public String getAdditionalInformation() {
    return this.AdditionalInformation;
  }

  public void setAdditionalInformation(String AdditionalInformation) {
    this.AdditionalInformation = AdditionalInformation;
  }

  public String getEvaluationRating() {
    return this.EvaluationRating;
  }

  public void setEvaluationRating(String EvaluationRating) {
    this.EvaluationRating = EvaluationRating;
  }

  public String getSignatureEquipment() {
    return this.SignatureEquipment;
  }

  public void setSignatureEquipment(String SignatureEquipment) {
    this.SignatureEquipment = SignatureEquipment;
  }

  public String getHostile() {
    return this.Hostile;
  }

  public void setHostile(String Hostile) {
    this.Hostile = Hostile;
  }

  public String getIFF____SIF____AIS() {
    return this.IFF__SIF__AIS;
  }

  public void setIFF____SIF____AIS(String IFF__SIF__AIS) {
    this.IFF__SIF__AIS = IFF__SIF__AIS;
  }

  public String getUniqueDesignation() {
    return this.UniqueDesignation;
  }

  public void setUniqueDesignation(String UniqueDesignation) {
    this.UniqueDesignation = UniqueDesignation;
  }

  public String getEquipmentType() {
    return this.EquipmentType;
  }

  public void setEquipmentType(String EquipmentType) {
    this.EquipmentType = EquipmentType;
  }

  public String getEngagementBarText() {
    return this.EngagementBarText;
  }

  public void setEngagementBarText(String EngagementBarText) {
    this.EngagementBarText = EngagementBarText;
  }
}
