// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task parameters. */
public class EstablishCheckpointTaskStruct {

  /** Common engineering task parameters. */
  EngineeringTaskStruct EngineeringTask;

  /** Location of the checkpoint */
  LocationStruct Location;

  /**
   * Radius on the surface affected by the checkpoint. All movement crossing the area will be
   * subject to check if checkpoint is in operation.
   */
  double Radius;

  /** The delay caused to moving entities when travelling through an operating checkpoint. */
  long DelayTime;

  public EngineeringTaskStruct getEngineeringTask() {
    return this.EngineeringTask;
  }

  public void setEngineeringTask(EngineeringTaskStruct EngineeringTask) {
    this.EngineeringTask = EngineeringTask;
  }

  public LocationStruct getLocation() {
    return this.Location;
  }

  public void setLocation(LocationStruct Location) {
    this.Location = Location;
  }

  public double getRadius() {
    return this.Radius;
  }

  public void setRadius(double Radius) {
    this.Radius = Radius;
  }

  public long getDelayTime() {
    return this.DelayTime;
  }

  public void setDelayTime(long DelayTime) {
    this.DelayTime = DelayTime;
  }
}
