// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data. */
public class EvacuateTaskStruct {

  /** Area to evacuate. */
  GeodeticLocation[] Area;

  /** Type of entities to evacuate. */
  EntityTypeStruct EntityType;

  /** The amount of entities to evacuate. */
  int Amount;

  /** The duration of the evacuation. */
  int Duration;

  public GeodeticLocation[] getArea() {
    return this.Area;
  }

  public void setArea(GeodeticLocation[] Area) {
    this.Area = Area;
  }

  public EntityTypeStruct getEntityType() {
    return this.EntityType;
  }

  public void setEntityType(EntityTypeStruct EntityType) {
    this.EntityType = EntityType;
  }

  public int getAmount() {
    return this.Amount;
  }

  public void setAmount(int Amount) {
    this.Amount = Amount;
  }

  public int getDuration() {
    return this.Duration;
  }

  public void setDuration(int Duration) {
    this.Duration = Duration;
  }
}
