// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Identification of an event. Based on the Event Identifier record as specified in IEEE 1278.1-1995
 * section 5.2.18.
 */
public class EventIdentifierStruct {

  /**
   * The event number. Uniquely assigned by the simulation application (federate) that initiates the
   * sequence of events. It shall be set to one for each exercise and incremented by one for each
   * event. In the case where all possible values are exhausted, the numbers may be reused beginning
   * again at one.
   */
  short EventCount;

  /** Identification of the object issuing the event. */
  String IssuingObjectIdentifier;

  public short getEventCount() {
    return this.EventCount;
  }

  public void setEventCount(short EventCount) {
    this.EventCount = EventCount;
  }

  public String getIssuingObjectIdentifier() {
    return this.IssuingObjectIdentifier;
  }

  public void setIssuingObjectIdentifier(String IssuingObjectIdentifier) {
    this.IssuingObjectIdentifier = IssuingObjectIdentifier;
  }
}
