// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying the characteristics of a linear object smoke segment */
public class ExhaustSmokeStruct {

  /** Specifies the linear object smoke segment characteristics */
  LinearSegmentStruct SegmentParameters;

  /** Specifies the opacity of the linear object smoke segment */
  int PercentOpacity;

  /** Specifies whether the linear object smoke segment is attached to the vehicle */
  RPRboolean Attached;

  /** Specifies the chemical content of the linear object smoke segment */
  ChemicalContentEnum32 ChemicalContent;

  public LinearSegmentStruct getSegmentParameters() {
    return this.SegmentParameters;
  }

  public void setSegmentParameters(LinearSegmentStruct SegmentParameters) {
    this.SegmentParameters = SegmentParameters;
  }

  public int getPercentOpacity() {
    return this.PercentOpacity;
  }

  public void setPercentOpacity(int PercentOpacity) {
    this.PercentOpacity = PercentOpacity;
  }

  public RPRboolean getAttached() {
    return this.Attached;
  }

  public void setAttached(RPRboolean Attached) {
    this.Attached = Attached;
  }

  public ChemicalContentEnum32 getChemicalContent() {
    return this.ChemicalContent;
  }

  public void setChemicalContent(ChemicalContentEnum32 ChemicalContent) {
    this.ChemicalContent = ChemicalContent;
  }
}
