// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Task-specific data. */
public class ExtinguishWildfireTaskStruct {

  /** Reference to wildfire entity. */
  UUID Wildfire;

  /** The duration of the extinguish activity. */
  int Duration;

  public UUID getWildfire() {
    return this.Wildfire;
  }

  public void setWildfire(UUID Wildfire) {
    this.Wildfire = Wildfire;
  }

  public int getDuration() {
    return this.Duration;
  }

  public void setDuration(int Duration) {
    this.Duration = Duration;
  }
}
