// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Enumeration of Federate Control Actions. The datatype is expected to be extended in specific
 * modules defining additional actions.
 */
public enum FederateControlActionEnum {
  HLAunknown(0),
  TaskDelegation(30),
  RequestWeatherCondition(801),
  RequestLandSurfaceCondition(802),
  RequestTroposphereLayerCondition(803),
  RequestWaterSurfaceCondition(804),
  RequestSubsurfaceLayerCondition(805),
  Other(0),
  TransferModellingResponsibility(10);

  private final int value;

  private final int[] values;

  private FederateControlActionEnum(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
