// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Identifier and value for a fixed datum. */
public class FixedDatumStruct {

  /** The identifier for this fixed datum. */
  DatumIdentifierEnum32 FixedDatumIdentifier;

  /** The value for this fixed datum. */
  int FixedDatumValue;

  public DatumIdentifierEnum32 getFixedDatumIdentifier() {
    return this.FixedDatumIdentifier;
  }

  public void setFixedDatumIdentifier(DatumIdentifierEnum32 FixedDatumIdentifier) {
    this.FixedDatumIdentifier = FixedDatumIdentifier;
  }

  public int getFixedDatumValue() {
    return this.FixedDatumValue;
  }

  public void setFixedDatumValue(int FixedDatumValue) {
    this.FixedDatumValue = FixedDatumValue;
  }
}
