// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying Gaussian Puff geometry record */
public class GaussPuffGeomRecStruct {

  /** Puff location X, Y, Z */
  WorldLocationStruct PuffLocation;

  /** Origination location X, Y, Z */
  WorldLocationStruct OriginationLocation;

  /** Sigma dimensions */
  DimensionStruct SigmaValue;

  /** Variation of sigma dimensions */
  DimensionRateStruct SigmaRate;

  /** Orientation, specified by Euler angles */
  OrientationStruct Orientation;

  /** Velocity Vx, Vy, Vz */
  VelocityVectorStruct Velocity;

  /** Angular velocity Vx, Vy, Vz */
  AngularVelocityVectorStruct AngularVelocity;

  /** Centroid height */
  float CentroidHeight;

  public WorldLocationStruct getPuffLocation() {
    return this.PuffLocation;
  }

  public void setPuffLocation(WorldLocationStruct PuffLocation) {
    this.PuffLocation = PuffLocation;
  }

  public WorldLocationStruct getOriginationLocation() {
    return this.OriginationLocation;
  }

  public void setOriginationLocation(WorldLocationStruct OriginationLocation) {
    this.OriginationLocation = OriginationLocation;
  }

  public DimensionStruct getSigmaValue() {
    return this.SigmaValue;
  }

  public void setSigmaValue(DimensionStruct SigmaValue) {
    this.SigmaValue = SigmaValue;
  }

  public DimensionRateStruct getSigmaRate() {
    return this.SigmaRate;
  }

  public void setSigmaRate(DimensionRateStruct SigmaRate) {
    this.SigmaRate = SigmaRate;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }

  public VelocityVectorStruct getVelocity() {
    return this.Velocity;
  }

  public void setVelocity(VelocityVectorStruct Velocity) {
    this.Velocity = Velocity;
  }

  public AngularVelocityVectorStruct getAngularVelocity() {
    return this.AngularVelocity;
  }

  public void setAngularVelocity(AngularVelocityVectorStruct AngularVelocity) {
    this.AngularVelocity = AngularVelocity;
  }

  public float getCentroidHeight() {
    return this.CentroidHeight;
  }

  public void setCentroidHeight(float CentroidHeight) {
    this.CentroidHeight = CentroidHeight;
  }
}
