// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** A geodetic point, specified by latitude and longitude, with unspecified altitude. WGS84 */
public class GeodeticLocation {

  /** The latitude in degrees. */
  double Latitude;

  /** The longitude in degrees. */
  double Longitude;

  public double getLatitude() {
    return this.Latitude;
  }

  public void setLatitude(double Latitude) {
    this.Latitude = Latitude;
  }

  public double getLongitude() {
    return this.Longitude;
  }

  public void setLongitude(double Longitude) {
    this.Longitude = Longitude;
  }
}
