// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * A geodetic point and radius specifying a circle on the earth's surface (WGS84) where the radius
 * is a great circle distance on the surface.
 */
public class GeodeticCircle {

  /** The center of the circular area. Lat, Long on WGS84. */
  GeodeticLocation CenterPoint;

  /** The radius of the circular area. */
  float Radius;

  public GeodeticLocation getCenterPoint() {
    return this.CenterPoint;
  }

  public void setCenterPoint(GeodeticLocation CenterPoint) {
    this.CenterPoint = CenterPoint;
  }

  public float getRadius() {
    return this.Radius;
  }

  public void setRadius(float Radius) {
    this.Radius = Radius;
  }
}
