// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying grid data representation */
public class GridDataStruct {

  /** Specifies the environmental data sample */
  EnvironmentDataSampleTypeEnum16 SampleType;

  /** Specifies grid data representation alternatives */
  GridDataRepresentationVariantStruct DataRepresentation___A___Alternatives;

  public EnvironmentDataSampleTypeEnum16 getSampleType() {
    return this.SampleType;
  }

  public void setSampleType(EnvironmentDataSampleTypeEnum16 SampleType) {
    this.SampleType = SampleType;
  }

  public GridDataRepresentationVariantStruct getDataRepresentation___A___Alternatives() {
    return this.DataRepresentation___A___Alternatives;
  }

  public void setDataRepresentation___A___Alternatives(
      GridDataRepresentationVariantStruct DataRepresentation___A___Alternatives) {
    this.DataRepresentation___A___Alternatives = DataRepresentation___A___Alternatives;
  }
}
