// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying type 2 data representation */
public class GridValueType2Struct {

  /** Specifies the number of environmental state variable data values */
  float[] NumberOfValues___A___Values;

  public float[] getNumberOfValues___A___Values() {
    return this.NumberOfValues___A___Values;
  }

  public void setNumberOfValues___A___Values(float[] NumberOfValues___A___Values) {
    this.NumberOfValues___A___Values = NumberOfValues___A___Values;
  }
}
