// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying type 0 data representation */
public class GridValueType0Struct {

  /** Specifies the number of bytes */
  byte[] NumberOfBytes___A___Values;

  public byte[] getNumberOfBytes______A______Values() {
    return this.NumberOfBytes___A___Values;
  }

  public void setNumberOfBytes______A______Values(byte[] NumberOfBytes___A___Values) {
    this.NumberOfBytes___A___Values = NumberOfBytes___A___Values;
  }
}
