// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying either regular (fixed spacing) or irregular (variable spacing) axis data */
public class GridAxisTypeVariantStruct {

  /** Discriminant */
  EnvironmentGridAxisTypeEnum8 AxisType;

  /** Specifies irregular (variable spacing) axis data alternative */
  IrregularGridAxisStruct IrregularGridAxis;

  public EnvironmentGridAxisTypeEnum8 getAxisType() {
    return this.AxisType;
  }

  public void setAxisType(EnvironmentGridAxisTypeEnum8 AxisType) {
    this.AxisType = AxisType;
  }

  public IrregularGridAxisStruct getIrregularGridAxis() {
    return this.IrregularGridAxis;
  }

  public void setIrregularGridAxis(IrregularGridAxisStruct IrregularGridAxis) {
    this.IrregularGridAxis = IrregularGridAxis;
  }
}
