// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Specifies the formations for ground units. */
public enum GroundFormationTypeEnum32 {
  HLAunknown(0),
  COLUMN(0),
  STAGGERED__COLUMN(1),
  ECHELON__LEFT(2),
  ECHELON__RIGHT(3),
  LINE(4),
  WEDGE(5),
  VEE(6),
  ASSAULT__VEE(7),
  FSE__COLUMN(8),
  STACK(9),
  NONE(10);

  private final int value;

  private final int[] values;

  private GroundFormationTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
