// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Hatch state */
public enum HatchStateEnum32 {
  HLAunknown(0),
  NotApplicable(0),
  PrimaryHatchIsClosed(1),
  PrimaryHatchIsPopped(2),
  PrimaryHatchIsPoppedAndPersonIsVisibleUnderHatch(3),
  PrimaryHatchIsOpen(4),
  PrimaryHatchIsOpenAndPersonIsVisible(5);

  private final int value;

  private final int[] values;

  private HatchStateEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
