// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Type and density of haze material. */
public class HazeStruct {

  /** Type of Haze. */
  HazeTypeEnum32 Type;

  /** Concentration/Density of haze measured in Kg/m3. */
  float Density;

  public HazeTypeEnum32 getType() {
    return this.Type;
  }

  public void setType(HazeTypeEnum32 Type) {
    this.Type = Type;
  }

  public float getDensity() {
    return this.Density;
  }

  public void setDensity(float Density) {
    this.Density = Density;
  }
}
