// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for IndirectFire task. */
public class IndirectFireTaskStruct {

  /** Area of where to fire. */
  LocationStruct[] Area;

  /** How long to fire for. */
  long Duration;

  /** Details regarding the weapon, munition, rounds and rate of fire. */
  RoundStruct Round;

  public LocationStruct[] getArea() {
    return this.Area;
  }

  public void setArea(LocationStruct[] Area) {
    this.Area = Area;
  }

  public long getDuration() {
    return this.Duration;
  }

  public void setDuration(long Duration) {
    this.Duration = Duration;
  }

  public RoundStruct getRound() {
    return this.Round;
  }

  public void setRound(RoundStruct Round) {
    this.Round = Round;
  }
}
