// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Types of Individual Protective Equipment. */
public enum IPETypeEnum8 {
  HLAunknown((byte) 0),
  None((byte) 0),
  One((byte) 1),
  OneR((byte) 2),
  Two((byte) 3),
  TwoR((byte) 4),
  Three((byte) 5),
  ThreeR((byte) 6),
  Four((byte) 7),
  FourR((byte) 8);

  private final byte value;

  private final byte[] values;

  private IPETypeEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
