// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying irregular (variable spacing) axis data */
public class IrregularGridAxisStruct {

  /**
   * Specifies the value that linearly scales the coordinates of the grid locations for the Xi axis
   */
  double CoordinateScale;

  /**
   * Specifies the constant offset value that shall be applied to the grid locations for the Xi axis
   */
  double CoordinateOffset;

  /**
   * Specifies the coordinate values for the Ni grid locations along the irregular (variable
   * spacing) Xi axis
   */
  short[] NumberOfGridLocations___A___GridLocations;

  public double getCoordinateScale() {
    return this.CoordinateScale;
  }

  public void setCoordinateScale(double CoordinateScale) {
    this.CoordinateScale = CoordinateScale;
  }

  public double getCoordinateOffset() {
    return this.CoordinateOffset;
  }

  public void setCoordinateOffset(double CoordinateOffset) {
    this.CoordinateOffset = CoordinateOffset;
  }

  public short[] getNumberOfGridLocations______A______GridLocations() {
    return this.NumberOfGridLocations___A___GridLocations;
  }

  public void setNumberOfGridLocations______A______GridLocations(
      short[] NumberOfGridLocations___A___GridLocations) {
    this.NumberOfGridLocations___A___GridLocations = NumberOfGridLocations___A___GridLocations;
  }
}
