// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task parameters. */
public class LayMinefieldTaskStruct {

  /** Common engineering task parameters. */
  EngineeringTaskStruct EngineeringTask;

  /** Type of mines used, defined in SISO-REF-010 */
  EntityTypeStruct MineType;

  /** Amount of mines to lay in area. */
  int MineCount;

  /** Area of the minefield. */
  LocationStruct[] Area;

  public EngineeringTaskStruct getEngineeringTask() {
    return this.EngineeringTask;
  }

  public void setEngineeringTask(EngineeringTaskStruct EngineeringTask) {
    this.EngineeringTask = EngineeringTask;
  }

  public EntityTypeStruct getMineType() {
    return this.MineType;
  }

  public void setMineType(EntityTypeStruct MineType) {
    this.MineType = MineType;
  }

  public int getMineCount() {
    return this.MineCount;
  }

  public void setMineCount(int MineCount) {
    this.MineCount = MineCount;
  }

  public LocationStruct[] getArea() {
    return this.Area;
  }

  public void setArea(LocationStruct[] Area) {
    this.Area = Area;
  }
}
