// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * The location of a point in space. Unless specified otherwise for the attribute, parameter, or
 * datatype field using this datatype, the location is in the world coordinate system, as specified
 * in IEEE Std 1278.1-2012 section 1.6.3.
 */
public class LocationStruct {

  /** Distance from the origin along the X axis. */
  double X;

  /** Distance from the origin along the Y axis. */
  double Y;

  /** Distance from the origin along the Z axis. */
  double Z;

  public double getX() {
    return this.X;
  }

  public void setX(double X) {
    this.X = X;
  }

  public double getY() {
    return this.Y;
  }

  public void setY(double Y) {
    this.Y = Y;
  }

  public double getZ() {
    return this.Z;
  }

  public void setZ(double Z) {
    this.Z = Z;
  }
}
