// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Minefield lane status */
public enum MinefieldLaneEnum8 {
  HLAunknown((byte) 0),
  MinefieldHasActiveLane((byte) 0),
  MinefieldHasAnInactiveLane((byte) 1);

  private final byte value;

  private final byte[] values;

  private MinefieldLaneEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
