// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * CrossCountry: move directly to the destination without considering the roads. OnlyRoads: stay on
 * the roads to get to the closest point to the destination that is still on the road;
 * RoadsAndCrossCountry: move to the destination by considering the roads; it is allowed to go off
 * the road.
 */
public enum MoveTypeEnum32 {
  HLAunknown(0),
  CrossCountry(0),
  OnlyRoads(1),
  RoadsAndCrossCountry(2);

  private final int value;

  private final int[] values;

  private MoveTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
