// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for MoveByRoute. */
public class MoveByRouteTaskStruct {

  /** Each waypoint includes the speed of movement to the waypoint. */
  Waypoint[] Route;

  /** Indicates if roads have to be followed or not. */
  MoveTypeEnum32 MoveType;

  public Waypoint[] getRoute() {
    return this.Route;
  }

  public void setRoute(Waypoint[] Route) {
    this.Route = Route;
  }

  public MoveTypeEnum32 getMoveType() {
    return this.MoveType;
  }

  public void setMoveType(MoveTypeEnum32 MoveType) {
    this.MoveType = MoveType;
  }
}
