// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for MoveToLocation task. */
public class MoveToLocationTaskStruct {

  /** Location to move to. */
  LocationStruct Location;

  /** Path to use in order to move to Location. */
  LocationStruct[] Path;

  /** Indicates if roads have to be followed. */
  MoveTypeEnum32 MoveType;

  /** Initial speed of the entity. */
  float Speed;

  public LocationStruct getLocation() {
    return this.Location;
  }

  public void setLocation(LocationStruct Location) {
    this.Location = Location;
  }

  public LocationStruct[] getPath() {
    return this.Path;
  }

  public void setPath(LocationStruct[] Path) {
    this.Path = Path;
  }

  public MoveTypeEnum32 getMoveType() {
    return this.MoveType;
  }

  public void setMoveType(MoveTypeEnum32 MoveType) {
    this.MoveType = MoveType;
  }

  public float getSpeed() {
    return this.Speed;
  }

  public void setSpeed(float Speed) {
    this.Speed = Speed;
  }
}
