// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Empty placeholder for future network device characteristics. */
public class NetworkDeviceEmptyCharactersticsStruct {}
