// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Characteristics of network device transmitter. */
public class NetworkDeviceTransmitterCharacteristicsVariant {

  /** Discriminant */
  PhysicalNetworkTypeEnum Type;

  /** No Network */
  NetworkDeviceEmptyCharactersticsStruct NoNetwork;

  /** Undefined */
  NetworkDeviceEmptyCharactersticsStruct Undefined;

  /** A generic description of transmitter characteristics. */
  NetworkDeviceGenericTransmitterCharacteristicsStruct Generic;

  public PhysicalNetworkTypeEnum getType() {
    return this.Type;
  }

  public void setType(PhysicalNetworkTypeEnum Type) {
    this.Type = Type;
  }

  public NetworkDeviceEmptyCharactersticsStruct getNoNetwork() {
    return this.NoNetwork;
  }

  public void setNoNetwork(NetworkDeviceEmptyCharactersticsStruct NoNetwork) {
    this.NoNetwork = NoNetwork;
  }

  public NetworkDeviceEmptyCharactersticsStruct getUndefined() {
    return this.Undefined;
  }

  public void setUndefined(NetworkDeviceEmptyCharactersticsStruct Undefined) {
    this.Undefined = Undefined;
  }

  public NetworkDeviceGenericTransmitterCharacteristicsStruct getGeneric() {
    return this.Generic;
  }

  public void setGeneric(NetworkDeviceGenericTransmitterCharacteristicsStruct Generic) {
    this.Generic = Generic;
  }
}
