// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Characteristics of a network device receiver. */
public class NetworkDeviceReceiverCharacteristicsVariant {

  /** Discriminant */
  PhysicalNetworkTypeEnum Type;

  /** No network. */
  NetworkDeviceEmptyCharactersticsStruct NoNetwork;

  /** Undefined */
  NetworkDeviceEmptyCharactersticsStruct Undefined;

  /** NA */
  NetworkDeviceEmptyCharactersticsStruct Generic;

  public PhysicalNetworkTypeEnum getType() {
    return this.Type;
  }

  public void setType(PhysicalNetworkTypeEnum Type) {
    this.Type = Type;
  }

  public NetworkDeviceEmptyCharactersticsStruct getNoNetwork() {
    return this.NoNetwork;
  }

  public void setNoNetwork(NetworkDeviceEmptyCharactersticsStruct NoNetwork) {
    this.NoNetwork = NoNetwork;
  }

  public NetworkDeviceEmptyCharactersticsStruct getUndefined() {
    return this.Undefined;
  }

  public void setUndefined(NetworkDeviceEmptyCharactersticsStruct Undefined) {
    this.Undefined = Undefined;
  }

  public NetworkDeviceEmptyCharactersticsStruct getGeneric() {
    return this.Generic;
  }

  public void setGeneric(NetworkDeviceEmptyCharactersticsStruct Generic) {
    this.Generic = Generic;
  }
}
