// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The naming convention applied to the radio system by the manufacturer/controlling agency. */
public enum NomenclatureVersionEnum8 {
  HLAunknown((byte) 0),
  Other((byte) 0),
  JointElectronicsTypeDesignationSystem__JETDS__Non___specificSeries((byte) 1),
  ManufacturerDesignation((byte) 2),
  NationalDesignation((byte) 3),
  JETDSARCSet1((byte) 11),
  JETDSARCSet2((byte) 12),
  JETDSARCSet3((byte) 13),
  JETDSARCSet4((byte) 14),
  JETDSBRCSet1((byte) 15),
  JETDSBRCSet2((byte) 16),
  JETDSBRCSet3((byte) 17),
  JETDSBRCSet4((byte) 18),
  JETDSCRCSet1((byte) 19),
  JETDSCRCSet2((byte) 20),
  JETDSCRCSet3((byte) 21),
  JETDSCRCSet4((byte) 22),
  JETDSDRCSet1((byte) 23),
  JETDSDRCSet2((byte) 24),
  JETDSDRCSet3((byte) 25),
  JETDSDRCSet4((byte) 26),
  JETDSFRCSet1((byte) 27),
  JETDSFRCSet2((byte) 28),
  JETDSFRCSet3((byte) 29),
  JETDSFRCSet4((byte) 30),
  JETDSGRCSet1((byte) 31),
  JETDSGRCSet2((byte) 32),
  JETDSGRCSet3((byte) 33),
  JETDSGRCSet4((byte) 34),
  JETDSKRCSet1((byte) 35),
  JETDSKRCSet2((byte) 36),
  JETDSKRCSet3((byte) 37),
  JETDSKRCSet4((byte) 38),
  JETDSMRCSet1((byte) 39),
  JETDSMRCSet2((byte) 40),
  JETDSMRCSet3((byte) 41),
  JETDSMRCSet4((byte) 42),
  JETDSPRCSet1((byte) 43),
  JETDSPRCSet2((byte) 44),
  JETDSPRCSet3((byte) 45),
  JETDSPRCSet4((byte) 46),
  JETDSSRCSet1((byte) 47),
  JETDSSRCSet2((byte) 48),
  JETDSSRCSet3((byte) 49),
  JETDSSRCSet4((byte) 50),
  JETDSTRCSet1((byte) 51),
  JETDSTRCSet2((byte) 52),
  JETDSTRCSet3((byte) 53),
  JETDSTRCSet4((byte) 54),
  JETDSVRCSet1((byte) 55),
  JETDSVRCSet2((byte) 56),
  JETDSVRCSet3((byte) 57),
  JETDSVRCSet4((byte) 58),
  JETDSWRCSet1((byte) 59),
  JETDSWRCSet2((byte) 60),
  JETDSWRCSet3((byte) 61),
  JETDSWRCSet4((byte) 62),
  JETDSZRCSet1((byte) 63),
  JETDSZRCSet2((byte) 64),
  JETDSZRCSet3((byte) 65),
  JETDSZRCSet4((byte) 66);

  private final byte value;

  private final byte[] values;

  private NomenclatureVersionEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
