// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for Observe task. */
public class ObserveTaskStruct {

  /** Area to observe. */
  LocationStruct[] ObservationArea;

  public LocationStruct[] getObservationArea() {
    return this.ObservationArea;
  }

  public void setObservationArea(LocationStruct[] ObservationArea) {
    this.ObservationArea = ObservationArea;
  }
}
