// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Other - The behaviour is federate application specific (e.g. wait for the next command). Circle -
 * At the end of the route, move to the start point of the patrol route (the federate application
 * determines the route). Reverse - Follow the patrol route in reverse order.
 */
public enum PatrolTypeEnum32 {
  HLAunknown(0),
  Other(0),
  Circle(1),
  Reverse(2);

  private final int value;

  private final int[] values;

  private PatrolTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
