// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task progress data for PatrolRepeating tasks. */
public class PatrolTaskProgress {

  /** Progress of the current path. */
  MoveTaskProgress PathProgress;

  /** Time elapsed for entire task. */
  long ElapsedTime;

  /** Time elapsed in the latest interval. */
  long IntervalElapsedTime;

  public MoveTaskProgress getPathProgress() {
    return this.PathProgress;
  }

  public void setPathProgress(MoveTaskProgress PathProgress) {
    this.PathProgress = PathProgress;
  }

  public long getElapsedTime() {
    return this.ElapsedTime;
  }

  public void setElapsedTime(long ElapsedTime) {
    this.ElapsedTime = ElapsedTime;
  }

  public long getIntervalElapsedTime() {
    return this.IntervalElapsedTime;
  }

  public void setIntervalElapsedTime(long IntervalElapsedTime) {
    this.IntervalElapsedTime = IntervalElapsedTime;
  }
}
