// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Defines the movement during the execution of the patrol. */
public enum PatrolMoveTypeEnum32 {
  HLAunknown(0),
  Other(0),
  Stealth(1),
  Caution(2),
  Open(3);

  private final int value;

  private final int[] values;

  private PatrolMoveTypeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
