// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Task-specific data for a Patrol task. */
public class PatrolTaskStruct {

  /** Specifies the route to patrol. */
  Waypoint[] Path;

  /**
   * Defined how the patrol should be executed. The full movement from start point, through the
   * patrol route and back to the start point is called one cycle.
   */
  PatrolTypeEnum32 PatrolType;

  /** Defines how the entity shall move during the patrol route. */
  PatrolMoveTypeEnum32 MoveType;

  /**
   * The duration of the patrol task. The path will be patrolled minimum 1 time. When time has
   * expired no patrol along the path will start.
   */
  long Duration;

  /**
   * The time between the start of two patrol cycles, i.e. the time to complete a cycle and any
   * waiting time before starting the next cycle.
   */
  long IntervalTime;

  public Waypoint[] getPath() {
    return this.Path;
  }

  public void setPath(Waypoint[] Path) {
    this.Path = Path;
  }

  public PatrolTypeEnum32 getPatrolType() {
    return this.PatrolType;
  }

  public void setPatrolType(PatrolTypeEnum32 PatrolType) {
    this.PatrolType = PatrolType;
  }

  public PatrolMoveTypeEnum32 getMoveType() {
    return this.MoveType;
  }

  public void setMoveType(PatrolMoveTypeEnum32 MoveType) {
    this.MoveType = MoveType;
  }

  public long getDuration() {
    return this.Duration;
  }

  public void setDuration(long Duration) {
    this.Duration = Duration;
  }

  public long getIntervalTime() {
    return this.IntervalTime;
  }

  public void setIntervalTime(long IntervalTime) {
    this.IntervalTime = IntervalTime;
  }
}
