// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Characteristics of physical networks depend on their type. */
public class PhysicalNetworkDescriptionVariant {

  /** Discriminant */
  PhysicalNetworkTypeEnum Type;

  /** (Empty) Characteristics of an undefined physical network. */
  PhysicalUndefinedNetworkStruct Undefined;

  /** Characteristics of a generic physical network. */
  PhysicalGenericNetworkStruct Generic;

  public PhysicalNetworkTypeEnum getType() {
    return this.Type;
  }

  public void setType(PhysicalNetworkTypeEnum Type) {
    this.Type = Type;
  }

  public PhysicalUndefinedNetworkStruct getUndefined() {
    return this.Undefined;
  }

  public void setUndefined(PhysicalUndefinedNetworkStruct Undefined) {
    this.Undefined = Undefined;
  }

  public PhysicalGenericNetworkStruct getGeneric() {
    return this.Generic;
  }

  public void setGeneric(PhysicalGenericNetworkStruct Generic) {
    this.Generic = Generic;
  }
}
