// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Protection effectiveness associated with a specific agent. */
public class ProtectionEffectivenessStruct {

  /** Percentage by which this protection reduces effects. 0-100% */
  float Effectiveness;

  /** Enumeration representation of the agent. */
  AgentTypeEnum16 Agent;

  public float getEffectiveness() {
    return this.Effectiveness;
  }

  public void setEffectiveness(float Effectiveness) {
    this.Effectiveness = Effectiveness;
  }

  public AgentTypeEnum16 getAgent() {
    return this.Agent;
  }

  public void setAgent(AgentTypeEnum16 Agent) {
    this.Agent = Agent;
  }
}
