// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.datatypes;

/** Record data. */
public class RecordStruct {

  /** Number of bits of data. */
  int NumberOfBits;

  /** Data. */
  byte[] NumberOfBytes___A___RecordData;

  public int getNumberOfBits() {
    return this.NumberOfBits;
  }

  public void setNumberOfBits(int NumberOfBits) {
    this.NumberOfBits = NumberOfBits;
  }

  public byte[] getNumberOfBytes___A___RecordData() {
    return this.NumberOfBytes___A___RecordData;
  }

  public void setNumberOfBytes___A___RecordData(byte[] NumberOfBytes___A___RecordData) {
    this.NumberOfBytes___A___RecordData = NumberOfBytes___A___RecordData;
  }
}
