// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying Rectangular Volume 2 geometry record */
public class RectVol2GeomRecStruct {

  /** Corner location X, Y, Z */
  WorldLocationStruct CornerLocation;

  /** Dimensions */
  DimensionStruct Dimensions;

  /** Variation of dimensions */
  DimensionRateStruct DimensionsRate;

  /** Orientation, specified by Euler angles */
  OrientationStruct Orientation;

  /** Velocity Vx, Vy, Vz */
  VelocityVectorStruct Velocity;

  /** Angular velocity Vx, Vy, Vz */
  AngularVelocityVectorStruct AngularVelocity;

  /** Padding field */
  byte[] Padding;

  public WorldLocationStruct getCornerLocation() {
    return this.CornerLocation;
  }

  public void setCornerLocation(WorldLocationStruct CornerLocation) {
    this.CornerLocation = CornerLocation;
  }

  public DimensionStruct getDimensions() {
    return this.Dimensions;
  }

  public void setDimensions(DimensionStruct Dimensions) {
    this.Dimensions = Dimensions;
  }

  public DimensionRateStruct getDimensionsRate() {
    return this.DimensionsRate;
  }

  public void setDimensionsRate(DimensionRateStruct DimensionsRate) {
    this.DimensionsRate = DimensionsRate;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }

  public VelocityVectorStruct getVelocity() {
    return this.Velocity;
  }

  public void setVelocity(VelocityVectorStruct Velocity) {
    this.Velocity = Velocity;
  }

  public AngularVelocityVectorStruct getAngularVelocity() {
    return this.AngularVelocity;
  }

  public void setAngularVelocity(AngularVelocityVectorStruct AngularVelocity) {
    this.AngularVelocity = AngularVelocity;
  }

  public byte[] getPadding() {
    return this.Padding;
  }

  public void setPadding(byte[] Padding) {
    this.Padding = Padding;
  }
}
