// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The color of the refueling station light. */
public enum RefuelingStationLightColorEnum8 {
  HLAunknown((byte) 0),
  Red((byte) 0),
  Amber((byte) 1),
  Green((byte) 2);

  private final byte value;

  private final byte[] values;

  private RefuelingStationLightColorEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
