// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Mean and variance of the distribution of the particles or droplets in a release. */
public class ReleaseDistributionStruct {

  /** Mean size of the released material in meters. */
  float Mean;

  /** Variance of the distribution of released particulates/droplets. */
  float Variance;

  public float getMean() {
    return this.Mean;
  }

  public void setMean(float Mean) {
    this.Mean = Mean;
  }

  public float getVariance() {
    return this.Variance;
  }

  public void setVariance(float Variance) {
    this.Variance = Variance;
  }
}
