// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Characterisation of a requested connection. */
public class RequestedConnection {

  /** Reference to the communication network which the requested connection should belong to. */
  UUID CommunicationNetwork;

  /** The type of connection requested. */
  ConnectionTypeEnum RequestedConnectionType;

  /**
   * Requested Id for the connection. If no Id is requested the value of this field should be all
   * zeros.
   */
  UUID ConnectionId;

  /**
   * List of entities intended as destinations for this requested connection. Leave empty in case of
   * broadcasting or multicasting. If multiple receivers are specified it is assumed that messages
   * will be sent sequentially to all recipients. Leave empty in broadcast / multicast cases.
   */
  UUID[] DestinationEntities;

  /**
   * Reference to the Network Device for the requested connection. If no specific network device is
   * requested the value of this field should be all zeros. Specifies which device of the Node
   * should be used for the connection. The device must be bound to the communication network. If
   * not set a suitable device is selected automaticly.
   */
  UUID NetworkDevice;

  public UUID getCommunicationNetwork() {
    return this.CommunicationNetwork;
  }

  public void setCommunicationNetwork(UUID CommunicationNetwork) {
    this.CommunicationNetwork = CommunicationNetwork;
  }

  public ConnectionTypeEnum getRequestedConnectionType() {
    return this.RequestedConnectionType;
  }

  public void setRequestedConnectionType(ConnectionTypeEnum RequestedConnectionType) {
    this.RequestedConnectionType = RequestedConnectionType;
  }

  public UUID getConnectionId() {
    return this.ConnectionId;
  }

  public void setConnectionId(UUID ConnectionId) {
    this.ConnectionId = ConnectionId;
  }

  public UUID[] getDestinationEntities() {
    return this.DestinationEntities;
  }

  public void setDestinationEntities(UUID[] DestinationEntities) {
    this.DestinationEntities = DestinationEntities;
  }

  public UUID getNetworkDevice() {
    return this.NetworkDevice;
  }

  public void setNetworkDevice(UUID NetworkDevice) {
    this.NetworkDevice = NetworkDevice;
  }
}
