// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The name of a resource and the number of instances of that resource by health status. */
public class ResourceStatusStruct {

  /** The number of healthy or intact resources */
  int NumberHealthyOrIntact;

  /** The number of slightly damaged resources */
  int NumberSlightlyDamaged;

  /** The number of moderately damaged resources */
  int NumberModeratelyDamaged;

  /** The number of significantly damaged resources */
  int NumberSignificantlyDamaged;

  /** The number of destroyed or consumed resources */
  int NumberDestroyed;

  /** The name of the resource */
  String ResourceName;

  /**
   * The type of the resource (as described in the Bit Encoded Values for Use with Protocols for
   * Distributed Interactive Simulation Applications)
   */
  EntityTypeStruct ResourceType;

  public int getNumberHealthyOrIntact() {
    return this.NumberHealthyOrIntact;
  }

  public void setNumberHealthyOrIntact(int NumberHealthyOrIntact) {
    this.NumberHealthyOrIntact = NumberHealthyOrIntact;
  }

  public int getNumberSlightlyDamaged() {
    return this.NumberSlightlyDamaged;
  }

  public void setNumberSlightlyDamaged(int NumberSlightlyDamaged) {
    this.NumberSlightlyDamaged = NumberSlightlyDamaged;
  }

  public int getNumberModeratelyDamaged() {
    return this.NumberModeratelyDamaged;
  }

  public void setNumberModeratelyDamaged(int NumberModeratelyDamaged) {
    this.NumberModeratelyDamaged = NumberModeratelyDamaged;
  }

  public int getNumberSignificantlyDamaged() {
    return this.NumberSignificantlyDamaged;
  }

  public void setNumberSignificantlyDamaged(int NumberSignificantlyDamaged) {
    this.NumberSignificantlyDamaged = NumberSignificantlyDamaged;
  }

  public int getNumberDestroyed() {
    return this.NumberDestroyed;
  }

  public void setNumberDestroyed(int NumberDestroyed) {
    this.NumberDestroyed = NumberDestroyed;
  }

  public String getResourceName() {
    return this.ResourceName;
  }

  public void setResourceName(String ResourceName) {
    this.ResourceName = ResourceName;
  }

  public EntityTypeStruct getResourceType() {
    return this.ResourceType;
  }

  public void setResourceType(EntityTypeStruct ResourceType) {
    this.ResourceType = ResourceType;
  }
}
