// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/**
 * Specifies the major modulation type as well as certain detailed information specific to the type.
 */
public class RFModulationTypeVariantStruct {

  /** Discriminant */
  MajorRFModulationTypeEnum16 MajorModulationType;

  /** Detailed modulation type for the amplitude major modulation type. */
  AmplitudeModulationTypeEnum16 AmplitudeModulationType;

  /** Detailed modulation type for the amplitude and angle major modulation type. */
  AmplitudeAngleModulationTypeEnum16 AmplitudeAngleModulationType;

  /** Detailed modulation type for the angle major modulation type. */
  AngleModulationTypeEnum16 AngleModulationType;

  /** Detailed modulation type for the combination major modulation type. */
  CombinationModulationTypeEnum16 CombinationModulationType;

  /** Detailed modulation type for the pulse major modulation type. */
  PulseModulationTypeEnum16 PulseModulationType;

  /** Detailed modulation type for the unmodulated major modulation type. */
  UnmodulatedTypeEnum16 UnmodulatedType;

  public MajorRFModulationTypeEnum16 getMajorModulationType() {
    return this.MajorModulationType;
  }

  public void setMajorModulationType(MajorRFModulationTypeEnum16 MajorModulationType) {
    this.MajorModulationType = MajorModulationType;
  }

  public AmplitudeModulationTypeEnum16 getAmplitudeModulationType() {
    return this.AmplitudeModulationType;
  }

  public void setAmplitudeModulationType(AmplitudeModulationTypeEnum16 AmplitudeModulationType) {
    this.AmplitudeModulationType = AmplitudeModulationType;
  }

  public AmplitudeAngleModulationTypeEnum16 getAmplitudeAngleModulationType() {
    return this.AmplitudeAngleModulationType;
  }

  public void setAmplitudeAngleModulationType(
      AmplitudeAngleModulationTypeEnum16 AmplitudeAngleModulationType) {
    this.AmplitudeAngleModulationType = AmplitudeAngleModulationType;
  }

  public AngleModulationTypeEnum16 getAngleModulationType() {
    return this.AngleModulationType;
  }

  public void setAngleModulationType(AngleModulationTypeEnum16 AngleModulationType) {
    this.AngleModulationType = AngleModulationType;
  }

  public CombinationModulationTypeEnum16 getCombinationModulationType() {
    return this.CombinationModulationType;
  }

  public void setCombinationModulationType(
      CombinationModulationTypeEnum16 CombinationModulationType) {
    this.CombinationModulationType = CombinationModulationType;
  }

  public PulseModulationTypeEnum16 getPulseModulationType() {
    return this.PulseModulationType;
  }

  public void setPulseModulationType(PulseModulationTypeEnum16 PulseModulationType) {
    this.PulseModulationType = PulseModulationType;
  }

  public UnmodulatedTypeEnum16 getUnmodulatedType() {
    return this.UnmodulatedType;
  }

  public void setUnmodulatedType(UnmodulatedTypeEnum16 UnmodulatedType) {
    this.UnmodulatedType = UnmodulatedType;
  }
}
