// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Details of munition fired. */
public class RoundStruct {

  /** Preferred weapon type. */
  EntityTypeStruct WeaponType;

  /** Preferred muntion type. */
  EntityTypeStruct MunitionType;

  /** Number of rounds to fire. */
  short QuantityFired;

  /** Number of rounds per second. */
  float RateOfFire;

  public EntityTypeStruct getWeaponType() {
    return this.WeaponType;
  }

  public void setWeaponType(EntityTypeStruct WeaponType) {
    this.WeaponType = WeaponType;
  }

  public EntityTypeStruct getMunitionType() {
    return this.MunitionType;
  }

  public void setMunitionType(EntityTypeStruct MunitionType) {
    this.MunitionType = MunitionType;
  }

  public short getQuantityFired() {
    return this.QuantityFired;
  }

  public void setQuantityFired(short QuantityFired) {
    this.QuantityFired = QuantityFired;
  }

  public float getRateOfFire() {
    return this.RateOfFire;
  }

  public void setRateOfFire(float RateOfFire) {
    this.RateOfFire = RateOfFire;
  }
}
