// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Standard Boolean type used for 8-bit compatibility. */
public enum RPRboolean {
  HLAunknown((byte) 0),
  False((byte) 0),
  True((byte) 1);

  private final byte value;

  private final byte[] values;

  private RPRboolean(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
