// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Task-specific data for SendSafetyRelatedMessage task. */
public class SendSafetyRelatedMessageTaskStruct {

  /** The entity that represents the destination. This must be an AIS station. */
  UUID ReceivingEntity;

  /** 1-156 chars of six-bit text. */
  byte Message;

  public UUID getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(UUID ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public byte getMessage() {
    return this.Message;
  }

  public void setMessage(byte Message) {
    this.Message = Message;
  }
}
