// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The emission states of aggregate sensors */
public enum SensorStateEnum32 {
  HLAunknown(0),
  OnButNotEmitting(2),
  Off(1),
  Other(0),
  OnAndEmitting(3);

  private final int value;

  private final int[] values;

  private SensorStateEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
