// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Different types of signatures. */
public enum SignatureTypeEnum8 {
  HLAunknown(0),
  DVOSignature(1),
  I2Signature(2),
  ThermalSignature(3),
  HUMINTSignature(4),
  ElectronicSignature(5);

  private final int value;

  private final int[] values;

  private SignatureTypeEnum8(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
