// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Record specifying Bounding Sphere & Sphere 1 geometry record */
public class Sphere1GeomRecStruct {

  /** Centroid location X, Y, Z */
  WorldLocationStruct CentroidLocation;

  /** Radius */
  float Radius;

  /** Padding field */
  byte[] Padding;

  public WorldLocationStruct getCentroidLocation() {
    return this.CentroidLocation;
  }

  public void setCentroidLocation(WorldLocationStruct CentroidLocation) {
    this.CentroidLocation = CentroidLocation;
  }

  public float getRadius() {
    return this.Radius;
  }

  public void setRadius(float Radius) {
    this.Radius = Radius;
  }

  public byte[] getPadding() {
    return this.Padding;
  }

  public void setPadding(byte[] Padding) {
    this.Padding = Padding;
  }
}
