// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Life form state */
public enum StanceCodeEnum32 {
  HLAunknown(0),
  NotApplicable(0),
  UprightStandingStill(1),
  UprightWalking(2),
  UprightRunning(3),
  Kneeling(4),
  Prone(5),
  Crawling(6),
  Swimming(7),
  Parachuting(8),
  Jumping(9),
  Sitting(10),
  Squatting(11),
  Crouching(12),
  Wading(13),
  Surrender(14),
  Detained(15);

  private final int value;

  private final int[] values;

  private StanceCodeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
