// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Represents a single supply type and the quantity being offered or requested. */
public class SupplyStatusStruct {

  /** The type of supply. */
  EntityTypeStruct SupplyType;

  /**
   * The number of units of the supply type. The unit measure depends on the supply type and shall
   * use the SI units of measurement used for such supplies.
   */
  double Quantity;

  public EntityTypeStruct getSupplyType() {
    return this.SupplyType;
  }

  public void setSupplyType(EntityTypeStruct SupplyType) {
    this.SupplyType = SupplyType;
  }

  public double getQuantity() {
    return this.Quantity;
  }

  public void setQuantity(double Quantity) {
    this.Quantity = Quantity;
  }
}
