// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Different symbol amplification data for different types of symbols. */
public class SymbolAmplificationVariant {

  /** Discriminant */
  SymbolTypeEnum SymbolType;

  /** Symbol amplification for unit symbol. */
  UnitSymbolAmplificationStruct UnitSymbol;

  /** Symbol amplification for equipment symbol. */
  EquipmentSymbolAmplificationStruct EquipmentSymbol;

  /** Symbol amplification for installation symbol. */
  InstallationSymbolAmplificationStruct InstallationSymbol;

  public SymbolTypeEnum getSymbolType() {
    return this.SymbolType;
  }

  public void setSymbolType(SymbolTypeEnum SymbolType) {
    this.SymbolType = SymbolType;
  }

  public UnitSymbolAmplificationStruct getUnitSymbol() {
    return this.UnitSymbol;
  }

  public void setUnitSymbol(UnitSymbolAmplificationStruct UnitSymbol) {
    this.UnitSymbol = UnitSymbol;
  }

  public EquipmentSymbolAmplificationStruct getEquipmentSymbol() {
    return this.EquipmentSymbol;
  }

  public void setEquipmentSymbol(EquipmentSymbolAmplificationStruct EquipmentSymbol) {
    this.EquipmentSymbol = EquipmentSymbol;
  }

  public InstallationSymbolAmplificationStruct getInstallationSymbol() {
    return this.InstallationSymbol;
  }

  public void setInstallationSymbol(InstallationSymbolAmplificationStruct InstallationSymbol) {
    this.InstallationSymbol = InstallationSymbol;
  }
}
