// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

import java.util.UUID;

/** Fixed record to describe the progress of an executing task. */
public class TaskProgress {

  /** Reference to the task this progress belongs to. */
  UUID TaskId;

  /** When was this task last updated. */
  int LastUpdated;

  /** Reference to the federate that is executing this task. */
  UUID ExecutingFederateId;

  /** Estimated time to completion. */
  int ETC;

  /** Variant record with task specific progress data. */
  TaskProgressVariantRecord ProgressData;

  public UUID getTaskId() {
    return this.TaskId;
  }

  public void setTaskId(UUID TaskId) {
    this.TaskId = TaskId;
  }

  public int getLastUpdated() {
    return this.LastUpdated;
  }

  public void setLastUpdated(int LastUpdated) {
    this.LastUpdated = LastUpdated;
  }

  public UUID getExecutingFederateId() {
    return this.ExecutingFederateId;
  }

  public void setExecutingFederateId(UUID ExecutingFederateId) {
    this.ExecutingFederateId = ExecutingFederateId;
  }

  public int getETC() {
    return this.ETC;
  }

  public void setETC(int ETC) {
    this.ETC = ETC;
  }

  public TaskProgressVariantRecord getProgressData() {
    return this.ProgressData;
  }

  public void setProgressData(TaskProgressVariantRecord ProgressData) {
    this.ProgressData = ProgressData;
  }
}
