// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Variant record for task progress data. */
public class TaskProgressVariantRecord {

  /** Discriminant */
  EntityControlActionEnum TaskType;

  /** Keeps track of elapesed time. */
  ElapsedTimeProgress Treatment;

  /** Progress parameters. */
  ElapsedTimeProgress COM__ElapsedTime;

  /** Keeps track of elapesed time. */
  ElapsedTimeProgress DIM__Duration;

  /** Keeps track of elapesed time and amount of evacuated entities. */
  EvacuateProgressStruct DIM__Evacuate;

  /** Keeps track of elapesed time. */
  ElapsedTimeProgress ElapsedTime;

  /** Keeps track of elapesed time and spent munition. */
  FireTaskProgress FireTask;

  /** Keeps track of achieved waypoints. */
  MoveTaskProgress MoveOnPath;

  /** Keeps track of achieved waypoints and elapsed time. */
  PatrolTaskProgress Patrol;

  /** Keeps track of elapsed time. */
  ElapsedTimeProgress LOG__ElapsedTime;

  /** Keeps track of movement task. */
  MoveTaskProgress LOG__Transport;

  /** Keeps track of elapesed time. */
  ElapsedTimeProgress ElapsedEngineeringTime;

  public EntityControlActionEnum getTaskType() {
    return this.TaskType;
  }

  public void setTaskType(EntityControlActionEnum TaskType) {
    this.TaskType = TaskType;
  }

  public ElapsedTimeProgress getTreatment() {
    return this.Treatment;
  }

  public void setTreatment(ElapsedTimeProgress Treatment) {
    this.Treatment = Treatment;
  }

  public ElapsedTimeProgress getCOM____ElapsedTime() {
    return this.COM__ElapsedTime;
  }

  public void setCOM____ElapsedTime(ElapsedTimeProgress COM__ElapsedTime) {
    this.COM__ElapsedTime = COM__ElapsedTime;
  }

  public ElapsedTimeProgress getDIM____Duration() {
    return this.DIM__Duration;
  }

  public void setDIM____Duration(ElapsedTimeProgress DIM__Duration) {
    this.DIM__Duration = DIM__Duration;
  }

  public EvacuateProgressStruct getDIM____Evacuate() {
    return this.DIM__Evacuate;
  }

  public void setDIM____Evacuate(EvacuateProgressStruct DIM__Evacuate) {
    this.DIM__Evacuate = DIM__Evacuate;
  }

  public ElapsedTimeProgress getElapsedTime() {
    return this.ElapsedTime;
  }

  public void setElapsedTime(ElapsedTimeProgress ElapsedTime) {
    this.ElapsedTime = ElapsedTime;
  }

  public FireTaskProgress getFireTask() {
    return this.FireTask;
  }

  public void setFireTask(FireTaskProgress FireTask) {
    this.FireTask = FireTask;
  }

  public MoveTaskProgress getMoveOnPath() {
    return this.MoveOnPath;
  }

  public void setMoveOnPath(MoveTaskProgress MoveOnPath) {
    this.MoveOnPath = MoveOnPath;
  }

  public PatrolTaskProgress getPatrol() {
    return this.Patrol;
  }

  public void setPatrol(PatrolTaskProgress Patrol) {
    this.Patrol = Patrol;
  }

  public ElapsedTimeProgress getLOG____ElapsedTime() {
    return this.LOG__ElapsedTime;
  }

  public void setLOG____ElapsedTime(ElapsedTimeProgress LOG__ElapsedTime) {
    this.LOG__ElapsedTime = LOG__ElapsedTime;
  }

  public MoveTaskProgress getLOG____Transport() {
    return this.LOG__Transport;
  }

  public void setLOG____Transport(MoveTaskProgress LOG__Transport) {
    this.LOG__Transport = LOG__Transport;
  }

  public ElapsedTimeProgress getElapsedEngineeringTime() {
    return this.ElapsedEngineeringTime;
  }

  public void setElapsedEngineeringTime(ElapsedTimeProgress ElapsedEngineeringTime) {
    this.ElapsedEngineeringTime = ElapsedEngineeringTime;
  }
}
