// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Variant record for task definition data. */
public class TaskDefinitionVariantRecord {

  /** Discriminant */
  EntityControlActionEnum TaskType;

  /** Task parameters. */
  SendSafetyRelatedMessageTaskStruct SendSafetyRelatedtMessage;

  /** Task parameters. */
  SendSafetyRelatedBroadcastMessageTaskStruct SendSafetyRelatedBroadcastMessage;

  /** Task parameters. */
  ApplyIPETaskStruct ApplyIPE;

  /** Task parameters. */
  AdministerTreatmentTaskStruct AdministerTreatment;

  /** Task parameters. */
  DisruptCommunicationTaskStruct DisruptCommunication;

  /** Task parameters. */
  SetTransmitterStatusTaskStruct SetTransmitterStatus;

  /** Task parameters. */
  PumpFloodingTaskStruct PumpFlooding;

  /** Task parameters. */
  ExtinguishWildfireTaskStruct ExtinguishWildfire;

  /** Task parameters. */
  EvacuateTaskStruct Evacuate;

  /** Task parameters. */
  CreateFireBreakTaskStruct CreateFireBreak;

  /** Task parameters. */
  CreateLeveeTaskStruct CreateLevee;

  /** No additional parameters. */
  EmptyTaskStruct NoTaskParameters;

  /** Task parameters. */
  DirectFireTaskStruct DirectFire;

  /** Task parameters. */
  IndirectFireTaskStruct IndirectFire;

  /** Task parameters. */
  FollowEntityTaskStruct FollowEntity;

  /** Task parameters. */
  MoveInDirectionTaskStruct MoveInDirection;

  /** Task parameters. */
  MoveIntoFormationTaskStruct MoveIntoFormation;

  /** Task parameters. */
  MoveToLocationTaskStruct MoveToLocation;

  /** Task parameters. */
  AttachTaskStruct Attach;

  /** Task parameters. */
  ObserveTaskStruct Observe;

  /** Task parameters. */
  OperateCheckpointTaskStruct OperateCheckpoint;

  /** Task parameters. */
  PatrolTaskStruct Patrol;

  /** Task parameters. */
  ChangeAltitudeTaskStruct ChangeAltitude;

  /** Task parameters. */
  ChangeSpeedTaskStruct ChangeSpeed;

  /** Task parameters. */
  ChangeHeadingTaskStruct ChangeHeading;

  /** Task parameters. */
  OtherActivityTaskStruct OtherActivity;

  /** Task parameters. */
  OperateObservationPostTaskStruct OperateObservationPost;

  /** Task parameters. */
  ChangeRulesOfEngagementTaskStruct ChangeRulesOfEngagement;

  /** Task parameters. */
  MagicMoveTaskStruct MagicMove;

  /** Task parameters. */
  MoveByRouteTaskStruct MoveByRoute;

  /** Task parameters. */
  ResupplyTaskStruct Resupply;

  /** Task parameters. */
  RepairTaskStruct Repair;

  /** Task parameters. */
  TransportTaskStruct Transport;

  /** Task parameters. */
  ClearEngineeringTaskStruct ClearEngineering;

  /** Task parameters. */
  LayMinefieldTaskStruct LayMinefield;

  /** Task parameters. */
  CreateBreachTaskStruct CreateBreach;

  /** Task parameters. */
  EstablishCheckpointTaskStruct EstablishCheckpoint;

  /** Task parameters. */
  CreateObstacleTaskStruct CreateObstacle;

  /** Task parameters. */
  EstablishObservationPostTaskStruct EstablishObservationPost;

  public EntityControlActionEnum getTaskType() {
    return this.TaskType;
  }

  public void setTaskType(EntityControlActionEnum TaskType) {
    this.TaskType = TaskType;
  }

  public SendSafetyRelatedMessageTaskStruct getSendSafetyRelatedtMessage() {
    return this.SendSafetyRelatedtMessage;
  }

  public void setSendSafetyRelatedtMessage(
      SendSafetyRelatedMessageTaskStruct SendSafetyRelatedtMessage) {
    this.SendSafetyRelatedtMessage = SendSafetyRelatedtMessage;
  }

  public SendSafetyRelatedBroadcastMessageTaskStruct getSendSafetyRelatedBroadcastMessage() {
    return this.SendSafetyRelatedBroadcastMessage;
  }

  public void setSendSafetyRelatedBroadcastMessage(
      SendSafetyRelatedBroadcastMessageTaskStruct SendSafetyRelatedBroadcastMessage) {
    this.SendSafetyRelatedBroadcastMessage = SendSafetyRelatedBroadcastMessage;
  }

  public ApplyIPETaskStruct getApplyIPE() {
    return this.ApplyIPE;
  }

  public void setApplyIPE(ApplyIPETaskStruct ApplyIPE) {
    this.ApplyIPE = ApplyIPE;
  }

  public AdministerTreatmentTaskStruct getAdministerTreatment() {
    return this.AdministerTreatment;
  }

  public void setAdministerTreatment(AdministerTreatmentTaskStruct AdministerTreatment) {
    this.AdministerTreatment = AdministerTreatment;
  }

  public DisruptCommunicationTaskStruct getDisruptCommunication() {
    return this.DisruptCommunication;
  }

  public void setDisruptCommunication(DisruptCommunicationTaskStruct DisruptCommunication) {
    this.DisruptCommunication = DisruptCommunication;
  }

  public SetTransmitterStatusTaskStruct getSetTransmitterStatus() {
    return this.SetTransmitterStatus;
  }

  public void setSetTransmitterStatus(SetTransmitterStatusTaskStruct SetTransmitterStatus) {
    this.SetTransmitterStatus = SetTransmitterStatus;
  }

  public PumpFloodingTaskStruct getPumpFlooding() {
    return this.PumpFlooding;
  }

  public void setPumpFlooding(PumpFloodingTaskStruct PumpFlooding) {
    this.PumpFlooding = PumpFlooding;
  }

  public ExtinguishWildfireTaskStruct getExtinguishWildfire() {
    return this.ExtinguishWildfire;
  }

  public void setExtinguishWildfire(ExtinguishWildfireTaskStruct ExtinguishWildfire) {
    this.ExtinguishWildfire = ExtinguishWildfire;
  }

  public EvacuateTaskStruct getEvacuate() {
    return this.Evacuate;
  }

  public void setEvacuate(EvacuateTaskStruct Evacuate) {
    this.Evacuate = Evacuate;
  }

  public CreateFireBreakTaskStruct getCreateFireBreak() {
    return this.CreateFireBreak;
  }

  public void setCreateFireBreak(CreateFireBreakTaskStruct CreateFireBreak) {
    this.CreateFireBreak = CreateFireBreak;
  }

  public CreateLeveeTaskStruct getCreateLevee() {
    return this.CreateLevee;
  }

  public void setCreateLevee(CreateLeveeTaskStruct CreateLevee) {
    this.CreateLevee = CreateLevee;
  }

  public EmptyTaskStruct getNoTaskParameters() {
    return this.NoTaskParameters;
  }

  public void setNoTaskParameters(EmptyTaskStruct NoTaskParameters) {
    this.NoTaskParameters = NoTaskParameters;
  }

  public DirectFireTaskStruct getDirectFire() {
    return this.DirectFire;
  }

  public void setDirectFire(DirectFireTaskStruct DirectFire) {
    this.DirectFire = DirectFire;
  }

  public IndirectFireTaskStruct getIndirectFire() {
    return this.IndirectFire;
  }

  public void setIndirectFire(IndirectFireTaskStruct IndirectFire) {
    this.IndirectFire = IndirectFire;
  }

  public FollowEntityTaskStruct getFollowEntity() {
    return this.FollowEntity;
  }

  public void setFollowEntity(FollowEntityTaskStruct FollowEntity) {
    this.FollowEntity = FollowEntity;
  }

  public MoveInDirectionTaskStruct getMoveInDirection() {
    return this.MoveInDirection;
  }

  public void setMoveInDirection(MoveInDirectionTaskStruct MoveInDirection) {
    this.MoveInDirection = MoveInDirection;
  }

  public MoveIntoFormationTaskStruct getMoveIntoFormation() {
    return this.MoveIntoFormation;
  }

  public void setMoveIntoFormation(MoveIntoFormationTaskStruct MoveIntoFormation) {
    this.MoveIntoFormation = MoveIntoFormation;
  }

  public MoveToLocationTaskStruct getMoveToLocation() {
    return this.MoveToLocation;
  }

  public void setMoveToLocation(MoveToLocationTaskStruct MoveToLocation) {
    this.MoveToLocation = MoveToLocation;
  }

  public AttachTaskStruct getAttach() {
    return this.Attach;
  }

  public void setAttach(AttachTaskStruct Attach) {
    this.Attach = Attach;
  }

  public ObserveTaskStruct getObserve() {
    return this.Observe;
  }

  public void setObserve(ObserveTaskStruct Observe) {
    this.Observe = Observe;
  }

  public OperateCheckpointTaskStruct getOperateCheckpoint() {
    return this.OperateCheckpoint;
  }

  public void setOperateCheckpoint(OperateCheckpointTaskStruct OperateCheckpoint) {
    this.OperateCheckpoint = OperateCheckpoint;
  }

  public PatrolTaskStruct getPatrol() {
    return this.Patrol;
  }

  public void setPatrol(PatrolTaskStruct Patrol) {
    this.Patrol = Patrol;
  }

  public ChangeAltitudeTaskStruct getChangeAltitude() {
    return this.ChangeAltitude;
  }

  public void setChangeAltitude(ChangeAltitudeTaskStruct ChangeAltitude) {
    this.ChangeAltitude = ChangeAltitude;
  }

  public ChangeSpeedTaskStruct getChangeSpeed() {
    return this.ChangeSpeed;
  }

  public void setChangeSpeed(ChangeSpeedTaskStruct ChangeSpeed) {
    this.ChangeSpeed = ChangeSpeed;
  }

  public ChangeHeadingTaskStruct getChangeHeading() {
    return this.ChangeHeading;
  }

  public void setChangeHeading(ChangeHeadingTaskStruct ChangeHeading) {
    this.ChangeHeading = ChangeHeading;
  }

  public OtherActivityTaskStruct getOtherActivity() {
    return this.OtherActivity;
  }

  public void setOtherActivity(OtherActivityTaskStruct OtherActivity) {
    this.OtherActivity = OtherActivity;
  }

  public OperateObservationPostTaskStruct getOperateObservationPost() {
    return this.OperateObservationPost;
  }

  public void setOperateObservationPost(OperateObservationPostTaskStruct OperateObservationPost) {
    this.OperateObservationPost = OperateObservationPost;
  }

  public ChangeRulesOfEngagementTaskStruct getChangeRulesOfEngagement() {
    return this.ChangeRulesOfEngagement;
  }

  public void setChangeRulesOfEngagement(
      ChangeRulesOfEngagementTaskStruct ChangeRulesOfEngagement) {
    this.ChangeRulesOfEngagement = ChangeRulesOfEngagement;
  }

  public MagicMoveTaskStruct getMagicMove() {
    return this.MagicMove;
  }

  public void setMagicMove(MagicMoveTaskStruct MagicMove) {
    this.MagicMove = MagicMove;
  }

  public MoveByRouteTaskStruct getMoveByRoute() {
    return this.MoveByRoute;
  }

  public void setMoveByRoute(MoveByRouteTaskStruct MoveByRoute) {
    this.MoveByRoute = MoveByRoute;
  }

  public ResupplyTaskStruct getResupply() {
    return this.Resupply;
  }

  public void setResupply(ResupplyTaskStruct Resupply) {
    this.Resupply = Resupply;
  }

  public RepairTaskStruct getRepair() {
    return this.Repair;
  }

  public void setRepair(RepairTaskStruct Repair) {
    this.Repair = Repair;
  }

  public TransportTaskStruct getTransport() {
    return this.Transport;
  }

  public void setTransport(TransportTaskStruct Transport) {
    this.Transport = Transport;
  }

  public ClearEngineeringTaskStruct getClearEngineering() {
    return this.ClearEngineering;
  }

  public void setClearEngineering(ClearEngineeringTaskStruct ClearEngineering) {
    this.ClearEngineering = ClearEngineering;
  }

  public LayMinefieldTaskStruct getLayMinefield() {
    return this.LayMinefield;
  }

  public void setLayMinefield(LayMinefieldTaskStruct LayMinefield) {
    this.LayMinefield = LayMinefield;
  }

  public CreateBreachTaskStruct getCreateBreach() {
    return this.CreateBreach;
  }

  public void setCreateBreach(CreateBreachTaskStruct CreateBreach) {
    this.CreateBreach = CreateBreach;
  }

  public EstablishCheckpointTaskStruct getEstablishCheckpoint() {
    return this.EstablishCheckpoint;
  }

  public void setEstablishCheckpoint(EstablishCheckpointTaskStruct EstablishCheckpoint) {
    this.EstablishCheckpoint = EstablishCheckpoint;
  }

  public CreateObstacleTaskStruct getCreateObstacle() {
    return this.CreateObstacle;
  }

  public void setCreateObstacle(CreateObstacleTaskStruct CreateObstacle) {
    this.CreateObstacle = CreateObstacle;
  }

  public EstablishObservationPostTaskStruct getEstablishObservationPost() {
    return this.EstablishObservationPost;
  }

  public void setEstablishObservationPost(
      EstablishObservationPostTaskStruct EstablishObservationPost) {
    this.EstablishObservationPost = EstablishObservationPost;
  }
}
