// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Size of trailing effect */
public enum TrailingEffectsCodeEnum32 {
  HLAunknown(0),
  NoTrail(0),
  SmallTrail(1),
  MediumTrail(2),
  LargeTrail(3);

  private final int value;

  private final int[] values;

  private TrailingEffectsCodeEnum32(int... values) {
    this.value = values[0];
    this.values = values;
  }

  public int getValue() {
    return value;
  }

  public int[] getValues() {
    return values;
  }
}
