// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** The current operational state of a radio transmitter. */
public enum TransmitterOperationalStatusEnum8 {
  HLAunknown((byte) 0),
  Off((byte) 0),
  OnButNotTransmitting((byte) 1),
  OnAndTransmitting((byte) 2);

  private final byte value;

  private final byte[] values;

  private TransmitterOperationalStatusEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
