// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Transfer type */
public enum TransferTypeEnum8 {
  HLAunknown((byte) 0),
  Other((byte) 0),
  EntityPush((byte) 1),
  EntityPull((byte) 2),
  EntitySwap((byte) 3),
  EnvironmentalProcessPush((byte) 4),
  EnvironmentalProcessPull((byte) 5),
  NotUsed((byte) 6),
  CancelTransfer((byte) 7),
  ManualPullTransfer___Entity((byte) 8),
  ManualPullTransfer___EnvironmentalProcess((byte) 9),
  RemoveEntity((byte) 10);

  private final byte value;

  private final byte[] values;

  private TransferTypeEnum8(byte... values) {
    this.value = values[0];
    this.values = values;
  }

  public byte getValue() {
    return value;
  }

  public byte[] getValues() {
    return values;
  }
}
