// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Defines the properties for a CBRN treatment. */
public class TreatmentStruct {

  /** Percentage by which this treatment reduces effects. 0-100% */
  float Effectiveness;

  /** Duration in seconds for which this treatment will remain effective. */
  int Duration;

  /**
   * The time window in seconds between exposure and treatment for which this treatment is
   * effective.
   */
  int TreatmentWindow;

  /** Array of agents that can be treated using this treatment. */
  AgentTypeEnum16[] TreatableAgents;

  public float getEffectiveness() {
    return this.Effectiveness;
  }

  public void setEffectiveness(float Effectiveness) {
    this.Effectiveness = Effectiveness;
  }

  public int getDuration() {
    return this.Duration;
  }

  public void setDuration(int Duration) {
    this.Duration = Duration;
  }

  public int getTreatmentWindow() {
    return this.TreatmentWindow;
  }

  public void setTreatmentWindow(int TreatmentWindow) {
    this.TreatmentWindow = TreatmentWindow;
  }

  public AgentTypeEnum16[] getTreatableAgents() {
    return this.TreatableAgents;
  }

  public void setTreatableAgents(AgentTypeEnum16[] TreatableAgents) {
    this.TreatableAgents = TreatableAgents;
  }
}
