// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Water surface wave conditions and direction. */
public class WaveStruct {

  /** Distance from a particular phase on a wave to the same phase on an adjacent wave. */
  float Length;

  /** Average vertical distance between trough and crest produced by the wave. */
  float Height;

  /**
   * Wave period is the distance between two waves passing through a stationary point, measured in
   * seconds.
   */
  int Period;

  /** The direction in which the wave propagates. */
  float Direction;

  public float getLength() {
    return this.Length;
  }

  public void setLength(float Length) {
    this.Length = Length;
  }

  public float getHeight() {
    return this.Height;
  }

  public void setHeight(float Height) {
    this.Height = Height;
  }

  public int getPeriod() {
    return this.Period;
  }

  public void setPeriod(int Period) {
    this.Period = Period;
  }

  public float getDirection() {
    return this.Direction;
  }

  public void setDirection(float Direction) {
    this.Direction = Direction;
  }
}
