// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.datatypes;

/** Wind direction and speeds. */
public class WindStruct {

  /** Required: Direction in degrees clockwise from due north. */
  float Direction;

  /** Required: Wind speed (m/s) in the specified WindDirection. */
  float HorizontalSpeed;

  /** Optional. Wind speed in m/s. Negative number is a downdraft. Default is 0. */
  float VerticalSpeed;

  public float getDirection() {
    return this.Direction;
  }

  public void setDirection(float Direction) {
    this.Direction = Direction;
  }

  public float getHorizontalSpeed() {
    return this.HorizontalSpeed;
  }

  public void setHorizontalSpeed(float HorizontalSpeed) {
    this.HorizontalSpeed = HorizontalSpeed;
  }

  public float getVerticalSpeed() {
    return this.VerticalSpeed;
  }

  public void setVerticalSpeed(float VerticalSpeed) {
    this.VerticalSpeed = VerticalSpeed;
  }
}
