// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.AidTypeEnum8;

/** This class defines additional attributes for aid to navigation (ATON) equipment. */
public class AidToNavigation extends AIS_Equipment {

  /** Optional. Type of AtoN. */
  AidTypeEnum8 AidType;

  /** Optional. Distance in meters to stern, in accordance with ITU-R M.1371-5 (02/2014). */
  Float DimensionToStern;

  /** Optional. Distance in meters to bow, in accordance with ITU-R M.1371-5 (02/2014). */
  Float DimensionToBow;

  /** Optional. Distance in meters to port, in accordance with ITU-R M.1371-5 (02/2014). */
  Float DimensionToPort;

  /** Optional. Distance in meters to starboard, in accordance with ITU-R M.1371-5 (02/2014). */
  Float DimensionToStarboard;

  public AidTypeEnum8 getAidType() {
    return this.AidType;
  }

  public void setAidType(AidTypeEnum8 AidType) {
    this.AidType = AidType;
  }

  public Float getDimensionToStern() {
    return this.DimensionToStern;
  }

  public void setDimensionToStern(Float DimensionToStern) {
    this.DimensionToStern = DimensionToStern;
  }

  public Float getDimensionToBow() {
    return this.DimensionToBow;
  }

  public void setDimensionToBow(Float DimensionToBow) {
    this.DimensionToBow = DimensionToBow;
  }

  public Float getDimensionToPort() {
    return this.DimensionToPort;
  }

  public void setDimensionToPort(Float DimensionToPort) {
    this.DimensionToPort = DimensionToPort;
  }

  public Float getDimensionToStarboard() {
    return this.DimensionToStarboard;
  }

  public void setDimensionToStarboard(Float DimensionToStarboard) {
    this.DimensionToStarboard = DimensionToStarboard;
  }
}
