// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.AgentTypeEnum16;
import nl.tno.oorti.test.netn4.datatypes.CBRNSensorReadingStruct;

/**
 * Represents a CBRN sensor. This object is used to pass information to a CBRN federate, which will
 * return sensor readings by publishing CBRN_SensorUpdate interactions.
 */
public class CBRN_Sensor extends Sensor {

  /** Duration that this sensor would like between updated readings. */
  Integer UpdateFrequency;

  /** Duration the sensor will collect samples. */
  Integer AveragingTime;

  /** Array of agents that this sensor wishes to detect. */
  AgentTypeEnum16[] DetectableAgents;

  /** Latest sensor readings. Defaults to no readings if this attribute is not set. */
  CBRNSensorReadingStruct[] SensorReadings;

  public Integer getUpdateFrequency() {
    return this.UpdateFrequency;
  }

  public void setUpdateFrequency(Integer UpdateFrequency) {
    this.UpdateFrequency = UpdateFrequency;
  }

  public Integer getAveragingTime() {
    return this.AveragingTime;
  }

  public void setAveragingTime(Integer AveragingTime) {
    this.AveragingTime = AveragingTime;
  }

  public AgentTypeEnum16[] getDetectableAgents() {
    return this.DetectableAgents;
  }

  public void setDetectableAgents(AgentTypeEnum16[] DetectableAgents) {
    this.DetectableAgents = DetectableAgents;
  }

  public CBRNSensorReadingStruct[] getSensorReadings() {
    return this.SensorReadings;
  }

  public void setSensorReadings(CBRNSensorReadingStruct[] SensorReadings) {
    this.SensorReadings = SensorReadings;
  }
}
