// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.ProtectionEffectivenessStruct;

/** Represents a feature that provides Collective Protection (COLPRO) against a CBRN threat. */
public class COLPRO extends CulturalFeature {

  /** The effectiveness that this COLPRO offers for each agent. */
  ProtectionEffectivenessStruct[] Protection;

  public ProtectionEffectivenessStruct[] getProtection() {
    return this.Protection;
  }

  public void setProtection(ProtectionEffectivenessStruct[] Protection) {
    this.Protection = Protection;
  }
}
