// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.CommunicationNetworkTypeEnum;
import nl.tno.oorti.test.netn4.datatypes.CommunicationServiceTypeEnum;

/**
 * The `CommunicationNetwork` class specifies details about the type of service used by a logical
 * communication network. This corresponds to the CommunicationNet-Elements of MSDL Units and
 * Equipments. Instances of this object class should be considered optional. No federate should rely
 * on this data to work with communication networks.
 */
public class CommunicationNetwork extends COM_Root {

  /** Required. Communication network name. Unique in the context of communication networks. */
  String Name;

  /** Optional. The communication network type of use. */
  CommunicationNetworkTypeEnum NetworkType;

  /** Optional. The type of service used on the communication network. */
  CommunicationServiceTypeEnum ServiceType;

  public String getName() {
    return this.Name;
  }

  public void setName(String Name) {
    this.Name = Name;
  }

  public CommunicationNetworkTypeEnum getNetworkType() {
    return this.NetworkType;
  }

  public void setNetworkType(CommunicationNetworkTypeEnum NetworkType) {
    this.NetworkType = NetworkType;
  }

  public CommunicationServiceTypeEnum getServiceType() {
    return this.ServiceType;
  }

  public void setServiceType(CommunicationServiceTypeEnum ServiceType) {
    this.ServiceType = ServiceType;
  }
}
