// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

/**
 * A pit, depression, or cavity formed in the surface of the earth by an explosion. The depression's
 * shape can range from saucer to conical, depending largely of the depth of burst.
 */
public class CraterObject extends PointObject {

  /**
   * Specifies the diameter of the crater, where the center of the crater is at the point object
   * location
   */
  Integer CraterSize;

  public Integer getCraterSize() {
    return this.CraterSize;
  }

  public void setCraterSize(Integer CraterSize) {
    this.CraterSize = CraterSize;
  }
}
