// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.TreatmentStruct;

/** Represents a feature that provides treatment for CBRN exposure. */
public class DecontaminationStation extends CulturalFeature {

  /** Required: Duration it takes to decontaminate an entity. */
  Integer DecontaminationPeriod;

  /** Required: The types of treatment that this decontamination station currently offers. */
  TreatmentStruct[] Treatments;

  public Integer getDecontaminationPeriod() {
    return this.DecontaminationPeriod;
  }

  public void setDecontaminationPeriod(Integer DecontaminationPeriod) {
    this.DecontaminationPeriod = DecontaminationPeriod;
  }

  public TreatmentStruct[] getTreatments() {
    return this.Treatments;
  }

  public void setTreatments(TreatmentStruct[] Treatments) {
    this.Treatments = Treatments;
  }
}
