// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.mim4.objects.HLAobjectRoot;
import nl.tno.oorti.test.netn4.datatypes.EntityIdentifierStruct;
import nl.tno.oorti.test.netn4.datatypes.RelativePositionStruct;

/**
 * A base class used to associate components such as sensor and emitting systems with their parent
 * entity object.
 */
public class EmbeddedSystem extends HLAobjectRoot {

  /** The EntityIdentifier of the object which this embedded system is a part of. */
  EntityIdentifierStruct EntityIdentifier;

  /** The RTI object instance ID of the object of which this embedded system is part of. */
  String HostObjectIdentifier;

  /** The position of the embedded system, relative to the host object's position. */
  RelativePositionStruct RelativePosition;

  public EntityIdentifierStruct getEntityIdentifier() {
    return this.EntityIdentifier;
  }

  public void setEntityIdentifier(EntityIdentifierStruct EntityIdentifier) {
    this.EntityIdentifier = EntityIdentifier;
  }

  public String getHostObjectIdentifier() {
    return this.HostObjectIdentifier;
  }

  public void setHostObjectIdentifier(String HostObjectIdentifier) {
    this.HostObjectIdentifier = HostObjectIdentifier;
  }

  public RelativePositionStruct getRelativePosition() {
    return this.RelativePosition;
  }

  public void setRelativePosition(RelativePositionStruct RelativePosition) {
    this.RelativePosition = RelativePosition;
  }
}
