// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.OpacityCodeEnum32;

/**
 * An object which has physical extent but not necessarily fixed size and shape, such as
 * meteorological effects such as clouds or smokes.
 */
public class EnvironmentalEntity extends BaseEntity {

  /** Specifies the density of an environmental entity */
  OpacityCodeEnum32 OpacityCode;

  public OpacityCodeEnum32 getOpacityCode() {
    return this.OpacityCode;
  }

  public void setOpacityCode(OpacityCodeEnum32 OpacityCode) {
    this.OpacityCode = OpacityCode;
  }
}
