// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import java.util.UUID;
import nl.tno.oorti.test.mim4.objects.HLAobjectRoot;
import nl.tno.oorti.test.netn4.datatypes.ActiveStatusEnum8;
import nl.tno.oorti.test.netn4.datatypes.DamageStatusEnhancedEnum32;
import nl.tno.oorti.test.netn4.datatypes.EntityIdentifierStruct;
import nl.tno.oorti.test.netn4.datatypes.EnvironmentObjectTypeStruct;
import nl.tno.oorti.test.netn4.datatypes.ForceIdentifierEnum8;
import nl.tno.oorti.test.netn4.datatypes.SymbolStruct;

/** A base class of environment point, linear, or areal object classes. */
public class EnvironmentObject extends HLAobjectRoot {

  /** Optional. A name of the EnvironmentObject. */
  String Name;

  /** Optional. A symbol identifier. */
  SymbolStruct Symbol;

  /**
   * Optional. Specifies if the EnvironmentObject is considered active in the simulation. An
   * inactive object should not affect other simulation models. The default value is 1 (Active).
   */
  ActiveStatusEnum8 Status;

  /** Optional. The damage state of an EnvironmentObject. The default value is 0 (NoDamage). */
  DamageStatusEnhancedEnum32 DamageState;

  /** Optional. A descriptive text comment. */
  String Comment;

  /** Optional. Reference to the host object. Required when using Breach/Burst objects. */
  UUID HostObject;

  /** Identifies this EnvironmentObject instance (point, linear or areal) */
  EntityIdentifierStruct ObjectIdentifier;

  /**
   * Identifies the Synthetic Environment object instance to which this EnvironmentObject instance
   * is associated
   */
  String ReferencedObjectIdentifier;

  /** Identifies the force that created or modified this EnvironmentObject instance */
  ForceIdentifierEnum8 ForceIdentifier;

  /** Identifies the type of this EnvironmentObject instance */
  EnvironmentObjectTypeStruct ObjectType;

  public String getName() {
    return this.Name;
  }

  public void setName(String Name) {
    this.Name = Name;
  }

  public SymbolStruct getSymbol() {
    return this.Symbol;
  }

  public void setSymbol(SymbolStruct Symbol) {
    this.Symbol = Symbol;
  }

  public ActiveStatusEnum8 getStatus() {
    return this.Status;
  }

  public void setStatus(ActiveStatusEnum8 Status) {
    this.Status = Status;
  }

  public DamageStatusEnhancedEnum32 getDamageState() {
    return this.DamageState;
  }

  public void setDamageState(DamageStatusEnhancedEnum32 DamageState) {
    this.DamageState = DamageState;
  }

  public String getComment() {
    return this.Comment;
  }

  public void setComment(String Comment) {
    this.Comment = Comment;
  }

  public UUID getHostObject() {
    return this.HostObject;
  }

  public void setHostObject(UUID HostObject) {
    this.HostObject = HostObject;
  }

  public EntityIdentifierStruct getObjectIdentifier() {
    return this.ObjectIdentifier;
  }

  public void setObjectIdentifier(EntityIdentifierStruct ObjectIdentifier) {
    this.ObjectIdentifier = ObjectIdentifier;
  }

  public String getReferencedObjectIdentifier() {
    return this.ReferencedObjectIdentifier;
  }

  public void setReferencedObjectIdentifier(String ReferencedObjectIdentifier) {
    this.ReferencedObjectIdentifier = ReferencedObjectIdentifier;
  }

  public ForceIdentifierEnum8 getForceIdentifier() {
    return this.ForceIdentifier;
  }

  public void setForceIdentifier(ForceIdentifierEnum8 ForceIdentifier) {
    this.ForceIdentifier = ForceIdentifier;
  }

  public EnvironmentObjectTypeStruct getObjectType() {
    return this.ObjectType;
  }

  public void setObjectType(EnvironmentObjectTypeStruct ObjectType) {
    this.ObjectType = ObjectType;
  }
}
