// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.mim4.objects.HLAobjectRoot;
import nl.tno.oorti.test.netn4.datatypes.TaskDefinition;
import nl.tno.oorti.test.netn4.datatypes.TaskProgress;

/**
 * Object to represent a task and its execution progress when delegated to a federate application
 * other than the one responsible for the tasked entity.
 */
public class ETR_DelegatedTask extends HLAobjectRoot {

  /** Required. Definition description of the task represented. */
  TaskDefinition TaskDefinition;

  /** Required. Progress description of the task represented. */
  TaskProgress TaskProgress;

  public TaskDefinition getTaskDefinition() {
    return this.TaskDefinition;
  }

  public void setTaskDefinition(TaskDefinition TaskDefinition) {
    this.TaskDefinition = TaskDefinition;
  }

  public TaskProgress getTaskProgress() {
    return this.TaskProgress;
  }

  public void setTaskProgress(TaskProgress TaskProgress) {
    this.TaskProgress = TaskProgress;
  }
}
