// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.ExhaustSmokeStruct;

/** An exhaust smoke linear object. */
public class ExhaustSmokeObject extends LinearObject {

  /** Specifies an exhaust smoke linear object */
  ExhaustSmokeStruct[] SegmentRecords;

  public ExhaustSmokeStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(ExhaustSmokeStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
