// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

/**
 * A firebreak is a corridor without any burning things. The firebreak should separate the burning
 * part from the not burning part.
 */
public class Firebreak extends BreachableLinearObject {

  /** Required: Width of the firebreak. */
  Float Width;

  public Float getWidth() {
    return this.Width;
  }

  public void setWidth(Float Width) {
    this.Width = Width;
  }
}
