// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

/** Representation of a flooded area. */
public class Flooding extends DIM_HazardRegion {

  /**
   * Required: FloodingLevel represents the water level of the flooding relative to the Mean Sea
   * Level (MSL).
   */
  Float Level;

  /** Optional: The water level change over time. */
  Float LevelChange;

  public Float getLevel() {
    return this.Level;
  }

  public void setLevel(Float Level) {
    this.Level = Level;
  }

  public Float getLevelChange() {
    return this.LevelChange;
  }

  public void setLevelChange(Float LevelChange) {
    this.LevelChange = LevelChange;
  }
}
