// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.mim4.objects.HLAobjectRoot;
import nl.tno.oorti.test.netn4.datatypes.EntityIdentifierStruct;
import nl.tno.oorti.test.netn4.datatypes.EnvironmentDataCoordinateSystemEnum16;
import nl.tno.oorti.test.netn4.datatypes.EnvironmentGridTypeEnum8;
import nl.tno.oorti.test.netn4.datatypes.EnvironmentTypeStruct;
import nl.tno.oorti.test.netn4.datatypes.GridAxisStruct;
import nl.tno.oorti.test.netn4.datatypes.GridDataStruct;
import nl.tno.oorti.test.netn4.datatypes.OrientationStruct;

/** An object class used to depict global, spatially varying environmental effects. */
public class GriddedData extends HLAobjectRoot {

  /** Identifies the environmental simulation application */
  EntityIdentifierStruct GridIdentifier;

  /** Specifies the coordinate system used to locate the data grid */
  EnvironmentDataCoordinateSystemEnum16 CoordinateSystem;

  /**
   * Specifies the number of grid axes used to define the data grid (e.g. three grid axes for an x,
   * y, z coordinate system)
   */
  Byte NumberOfGridAxes;

  /** Specifies whether the grid axes remain constant for the life of the data grid */
  EnvironmentGridTypeEnum8 ConstantGrid;

  /** Identifies the type of environmental entity being described */
  EnvironmentTypeStruct EnvironmentType;

  /** Specifies the orientation of the data grid, with Euler angles */
  OrientationStruct Orientation;

  /** Specifies the valid time of the environmental data sample */
  Long SampleTime;

  /** Specifies the number of data values that make up this grid */
  Integer TotalValues;

  /**
   * Specifies the number of data values at each grid point ; VectorDimension shall be one for
   * scalar data, and shall be greater than one when multiple enumerated environmental data values
   * are sent for each grid point (e.g. u, v, w wind components have VectorDimension = 3)
   */
  Byte VectorDimension;

  /** Specifies information on grid axes */
  GridAxisStruct[] GridAxisInfo;

  /** Specifies information on grid data representations */
  GridDataStruct[] GridDataInfo;

  public EntityIdentifierStruct getGridIdentifier() {
    return this.GridIdentifier;
  }

  public void setGridIdentifier(EntityIdentifierStruct GridIdentifier) {
    this.GridIdentifier = GridIdentifier;
  }

  public EnvironmentDataCoordinateSystemEnum16 getCoordinateSystem() {
    return this.CoordinateSystem;
  }

  public void setCoordinateSystem(EnvironmentDataCoordinateSystemEnum16 CoordinateSystem) {
    this.CoordinateSystem = CoordinateSystem;
  }

  public Byte getNumberOfGridAxes() {
    return this.NumberOfGridAxes;
  }

  public void setNumberOfGridAxes(Byte NumberOfGridAxes) {
    this.NumberOfGridAxes = NumberOfGridAxes;
  }

  public EnvironmentGridTypeEnum8 getConstantGrid() {
    return this.ConstantGrid;
  }

  public void setConstantGrid(EnvironmentGridTypeEnum8 ConstantGrid) {
    this.ConstantGrid = ConstantGrid;
  }

  public EnvironmentTypeStruct getEnvironmentType() {
    return this.EnvironmentType;
  }

  public void setEnvironmentType(EnvironmentTypeStruct EnvironmentType) {
    this.EnvironmentType = EnvironmentType;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }

  public Long getSampleTime() {
    return this.SampleTime;
  }

  public void setSampleTime(Long SampleTime) {
    this.SampleTime = SampleTime;
  }

  public Integer getTotalValues() {
    return this.TotalValues;
  }

  public void setTotalValues(Integer TotalValues) {
    this.TotalValues = TotalValues;
  }

  public Byte getVectorDimension() {
    return this.VectorDimension;
  }

  public void setVectorDimension(Byte VectorDimension) {
    this.VectorDimension = VectorDimension;
  }

  public GridAxisStruct[] getGridAxisInfo() {
    return this.GridAxisInfo;
  }

  public void setGridAxisInfo(GridAxisStruct[] GridAxisInfo) {
    this.GridAxisInfo = GridAxisInfo;
  }

  public GridDataStruct[] getGridDataInfo() {
    return this.GridDataInfo;
  }

  public void setGridDataInfo(GridDataStruct[] GridDataInfo) {
    this.GridDataInfo = GridDataInfo;
  }
}
