// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.RPRboolean;

/** A platform entity that operates wholly on the surface of the earth. */
public class GroundVehicle extends Platform {

  /**
   * Optional: Whether the entity's emergency lights are on or not. A value of true, indicating that
   * the lights are on, means that the lights begin flashing in accordance with the duty cylce of
   * the model. Default Off = False.
   */
  RPRboolean EmergencyLightsOn;

  /**
   * Optional: Whether the entity's left front and left rear indicator lights are on or not. A value
   * of true, indicating that the lights are on, means that the lights begin flashing in accordance
   * with the duty cylce of the model. Default Off = False.
   */
  RPRboolean LeftIndicatorLightsOn;

  /**
   * Optional: Whether the entity's right front and right rear indicator lights are on or not.
   * Default Off = False.
   */
  RPRboolean RightIndicatorLightsOn;

  public RPRboolean getEmergencyLightsOn() {
    return this.EmergencyLightsOn;
  }

  public void setEmergencyLightsOn(RPRboolean EmergencyLightsOn) {
    this.EmergencyLightsOn = EmergencyLightsOn;
  }

  public RPRboolean getLeftIndicatorLightsOn() {
    return this.LeftIndicatorLightsOn;
  }

  public void setLeftIndicatorLightsOn(RPRboolean LeftIndicatorLightsOn) {
    this.LeftIndicatorLightsOn = LeftIndicatorLightsOn;
  }

  public RPRboolean getRightIndicatorLightsOn() {
    return this.RightIndicatorLightsOn;
  }

  public void setRightIndicatorLightsOn(RPRboolean RightIndicatorLightsOn) {
    this.RightIndicatorLightsOn = RightIndicatorLightsOn;
  }
}
