// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.CBRNDamageEnum8;
import nl.tno.oorti.test.netn4.datatypes.CBRNExposureStruct;
import nl.tno.oorti.test.netn4.datatypes.IPETypeEnum8;
import nl.tno.oorti.test.netn4.datatypes.TreatmentStruct;

/** A human lifeform. */
public class Human extends Lifeform {

  /** Array of agents to which this entity has been exposed to. Defaults to an empty array. */
  CBRNExposureStruct[] Exposures;

  /** The types of treatment that this entity has used. Defaults to an empty array. */
  TreatmentStruct[] Treatments;

  /** Triage level of this entity. Defaults to Uninjured. */
  CBRNDamageEnum8 TriageLevel;

  /** Type of IPE that the entity is using. Defaults to None. */
  IPETypeEnum8 IPEType;

  public CBRNExposureStruct[] getExposures() {
    return this.Exposures;
  }

  public void setExposures(CBRNExposureStruct[] Exposures) {
    this.Exposures = Exposures;
  }

  public TreatmentStruct[] getTreatments() {
    return this.Treatments;
  }

  public void setTreatments(TreatmentStruct[] Treatments) {
    this.Treatments = Treatments;
  }

  public CBRNDamageEnum8 getTriageLevel() {
    return this.TriageLevel;
  }

  public void setTriageLevel(CBRNDamageEnum8 TriageLevel) {
    this.TriageLevel = TriageLevel;
  }

  public IPETypeEnum8 getIPEType() {
    return this.IPEType;
  }

  public void setIPEType(IPETypeEnum8 IPEType) {
    this.IPEType = IPEType;
  }
}
