// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.LandslideTypeEnum;

/** Use the `Landslide` object to represent a landslide area covered by mud, snow or gravel. */
public class Landslide extends DIM_HazardRegion {

  /** Required: Thickness in meter. */
  Float Thickness;

  /** Optional: The type of landslide material. Default = 0. */
  LandslideTypeEnum LandslideType;

  public Float getThickness() {
    return this.Thickness;
  }

  public void setThickness(Float Thickness) {
    this.Thickness = Thickness;
  }

  public LandslideTypeEnum getLandslideType() {
    return this.LandslideType;
  }

  public void setLandslideType(LandslideTypeEnum LandslideType) {
    this.LandslideType = LandslideType;
  }
}
