// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import java.util.UUID;
import nl.tno.oorti.test.netn4.datatypes.LinkStatusStruct;

/**
 * A `LinkStates` object describes the presence and quality of a set of direct links between nodes
 * on a physical level. Links are defined between a transmitting and receiving device.
 *
 * <p>Bidirectional links assume identical link quality in both directions. Otherwise, two
 * unidirectional links should be described.
 *
 * <p>Each `LinkStates` instance is associated with one physical network. To support load balancing
 * in link quality simulation, multiple `LinkStates` instances can be associated with the same
 * physical network as long as they do not contain duplicated link-state information.
 *
 * <p>A link should not be contained in more than one `LinkStates` object. If a link is not
 * contained in any instance, it is not present, and it means it could not be established.
 *
 * <p>The `LinkStates` provides information that can be used to calculate connections.
 */
public class LinkStates extends COM_Root {

  /** Required. Reference to a physical network. */
  UUID PhysicalNetwork;

  /** Required. Status of a set of physical network links. */
  LinkStatusStruct[] Links;

  public UUID getPhysicalNetwork() {
    return this.PhysicalNetwork;
  }

  public void setPhysicalNetwork(UUID PhysicalNetwork) {
    this.PhysicalNetwork = PhysicalNetwork;
  }

  public LinkStatusStruct[] getLinks() {
    return this.Links;
  }

  public void setLinks(LinkStatusStruct[] Links) {
    this.Links = Links;
  }
}
