// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.EnvironmentConditionModelTypeEnum32;

/** The available METOC services are objects in the federation. */
public class METOC_Service extends SMC_Service {

  /**
   * Required. Type of METOC model provided by the service. Specifies whether the service delivers
   * Simulated, Real (Historical), Live (Current) or Standard model data.
   */
  EnvironmentConditionModelTypeEnum32 ModelType;

  public EnvironmentConditionModelTypeEnum32 getModelType() {
    return this.ModelType;
  }

  public void setModelType(EnvironmentConditionModelTypeEnum32 ModelType) {
    this.ModelType = ModelType;
  }
}
