// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.MinefieldLaneMarkerStruct;

/**
 * A minefield lane marker showing a cleared lane through a specific minefield, defined as a linear
 * object.
 */
public class MinefieldLaneMarkerObject extends LinearObject {

  /** Specifies a minefield lane marker showing a cleared lane through a minefield */
  MinefieldLaneMarkerStruct[] SegmentRecords;

  public MinefieldLaneMarkerStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(MinefieldLaneMarkerStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
