// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.IffAlternateMode4Enum8;
import nl.tno.oorti.test.netn4.datatypes.RPRboolean;

/**
 * NATO Identification Friend or Foe (IFF) system that uses electromagnetic transmissions to which
 * friendly forces' equipment automatically responds.
 */
public class NatoIFF extends IFF {

  /** IFF Alternate Mode 4. */
  IffAlternateMode4Enum8 AlternateMode4;

  /** Specifies whether or not Mode 1 is enabled. */
  RPRboolean Mode1Enabled;

  /** Specifies whether or not Mode 1 is damaged. */
  RPRboolean Mode1IsDamaged;

  /** Specifies whether or not Mode 1 is malfunctioning. */
  RPRboolean Mode1IsMalfunctioning;

  /** Specifies whether or not Mode 1 is on. */
  RPRboolean Mode1IsOn;

  /** Specifies whether or not Mode 2 is enabled. */
  RPRboolean Mode2Enabled;

  /** Specifies whether or not Mode 2 is damaged. */
  RPRboolean Mode2IsDamaged;

  /** Specifies whether or not Mode 2 is malfunctioning. */
  RPRboolean Mode2IsMalfunctioning;

  /** Specifies whether or not Mode 2 is on. */
  RPRboolean Mode2IsOn;

  /** Specifies whether or not Mode 3 is enabled. */
  RPRboolean Mode3AEnabled;

  /** Specifies whether or not Mode 3 is damaged. */
  RPRboolean Mode3AIsDamaged;

  /** Specifies whether or not Mode 3 is malfunctioning. */
  RPRboolean Mode3AIsMalfunctioning;

  /** Specifies whether or not Mode 3 is on. */
  RPRboolean Mode3AIsOn;

  /** Specifies whether or not Mode 4 is enabled. */
  RPRboolean Mode4Enabled;

  /** Specifies whether or not Mode 4 is damaged. */
  RPRboolean Mode4IsDamaged;

  /** Specifies whether or not Mode 4 is malfunctioning. */
  RPRboolean Mode4IsMalfunctioning;

  /** Specifies whether or not Mode 4 is on. */
  RPRboolean Mode4IsOn;

  /** Mode 4 Pseudo-Crypto value (0-4094). */
  Short Mode4PseudoCrypto;

  /** Specifies whether or not Mode 4 pseudo-crypto value is available. */
  RPRboolean Mode4PseudoCryptoAvailable;

  /** Specifies whether or not Parameter 5 - Mode C is enabled. */
  RPRboolean Mode5CEnabled;

  /** Specifies whether or not Parameter 5 - Mode C is damaged. */
  RPRboolean Mode5CIsDamaged;

  /** Specifies whether or not Parameter 5 - Mode C is malfunctioning. */
  RPRboolean Mode5CIsMalfunctioning;

  /** Specifies whether or not Parameter 5 - Mode C is on. */
  RPRboolean Mode5CIsOn;

  /** Specifies whether or not Parameter 6 - Mode S is enabled. */
  RPRboolean ModeSEnabled;

  /** Specifies whether or not Parameter 6 - Mode S is damaged. */
  RPRboolean ModeSIsDamaged;

  /** Specifies whether or not Parameter 6 - Mode S is malfunctioning. */
  RPRboolean ModeSIsMalfunctioning;

  /** Specifies whether or not Parameter 6 - Mode S is on. */
  RPRboolean ModeSIsOn;

  /**
   * Specifies which Traffic Alert/Collision Avoidance System is used. FALSE means TCAS I, TRUE
   * means TCAS II.
   */
  RPRboolean ModeSIsTcasI;

  public IffAlternateMode4Enum8 getAlternateMode4() {
    return this.AlternateMode4;
  }

  public void setAlternateMode4(IffAlternateMode4Enum8 AlternateMode4) {
    this.AlternateMode4 = AlternateMode4;
  }

  public RPRboolean getMode1Enabled() {
    return this.Mode1Enabled;
  }

  public void setMode1Enabled(RPRboolean Mode1Enabled) {
    this.Mode1Enabled = Mode1Enabled;
  }

  public RPRboolean getMode1IsDamaged() {
    return this.Mode1IsDamaged;
  }

  public void setMode1IsDamaged(RPRboolean Mode1IsDamaged) {
    this.Mode1IsDamaged = Mode1IsDamaged;
  }

  public RPRboolean getMode1IsMalfunctioning() {
    return this.Mode1IsMalfunctioning;
  }

  public void setMode1IsMalfunctioning(RPRboolean Mode1IsMalfunctioning) {
    this.Mode1IsMalfunctioning = Mode1IsMalfunctioning;
  }

  public RPRboolean getMode1IsOn() {
    return this.Mode1IsOn;
  }

  public void setMode1IsOn(RPRboolean Mode1IsOn) {
    this.Mode1IsOn = Mode1IsOn;
  }

  public RPRboolean getMode2Enabled() {
    return this.Mode2Enabled;
  }

  public void setMode2Enabled(RPRboolean Mode2Enabled) {
    this.Mode2Enabled = Mode2Enabled;
  }

  public RPRboolean getMode2IsDamaged() {
    return this.Mode2IsDamaged;
  }

  public void setMode2IsDamaged(RPRboolean Mode2IsDamaged) {
    this.Mode2IsDamaged = Mode2IsDamaged;
  }

  public RPRboolean getMode2IsMalfunctioning() {
    return this.Mode2IsMalfunctioning;
  }

  public void setMode2IsMalfunctioning(RPRboolean Mode2IsMalfunctioning) {
    this.Mode2IsMalfunctioning = Mode2IsMalfunctioning;
  }

  public RPRboolean getMode2IsOn() {
    return this.Mode2IsOn;
  }

  public void setMode2IsOn(RPRboolean Mode2IsOn) {
    this.Mode2IsOn = Mode2IsOn;
  }

  public RPRboolean getMode3AEnabled() {
    return this.Mode3AEnabled;
  }

  public void setMode3AEnabled(RPRboolean Mode3AEnabled) {
    this.Mode3AEnabled = Mode3AEnabled;
  }

  public RPRboolean getMode3AIsDamaged() {
    return this.Mode3AIsDamaged;
  }

  public void setMode3AIsDamaged(RPRboolean Mode3AIsDamaged) {
    this.Mode3AIsDamaged = Mode3AIsDamaged;
  }

  public RPRboolean getMode3AIsMalfunctioning() {
    return this.Mode3AIsMalfunctioning;
  }

  public void setMode3AIsMalfunctioning(RPRboolean Mode3AIsMalfunctioning) {
    this.Mode3AIsMalfunctioning = Mode3AIsMalfunctioning;
  }

  public RPRboolean getMode3AIsOn() {
    return this.Mode3AIsOn;
  }

  public void setMode3AIsOn(RPRboolean Mode3AIsOn) {
    this.Mode3AIsOn = Mode3AIsOn;
  }

  public RPRboolean getMode4Enabled() {
    return this.Mode4Enabled;
  }

  public void setMode4Enabled(RPRboolean Mode4Enabled) {
    this.Mode4Enabled = Mode4Enabled;
  }

  public RPRboolean getMode4IsDamaged() {
    return this.Mode4IsDamaged;
  }

  public void setMode4IsDamaged(RPRboolean Mode4IsDamaged) {
    this.Mode4IsDamaged = Mode4IsDamaged;
  }

  public RPRboolean getMode4IsMalfunctioning() {
    return this.Mode4IsMalfunctioning;
  }

  public void setMode4IsMalfunctioning(RPRboolean Mode4IsMalfunctioning) {
    this.Mode4IsMalfunctioning = Mode4IsMalfunctioning;
  }

  public RPRboolean getMode4IsOn() {
    return this.Mode4IsOn;
  }

  public void setMode4IsOn(RPRboolean Mode4IsOn) {
    this.Mode4IsOn = Mode4IsOn;
  }

  public Short getMode4PseudoCrypto() {
    return this.Mode4PseudoCrypto;
  }

  public void setMode4PseudoCrypto(Short Mode4PseudoCrypto) {
    this.Mode4PseudoCrypto = Mode4PseudoCrypto;
  }

  public RPRboolean getMode4PseudoCryptoAvailable() {
    return this.Mode4PseudoCryptoAvailable;
  }

  public void setMode4PseudoCryptoAvailable(RPRboolean Mode4PseudoCryptoAvailable) {
    this.Mode4PseudoCryptoAvailable = Mode4PseudoCryptoAvailable;
  }

  public RPRboolean getMode5CEnabled() {
    return this.Mode5CEnabled;
  }

  public void setMode5CEnabled(RPRboolean Mode5CEnabled) {
    this.Mode5CEnabled = Mode5CEnabled;
  }

  public RPRboolean getMode5CIsDamaged() {
    return this.Mode5CIsDamaged;
  }

  public void setMode5CIsDamaged(RPRboolean Mode5CIsDamaged) {
    this.Mode5CIsDamaged = Mode5CIsDamaged;
  }

  public RPRboolean getMode5CIsMalfunctioning() {
    return this.Mode5CIsMalfunctioning;
  }

  public void setMode5CIsMalfunctioning(RPRboolean Mode5CIsMalfunctioning) {
    this.Mode5CIsMalfunctioning = Mode5CIsMalfunctioning;
  }

  public RPRboolean getMode5CIsOn() {
    return this.Mode5CIsOn;
  }

  public void setMode5CIsOn(RPRboolean Mode5CIsOn) {
    this.Mode5CIsOn = Mode5CIsOn;
  }

  public RPRboolean getModeSEnabled() {
    return this.ModeSEnabled;
  }

  public void setModeSEnabled(RPRboolean ModeSEnabled) {
    this.ModeSEnabled = ModeSEnabled;
  }

  public RPRboolean getModeSIsDamaged() {
    return this.ModeSIsDamaged;
  }

  public void setModeSIsDamaged(RPRboolean ModeSIsDamaged) {
    this.ModeSIsDamaged = ModeSIsDamaged;
  }

  public RPRboolean getModeSIsMalfunctioning() {
    return this.ModeSIsMalfunctioning;
  }

  public void setModeSIsMalfunctioning(RPRboolean ModeSIsMalfunctioning) {
    this.ModeSIsMalfunctioning = ModeSIsMalfunctioning;
  }

  public RPRboolean getModeSIsOn() {
    return this.ModeSIsOn;
  }

  public void setModeSIsOn(RPRboolean ModeSIsOn) {
    this.ModeSIsOn = ModeSIsOn;
  }

  public RPRboolean getModeSIsTcasI() {
    return this.ModeSIsTcasI;
  }

  public void setModeSIsTcasI(RPRboolean ModeSIsTcasI) {
    this.ModeSIsTcasI = ModeSIsTcasI;
  }
}
