// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.RPRboolean;

/**
 * The part of a specific IFF system that responds (for example by emitting pulses) to the
 * electromagnetic signals.
 */
public class NatoIFFTransponder extends NatoIFF {

  /** Specifies whether or not emergency is on. */
  RPRboolean EmergencyOn;

  /** Specifies whether or not the squawk ident/flash is on. */
  RPRboolean IdentSquawkFlashOn;

  /** Mode 1 code, two octal values. */
  Short Mode1Code;

  /** Mode 2 code, four octal values. */
  Short Mode2Code;

  /** Mode 3 code, four octal values. */
  Short Mode3ACode;

  /** Parameter 5 - Mode C altitude. */
  Short Mode5CAltitude;

  /** Specifies whether or not Parameter 5 - Mode C altitude is available. */
  RPRboolean Mode5CAltitudeAvailable;

  /** Specifies whether or not STI is on. */
  RPRboolean StiOn;

  public RPRboolean getEmergencyOn() {
    return this.EmergencyOn;
  }

  public void setEmergencyOn(RPRboolean EmergencyOn) {
    this.EmergencyOn = EmergencyOn;
  }

  public RPRboolean getIdentSquawkFlashOn() {
    return this.IdentSquawkFlashOn;
  }

  public void setIdentSquawkFlashOn(RPRboolean IdentSquawkFlashOn) {
    this.IdentSquawkFlashOn = IdentSquawkFlashOn;
  }

  public Short getMode1Code() {
    return this.Mode1Code;
  }

  public void setMode1Code(Short Mode1Code) {
    this.Mode1Code = Mode1Code;
  }

  public Short getMode2Code() {
    return this.Mode2Code;
  }

  public void setMode2Code(Short Mode2Code) {
    this.Mode2Code = Mode2Code;
  }

  public Short getMode3ACode() {
    return this.Mode3ACode;
  }

  public void setMode3ACode(Short Mode3ACode) {
    this.Mode3ACode = Mode3ACode;
  }

  public Short getMode5CAltitude() {
    return this.Mode5CAltitude;
  }

  public void setMode5CAltitude(Short Mode5CAltitude) {
    this.Mode5CAltitude = Mode5CAltitude;
  }

  public RPRboolean getMode5CAltitudeAvailable() {
    return this.Mode5CAltitudeAvailable;
  }

  public void setMode5CAltitudeAvailable(RPRboolean Mode5CAltitudeAvailable) {
    this.Mode5CAltitudeAvailable = Mode5CAltitudeAvailable;
  }

  public RPRboolean getStiOn() {
    return this.StiOn;
  }

  public void setStiOn(RPRboolean StiOn) {
    this.StiOn = StiOn;
  }
}
