// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

/**
 * Linear objects other than BreachableLinear, Breach, ExhaustSmoke, or MinefieldLaneMarker objects.
 */
public class OtherLinearObject extends LinearObject {}
