// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.PhysicalNetworkDescriptionVariant;

/**
 * The `PhysicalNetwork` object class represents type-specific parameters/constraints for a physical
 * network. Physical networks are simulated by `LinkState` objects and do not require that an
 * instance of PhysicalNetwork exist in the federation.
 */
public class PhysicalNetwork extends COM_Root {

  /** Required. Unique physical network name. Uniqueness in the context of physical networks. */
  String Name;

  /** Required. Characteristics of the physical network. */
  PhysicalNetworkDescriptionVariant Description;

  public String getName() {
    return this.Name;
  }

  public void setName(String Name) {
    this.Name = Name;
  }

  public PhysicalNetworkDescriptionVariant getDescription() {
    return this.Description;
  }

  public void setDescription(PhysicalNetworkDescriptionVariant Description) {
    this.Description = Description;
  }
}
