// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.DamageStatusEnum32;
import nl.tno.oorti.test.netn4.datatypes.OrientationStruct;
import nl.tno.oorti.test.netn4.datatypes.RPRboolean;
import nl.tno.oorti.test.netn4.datatypes.WorldLocationStruct;

/**
 * A synthetic environment object that is geometrically anchored to the terrain with a single point.
 */
public class PointObject extends EnvironmentObject {

  /** Optional. The radius of the point object. */
  Double Radius;

  /** Specifies the location of the object based on x, y and z coordinates */
  WorldLocationStruct Location;

  /**
   * Specifies the angles of rotation around the coordinate axis between the object's attitude and
   * the reference coordinate system axes ; these are calculated as the Tait-Bryan Euler angles,
   * specifying the successive rotations needed to transform from the world coordinate system to the
   * object coordinate system
   */
  OrientationStruct Orientation;

  /** Specifies the percent completion of the object */
  Integer PercentComplete;

  /** Specifies the damaged appearance of the object instance */
  DamageStatusEnum32 DamagedAppearance;

  /** Specifies whether or not the object was created before the start of the exercise */
  RPRboolean ObjectPreDistributed;

  /**
   * Specifies whether or not the object has been deactivated (it has ceased to exist in the
   * synthetic environment)
   */
  RPRboolean Deactivated;

  /** Specifies whether or not the object is smoking (creating a smoke plume) */
  RPRboolean Smoking;

  /** Specifies whether or not the object is aflame */
  RPRboolean Flaming;

  public Double getRadius() {
    return this.Radius;
  }

  public void setRadius(Double Radius) {
    this.Radius = Radius;
  }

  public WorldLocationStruct getLocation() {
    return this.Location;
  }

  public void setLocation(WorldLocationStruct Location) {
    this.Location = Location;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }

  public Integer getPercentComplete() {
    return this.PercentComplete;
  }

  public void setPercentComplete(Integer PercentComplete) {
    this.PercentComplete = PercentComplete;
  }

  public DamageStatusEnum32 getDamagedAppearance() {
    return this.DamagedAppearance;
  }

  public void setDamagedAppearance(DamageStatusEnum32 DamagedAppearance) {
    this.DamagedAppearance = DamagedAppearance;
  }

  public RPRboolean getObjectPreDistributed() {
    return this.ObjectPreDistributed;
  }

  public void setObjectPreDistributed(RPRboolean ObjectPreDistributed) {
    this.ObjectPreDistributed = ObjectPreDistributed;
  }

  public RPRboolean getDeactivated() {
    return this.Deactivated;
  }

  public void setDeactivated(RPRboolean Deactivated) {
    this.Deactivated = Deactivated;
  }

  public RPRboolean getSmoking() {
    return this.Smoking;
  }

  public void setSmoking(RPRboolean Smoking) {
    this.Smoking = Smoking;
  }

  public RPRboolean getFlaming() {
    return this.Flaming;
  }

  public void setFlaming(RPRboolean Flaming) {
    this.Flaming = Flaming;
  }
}
