// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

/** A ribbon bridge object. */
public class RibbonBridgeObject extends PointObject {

  /** Specifies the number of segments composing the ribbon bridge */
  Integer NumberOfSegments;

  public Integer getNumberOfSegments() {
    return this.NumberOfSegments;
  }

  public void setNumberOfSegments(Integer NumberOfSegments) {
    this.NumberOfSegments = NumberOfSegments;
  }
}
