// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.CurrentStruct;
import nl.tno.oorti.test.netn4.datatypes.LayerStruct;
import nl.tno.oorti.test.netn4.datatypes.SedimentTypeEnum32;

/** The environmental condition of a subsurface water layer. */
public class SubsurfaceLayer extends METOC_EnvironmentCondition {

  /**
   * Optional. A body of water extends upwards from a (negative) base altitude (see LayerStruct).
   * Ignore any portion of the layer extending above sea level. The default value is the volume
   * between the sea floor and the surface.
   */
  LayerStruct Layer;

  /**
   * Optional. The distance at which the human eye in the region/location can discern an object or
   * light. Use the minimum distance if overlapping regions/locations exist.
   */
  Float VisibilityRange;

  /** Optional. The temperature at the base altitude of the subsurface layer. Default = 0. */
  Float Temperature;

  /**
   * Optional. Describes current in the water layer. The default is no current. Use the average
   * current direction and speed if overlapping layers exist.
   */
  CurrentStruct Current;

  /**
   * Optional. The salinity of seawater on the practical salinity scale 1978 (PSS-78). The default
   * value is 35 (equivalent to 35 parts per thousand). Use the average salinity if overlapping
   * layers exist.
   */
  Float Salinity;

  /**
   * Optional. Type of sediment on the sea floor. The default is `NoSediment`. Use the latest if
   * overlapping layers exist.
   */
  SedimentTypeEnum32 BottomType;

  public LayerStruct getLayer() {
    return this.Layer;
  }

  public void setLayer(LayerStruct Layer) {
    this.Layer = Layer;
  }

  public Float getVisibilityRange() {
    return this.VisibilityRange;
  }

  public void setVisibilityRange(Float VisibilityRange) {
    this.VisibilityRange = VisibilityRange;
  }

  public Float getTemperature() {
    return this.Temperature;
  }

  public void setTemperature(Float Temperature) {
    this.Temperature = Temperature;
  }

  public CurrentStruct getCurrent() {
    return this.Current;
  }

  public void setCurrent(CurrentStruct Current) {
    this.Current = Current;
  }

  public Float getSalinity() {
    return this.Salinity;
  }

  public void setSalinity(Float Salinity) {
    this.Salinity = Salinity;
  }

  public SedimentTypeEnum32 getBottomType() {
    return this.BottomType;
  }

  public void setBottomType(SedimentTypeEnum32 BottomType) {
    this.BottomType = BottomType;
  }
}
