// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.netn4.objects;

import nl.tno.oorti.test.netn4.datatypes.RPRboolean;
import nl.tno.oorti.test.netn4.datatypes.RefuelingStationLightColorEnum8;
import nl.tno.oorti.test.netn4.datatypes.RefuelingStationLightDayNightEnum8;

/** A tanker aircraft. */
public class TankerAircraft extends Aircraft {

  /** Optional: Whether the refueling station lights are on or not. Default Off = False. */
  RPRboolean RefuelingStation1LightsOn;

  /** Optional: Color of the refueling station lights. Default Red = 0. */
  RefuelingStationLightColorEnum8 RefuelingStation1LightsColor;

  /** Optional: Whether the refueling station lights are flashing. Default Steady = False. */
  RPRboolean RefuelingStation1LightsFlashing;

  /** Optional: Describes the day/night status of the refueling station lights. Default Day = 0. */
  RefuelingStationLightDayNightEnum8 RefuelingStation1DayNight;

  /** Optional: Whether the refueling station lights are on or not. Default Off = False. */
  RPRboolean RefuelingStation2LightsOn;

  /** Optional: Color of the refueling station lights. Default Red = 0. */
  RefuelingStationLightColorEnum8 RefuelingStation2LightsColor;

  /** Optional: Whether the refueling station lights are flashing. Default Steady = False. */
  RPRboolean RefuelingStation2LightsFlashing;

  /** Optional: Describes the day/night status of the refueling station lights. Default Day = 0. */
  RefuelingStationLightDayNightEnum8 RefuelingStation2DayNight;

  /** Optional: Whether the refueling station lights are on or not. Default Off = False. */
  RPRboolean RefuelingStation3LightsOn;

  /** Optional: Color of the refueling station lights. Default Red = 0. */
  RefuelingStationLightColorEnum8 RefuelingStation3LightsColor;

  /** Optional: Whether the refueling station lights are flashing. Default Steady = False. */
  RPRboolean RefuelingStation3LightsFlashing;

  /** Optional: Describes the day/night status of the refueling station lights. Default Day = 0. */
  RefuelingStationLightDayNightEnum8 RefuelingStation3DayNight;

  public RPRboolean getRefuelingStation1LightsOn() {
    return this.RefuelingStation1LightsOn;
  }

  public void setRefuelingStation1LightsOn(RPRboolean RefuelingStation1LightsOn) {
    this.RefuelingStation1LightsOn = RefuelingStation1LightsOn;
  }

  public RefuelingStationLightColorEnum8 getRefuelingStation1LightsColor() {
    return this.RefuelingStation1LightsColor;
  }

  public void setRefuelingStation1LightsColor(
      RefuelingStationLightColorEnum8 RefuelingStation1LightsColor) {
    this.RefuelingStation1LightsColor = RefuelingStation1LightsColor;
  }

  public RPRboolean getRefuelingStation1LightsFlashing() {
    return this.RefuelingStation1LightsFlashing;
  }

  public void setRefuelingStation1LightsFlashing(RPRboolean RefuelingStation1LightsFlashing) {
    this.RefuelingStation1LightsFlashing = RefuelingStation1LightsFlashing;
  }

  public RefuelingStationLightDayNightEnum8 getRefuelingStation1DayNight() {
    return this.RefuelingStation1DayNight;
  }

  public void setRefuelingStation1DayNight(
      RefuelingStationLightDayNightEnum8 RefuelingStation1DayNight) {
    this.RefuelingStation1DayNight = RefuelingStation1DayNight;
  }

  public RPRboolean getRefuelingStation2LightsOn() {
    return this.RefuelingStation2LightsOn;
  }

  public void setRefuelingStation2LightsOn(RPRboolean RefuelingStation2LightsOn) {
    this.RefuelingStation2LightsOn = RefuelingStation2LightsOn;
  }

  public RefuelingStationLightColorEnum8 getRefuelingStation2LightsColor() {
    return this.RefuelingStation2LightsColor;
  }

  public void setRefuelingStation2LightsColor(
      RefuelingStationLightColorEnum8 RefuelingStation2LightsColor) {
    this.RefuelingStation2LightsColor = RefuelingStation2LightsColor;
  }

  public RPRboolean getRefuelingStation2LightsFlashing() {
    return this.RefuelingStation2LightsFlashing;
  }

  public void setRefuelingStation2LightsFlashing(RPRboolean RefuelingStation2LightsFlashing) {
    this.RefuelingStation2LightsFlashing = RefuelingStation2LightsFlashing;
  }

  public RefuelingStationLightDayNightEnum8 getRefuelingStation2DayNight() {
    return this.RefuelingStation2DayNight;
  }

  public void setRefuelingStation2DayNight(
      RefuelingStationLightDayNightEnum8 RefuelingStation2DayNight) {
    this.RefuelingStation2DayNight = RefuelingStation2DayNight;
  }

  public RPRboolean getRefuelingStation3LightsOn() {
    return this.RefuelingStation3LightsOn;
  }

  public void setRefuelingStation3LightsOn(RPRboolean RefuelingStation3LightsOn) {
    this.RefuelingStation3LightsOn = RefuelingStation3LightsOn;
  }

  public RefuelingStationLightColorEnum8 getRefuelingStation3LightsColor() {
    return this.RefuelingStation3LightsColor;
  }

  public void setRefuelingStation3LightsColor(
      RefuelingStationLightColorEnum8 RefuelingStation3LightsColor) {
    this.RefuelingStation3LightsColor = RefuelingStation3LightsColor;
  }

  public RPRboolean getRefuelingStation3LightsFlashing() {
    return this.RefuelingStation3LightsFlashing;
  }

  public void setRefuelingStation3LightsFlashing(RPRboolean RefuelingStation3LightsFlashing) {
    this.RefuelingStation3LightsFlashing = RefuelingStation3LightsFlashing;
  }

  public RefuelingStationLightDayNightEnum8 getRefuelingStation3DayNight() {
    return this.RefuelingStation3DayNight;
  }

  public void setRefuelingStation3DayNight(
      RefuelingStationLightDayNightEnum8 RefuelingStation3DayNight) {
    this.RefuelingStation3DayNight = RefuelingStation3DayNight;
  }
}
