// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.mim4.interactions;

/** Cause the joined federate to cease regulating the logical time of other joined federates */
public class HLAdisableTimeRegulation extends HLAservice {}
