// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * Cause the logical time of the joined federate to begin being constrained by the logical times of
 * other joined federates
 */
public class HLAenableTimeConstrained extends HLAservice {}
