// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/** Mimic the federate's report of starting a save */
public class HLAfederateSaveBegun extends HLAservice {}
