// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.mim4.interactions;

/** Change the lookahead value used by the joined federate */
public class HLAmodifyLookahead extends HLAservice {

  /** New value for lookahead */
  byte[] HLAlookahead;

  public byte[] getHLAlookahead() {
    return this.HLAlookahead;
  }

  public void setHLAlookahead(byte[] HLAlookahead) {
    this.HLAlookahead = HLAlookahead;
  }
}
