// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * Requests that the RTI shall send a report interaction with the content of the specified FOM
 * module for the federation. The FOM module is indicated by the order number in the federations
 * HLAFOMmoduleDesignatorList attribute.
 */
public class HLAmanager_HLAfederation_HLArequest_HLArequestFOMmoduleData
    extends HLAmanager_HLAfederation_HLArequest {

  /** Indicates order number of requested FOM module */
  Integer HLAFOMmoduleIndicator;

  public Integer getHLAFOMmoduleIndicator() {
    return this.HLAFOMmoduleIndicator;
  }

  public void setHLAFOMmoduleIndicator(Integer HLAFOMmoduleIndicator) {
    this.HLAFOMmoduleIndicator = HLAFOMmoduleIndicator;
  }
}
