// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2026/01/25 15:07:27

package nl.tno.oorti.test.mim4.interactions;

/** Permit a federate to receive RTI data about a specific federation execution */
public class HLAmanager_HLAfederation_HLAreport extends HLAfederation {}
