// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

import nl.tno.oorti.test.mim4.datatypes.HLAobjectClassBasedCount;

/**
 * The interaction shall be sent by the RTI in response to an interaction of class
 * HLAmanager.HLAfederate.HLArequest.HLArequestObjectInstancesReflected. It shall report the number
 * of object instances (by registered class of the object instances) for which the joined federate
 * has had a Reflect Attribute Values service invocation. If the joined federate has no object
 * instances that are reflected for a given transport type, then a single interaction shall be sent
 * as a NULL response with the HLAobjectInstanceCounts parameter having an undefined value.
 */
public class HLAreportObjectInstancesReflected extends HLAreport {

  /**
   * List of object instance counts. Each object instance count consists of an object class handle
   * and the number of object instances of that class. This parameter shall be an empty list in a
   * NULL response.
   */
  HLAobjectClassBasedCount[] HLAobjectInstanceCounts;

  public HLAobjectClassBasedCount[] getHLAobjectInstanceCounts() {
    return this.HLAobjectInstanceCounts;
  }

  public void setHLAobjectInstanceCounts(HLAobjectClassBasedCount[] HLAobjectInstanceCounts) {
    this.HLAobjectInstanceCounts = HLAobjectInstanceCounts;
  }
}
