// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * Request that the RTI send a report interaction that contains a list that includes each federate
 * (and its synchronization point status) that is associated with a particular synchronization
 * point. It shall result in one interaction of class
 * HLAmanager.HLAfederation.HLAreport.HLAreportSynchronizationPointStaus.
 */
public class HLArequestSynchronizationPointStatus extends HLAmanager_HLAfederation_HLArequest {}
