// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

import nl.tno.oorti.test.mim4.datatypes.HLAobjectClassBasedCount;

/**
 * The interaction shall be sent by the RTI in response to an interaction of class
 * HLAmanager.HLAfederate.HLArequest.HLArequestReflectionsReceived. It shall report the number of
 * reflections received (by registered class of the object instances of the reflects) by the joined
 * federate since the beginning of the federation execution. One interaction of this class shall be
 * sent by the RTI for each transportation type used. If the joined federate has no reflections
 * received for a given transportation type, then a single interaction shall be sent as a NULL
 * response with the HLAreflectCounts parameter having an undefined value.
 */
public class HLAreportReflectionsReceived extends HLAreport {

  /** Transportation type used in receiving reflections */
  String HLAtransportation;

  /**
   * List of reflection counts. Each reflection count consists of an object class handle and the
   * number of reflections received of that class. If no reflects of instance attributes of any
   * object instances of any class for a given transportation type have been received, then the RTI
   * shall send a HLAmanager.HLAfederate.HLAreport.HLAreportReflectionsReceived interaction for that
   * transportation type. However, no HLAobjectClassBasedCount elements at all shall appear in the
   * HLAobjectClassBasedCount array for that interaction of that transportation type. In other
   * words, the HLAreportReflectionsReceived interaction that is sent for that transportation type
   * shall have an empty HLAobjectClassBasedCount array. If no reflects of instance attributes of
   * any object instances of a given class for a given transportation type have been received, then
   * no HLAobjectClassBasedCount element for that object class shall be in the
   * HLAobjectClassBasedCount array of the HLAmanager.
   * HLAfederate.HLAreport.HLAreportReflectionsReceived interaction for that transportation type.
   * This parameter shall be an empty list in a NULL response for the given transportation type.
   */
  HLAobjectClassBasedCount[] HLAreflectCounts;

  public String getHLAtransportation() {
    return this.HLAtransportation;
  }

  public void setHLAtransportation(String HLAtransportation) {
    this.HLAtransportation = HLAtransportation;
  }

  public HLAobjectClassBasedCount[] getHLAreflectCounts() {
    return this.HLAreflectCounts;
  }

  public void setHLAreflectCounts(HLAobjectClassBasedCount[] HLAreflectCounts) {
    this.HLAreflectCounts = HLAreflectCounts;
  }
}
