// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * The interaction shall be sent by the RTI in response to an interaction of class
 * HLAmanager.HLAfederate.HLArequest.HLArequestObjectInstanceInformation. It shall report on a
 * single object instance and portray the instance attributes of that object instance that are owned
 * by the joined federate, the registered class of the object instance, and the known class of the
 * object instance at that joined federate. If the joined federate does not know the object
 * instance, a single interaction shall be sent as a NULL response with the
 * HLAownedInstanceAttributeList parameter having an undefined value.
 */
public class HLAreportObjectInstanceInformation extends HLAreport {

  /** Handle of the object instance for which the interaction was sent */
  byte[] HLAobjectInstance;

  /**
   * List of the handles of all instance attributes, of the object instance, owned by the joined
   * federate. This parameter shall be an empty list in a NULL response.
   */
  byte[][] HLAownedInstanceAttributeList;

  /**
   * Handle of the registered class of the object instance. This parameter shall be omitted in a
   * NULL response.
   */
  byte[] HLAregisteredClass;

  /**
   * Handle of the known class of the object instance at the joined federate. This parameter shall
   * be omitted in a NULL response.
   */
  byte[] HLAknownClass;

  public byte[] getHLAobjectInstance() {
    return this.HLAobjectInstance;
  }

  public void setHLAobjectInstance(byte[] HLAobjectInstance) {
    this.HLAobjectInstance = HLAobjectInstance;
  }

  public byte[][] getHLAownedInstanceAttributeList() {
    return this.HLAownedInstanceAttributeList;
  }

  public void setHLAownedInstanceAttributeList(byte[][] HLAownedInstanceAttributeList) {
    this.HLAownedInstanceAttributeList = HLAownedInstanceAttributeList;
  }

  public byte[] getHLAregisteredClass() {
    return this.HLAregisteredClass;
  }

  public void setHLAregisteredClass(byte[] HLAregisteredClass) {
    this.HLAregisteredClass = HLAregisteredClass;
  }

  public byte[] getHLAknownClass() {
    return this.HLAknownClass;
  }

  public void setHLAknownClass(byte[] HLAknownClass) {
    this.HLAknownClass = HLAknownClass;
  }
}
