// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * The interaction class shall be acted upon by the RTI. These interactions shall invoke HLA
 * services on behalf of another joined federate. They shall cause the RTI to react as if the
 * service has been invoked by that other joined federate. If exceptions arise as a result of the
 * use of these interactions, they shall be reported via the
 * HLAmanager.HLAfederate.HLAreport.HLAreportMOMexception interaction to all joined federates that
 * subscribe to this interaction. There are two ways an error can occur: the sending federate does
 * not provide all the required arguments as parameters or the preconditions of the spoofed service
 * are not met. Each type of error is reported via the HLAMOMreportMOMexception. NOTE - These
 * interactions shall have the potential to disrupt normal federation execution and should be used
 * with great care.
 */
public class HLAservice extends HLAfederate {}
