// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/** Set the joined federate's subscription status of attributes of an object class */
public class HLAsubscribeObjectClassAttributes extends HLAservice {

  /** Object class for which the joined federate's subscription shall change */
  byte[] HLAobjectClass;

  /**
   * List of handles of attributes of HLAobjectClass to which the joined federate shall now
   * subscribe
   */
  byte[][] HLAattributeList;

  /** Whether the subscription is active */
  Boolean HLAactive;

  public byte[] getHLAobjectClass() {
    return this.HLAobjectClass;
  }

  public void setHLAobjectClass(byte[] HLAobjectClass) {
    this.HLAobjectClass = HLAobjectClass;
  }

  public byte[][] getHLAattributeList() {
    return this.HLAattributeList;
  }

  public void setHLAattributeList(byte[][] HLAattributeList) {
    this.HLAattributeList = HLAattributeList;
  }

  public Boolean getHLAactive() {
    return this.HLAactive;
  }

  public void setHLAactive(Boolean HLAactive) {
    this.HLAactive = HLAactive;
  }
}
