// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/** Cause the joined federate no longer to subscribe to attributes of an object class */
public class HLAunsubscribeObjectClassAttributes extends HLAservice {

  /** Object class for which the joined federate's subscription shall change */
  byte[] HLAobjectClass;

  /**
   * List of handles of attributes of HLAobjectClass to which the joined federate shall now
   * unsubscribe
   */
  byte[][] HLAattributeList;

  public byte[] getHLAobjectClass() {
    return this.HLAobjectClass;
  }

  public void setHLAobjectClass(byte[] HLAobjectClass) {
    this.HLAobjectClass = HLAobjectClass;
  }

  public byte[][] getHLAattributeList() {
    return this.HLAattributeList;
  }

  public void setHLAattributeList(byte[][] HLAattributeList) {
    this.HLAattributeList = HLAattributeList;
  }
}
