// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/**
 * Cause the ownership of attributes of an object instance to be unconditionally divested by the
 * joined federate
 */
public class HLAunconditionalAttributeOwnershipDivestiture extends HLAservice {

  /** Handle of the object instance whose attributes' ownership is to be divested */
  byte[] HLAobjectInstance;

  /**
   * List of handles of instance attributes belonging to HLAobjectInstance whose ownership is to be
   * divested by the joined federate
   */
  byte[][] HLAattributeList;

  public byte[] getHLAobjectInstance() {
    return this.HLAobjectInstance;
  }

  public void setHLAobjectInstance(byte[] HLAobjectInstance) {
    this.HLAobjectInstance = HLAobjectInstance;
  }

  public byte[][] getHLAattributeList() {
    return this.HLAattributeList;
  }

  public void setHLAattributeList(byte[][] HLAattributeList) {
    this.HLAattributeList = HLAattributeList;
  }
}
