// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2025/09/14 01:29:01

package nl.tno.oorti.test.mim4.interactions;

/** Cause the joined federate no longer to publish an interaction class */
public class HLAunpublishInteractionClass extends HLAservice {

  /** Interaction class that the joined federate shall no longer publish */
  byte[] HLAinteractionClass;

  public byte[] getHLAinteractionClass() {
    return this.HLAinteractionClass;
  }

  public void setHLAinteractionClass(byte[] HLAinteractionClass) {
    this.HLAinteractionClass = HLAinteractionClass;
  }
}
